Garmin Fleet Management Controller: CAobrdDriverShipmentsDlg.cpp File Reference
CAobrdDriverShipmentsDlg.cpp File Reference
#include "stdafx.h"
#include "CFmiApplication.h"
#include "CAobrdDriverShipmentsDlg.h"
#include "util.h"
#include "garmin_types.h"
Functions
static COleDateTime convertFromTimeType (time_type aTimestamp)
Convert time_type to COleDateTime for use with CDateTimeCtrl.
static time_type convertToTimeType (COleDateTime &datePart, COleDateTime &timePart)
Convert COleDateTime pairs to time_type.
Function Documentation
static COleDateTime convertFromTimeType (time_type aTimestamp) static
Convert time_type to COleDateTime for use with CDateTimeCtrl.
Definition at line 274 of file CAobrdDriverShipmentsDlg.cpp.
References date_time_data_type::date, date_time_data_type::_date::day, date_time_data_type::_time::hour, date_time_data_type::_time::minute, date_time_data_type::_date::month, date_time_data_type::_time::second, date_time_data_type::time, UTIL_convert_seconds_to_date_type(), UTIL_convert_seconds_to_time_type(), UTIL_convert_UTC_to_local(), and date_time_data_type::_date::year.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList().
static time_type convertToTimeType (COleDateTime & datePart, COleDateTime & timePart) static
Convert COleDateTime pairs to time_type.
Definition at line 253 of file CAobrdDriverShipmentsDlg.cpp.
References date_time_data_type::date, date_time_data_type::_date::day, date_time_data_type::_time::hour, date_time_data_type::_time::minute, date_time_data_type::_date::month, date_time_data_type::_time::second, date_time_data_type::time, UTIL_convert_date_time_to_seconds(), UTIL_convert_local_to_UTC(), UTIL_convert_time_type_to_seconds(), and date_time_data_type::_date::year.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().