Garmin Fleet Management Controller: CFeatureDlg Class Reference
CFeatureDlg Class Reference
FMI Feature (enable) modal dialog.
#include <CFeatureDlg.h>
Public Member Functions
CFeatureDlg (CWnd *aParent, FmiApplicationLayer &aCom)
Constructor.
virtual ~CFeatureDlg ()
Destructor.
afx_msg void OnBnClickedOk ()
Click handler for OK button.
BOOL OnInitDialog ()
Initialize the dialog.
Protected Member Functions
void checkFeature (CButton *aCheckBox, fmi_feature_type aFeature)
Process a feature check box.
Protected Attributes
FmiApplicationLayer & mCom
Reference to the FMI application layer.
uint16 mFeatureCodes [126]
Array of feature codes to send in the FMI Enable packet.
uint8 mFeatureCount
Number of feature codes to send in the FMI Enable packet.
Detailed Description
FMI Feature (enable) modal dialog.
This dialog allows the user to send an FMI Enable packet with the specified features enabled or disabled.
Since
Protocol A607
Definition at line 22 of file CFeatureDlg.h.
Constructor & Destructor Documentation
CFeatureDlg::CFeatureDlg (CWnd * aParent, FmiApplicationLayer & aCom)
Constructor.
Parameters
aParent The parent window
aCom Reference to the FMI communication controller
Definition at line 25 of file CFeatureDlg.cpp.
CFeatureDlg::~CFeatureDlg () virtual
Destructor.
Definition at line 38 of file CFeatureDlg.cpp.
Member Function Documentation
void CFeatureDlg::checkFeature (CButton * aCheckBox, fmi_feature_type aFeature) protected
Process a feature check box.
Based on the state of aCheckBox, add aFeature to mFeatureCodes as enabled or disabled if appropriate.
Parameters
aCheckBox The check box to inspect
aFeature The feature code to enable or disable
Definition at line 69 of file CFeatureDlg.cpp.
References FEATURE_STATE_DISABLED, and FEATURE_STATE_ENABLED.
Referenced by OnBnClickedOk().
void CFeatureDlg::OnBnClickedOk ()
Click handler for OK button.
Build and send an extended FMI enable packet based on the state of the check boxes.
Definition at line 97 of file CFeatureDlg.cpp.
References checkFeature(), CODEPAGE_ASCII, CODEPAGE_UNICODE, custom_avoid_feature_enable_type::enable, FALSE, FEATURE_ID_A607_SUPPORT, FEATURE_ID_AOBRD_SUPPORT, FEATURE_ID_DRIVER_PASSWORDS, FEATURE_ID_MULTIPLE_DRIVERS, FEATURE_ID_UNICODE, FMI_CUSTOM_AVOID_ENABLE_FEATURE_REQUEST, IDC_FEATURE_CHK_A607, IDC_FEATURE_CHK_AOBRD, IDC_FEATURE_CHK_CUST_AVOID, IDC_FEATURE_CHK_MULTIDRIVER, IDC_FEATURE_CHK_PASSWORDS, IDC_FEATURE_CHK_UNICODE, FmiApplicationLayer::mClientCodepage, mCom, mFeatureCodes, mFeatureCount, FmiApplicationLayer::mUseAOBRD, FmiApplicationLayer::mUseMultipleDrivers, FmiApplicationLayer::mUsePasswords, custom_avoid_feature_enable_type::origination_time, FmiApplicationLayer::sendEnable(), FmiApplicationLayer::sendFmiPacket(), TRUE, and UTIL_get_current_garmin_time().
BOOL CFeatureDlg::OnInitDialog ()
Initialize the dialog.
This function is called when the window is created. It gets references to each of the check boxes, and sets the default state of the Unicode Support and A607 Support boxes to checked.
Returns
TRUE, since this function does not set focus to a control
Definition at line 49 of file CFeatureDlg.cpp.
References IDC_FEATURE_CHK_A607, IDC_FEATURE_CHK_CUST_AVOID, and IDC_FEATURE_CHK_UNICODE.
Member Data Documentation
FmiApplicationLayer& CFeatureDlg::mCom protected
Reference to the FMI application layer.
Definition at line 46 of file CFeatureDlg.h.
Referenced by OnBnClickedOk().
uint16 CFeatureDlg::mFeatureCodes[126] protected
Array of feature codes to send in the FMI Enable packet.
Definition at line 52 of file CFeatureDlg.h.
Referenced by OnBnClickedOk().
uint8 CFeatureDlg::mFeatureCount protected
Number of feature codes to send in the FMI Enable packet.
Definition at line 49 of file CFeatureDlg.h.
Referenced by OnBnClickedOk().
The documentation for this class was generated from the following files:
CFeatureDlg.h
CFeatureDlg.cpp