Garmin Fleet Management Controller: CsvWriter Class Reference
CsvWriter Class Reference
#include <CsvWriter.h>
Public Member Functions
CsvWriter (CFile *file)
virtual ~CsvWriter ()
void Finish ()
void NewLine ()
void WriteValue (char *value)
void WriteValue (char *value, int len)
Protected Attributes
CFile * m_file
Detailed Description
Definition at line 16 of file CsvWriter.h.
Constructor & Destructor Documentation
CsvWriter::CsvWriter (CFile * file)
Definition at line 14 of file CsvWriter.cpp.
CsvWriter::~CsvWriter () virtual
Definition at line 20 of file CsvWriter.cpp.
Member Function Documentation
void CsvWriter::Finish ()
Definition at line 63 of file CsvWriter.cpp.
References m_file.
Referenced by AobrdEventLogConverter::convertToCsv().
void CsvWriter::NewLine ()
Definition at line 57 of file CsvWriter.cpp.
References m_file.
Referenced by AobrdEventLogConverter::convertToCsv(), and modifyStatusChangeRecord().
void CsvWriter::WriteValue (char * value)
Definition at line 25 of file CsvWriter.cpp.
Referenced by AobrdEventLogConverter::convertToCsv(), encodeDegreeFields(), encodeStringFields(), encodeTimestampField(), encodeTimestampFields(), encodeUint16Fields(), encodeUint32Fields(), and modifyStatusChangeRecord().
void CsvWriter::WriteValue (char * value, int len)
Definition at line 30 of file CsvWriter.cpp.
References m_file.
Member Data Documentation
CFile* CsvWriter::m_file protected
Definition at line 29 of file CsvWriter.h.
Referenced by Finish(), NewLine(), and WriteValue().
The documentation for this class was generated from the following files:
CsvWriter.h
CsvWriter.cpp