Garmin Fleet Management Controller: CCustomFormsDlg Class Reference
CCustomFormsDlg Class Reference
Browser-based container for listing the Custom Forms library.
#include <CCustomFormsDlg.h>
Public Types
enum { IDD = IDD_CUSTOM_FORMS }
Public Member Functions
CCustomFormsDlg (CWnd *pParent, FmiApplicationLayer &aCom)
Constructor.
virtual ~CCustomFormsDlg ()
Destructor.
void OnBeforeNavigate2 (LPDISPATCH pDisp, VARIANT *URL, VARIANT *Flags, VARIANT *TargetFrameName, VARIANT *PostData, VARIANT *Headers, BOOL *Cancel)
This catches navigation attempts for the purpose of handling application-specific navigation.
void onEvent (EventId aEventId, uint32 aEventData, void *aEventDataPtr)
Handles event callbacks by translating an EventId into a windows message.
Protected Member Functions
bool buildCatalog (LPCTSTR filename)
Construct a catalog document based on the library structure.
BOOL deleteFromDevice (int formId)
virtual void DoDataExchange (CDataExchange *pDX)
Perform dialog data exchange and validation.
BOOL importForm ()
BOOL moveOnDevice (int formId, uint8 newPosition)
afx_msg LRESULT OnFormDeleted (WPARAM, LPARAM)
This function handles form delete ACK event from device.
afx_msg LRESULT OnFormPositionChanged (WPARAM, LPARAM)
This function handles form position report event from device.
afx_msg LRESULT OnFormSubmitReceived (WPARAM, LPARAM)
This function handles completed form submit event from device.
BOOL OnInitDialog ()
This function is called when the window is created.
afx_msg void OnSize (UINT aType, int aClientWidth, int aClientHeight)
Called after the dialog is resized; repositions the contents of the display.
void refreshCatalog ()
This function reconstructs catalog file and redisplays it.
BOOL requestPosition (int formId)
BOOL sendToDevice (LPCTSTR filename)
void transform (LPCTSTR src, XMLTransformer *transformer, CMapStringToString &params)
Transform specified XML document and display in web view.
Protected Attributes
CWebBrowser2 m_browser
XMLTransformer * m_submittedTransform
cache the submitted form transformer for re-use
XMLTransformer * m_templateTransform
cache the form template transformer for re-use
FmiApplicationLayer & mCom
Reference to the FMI communication controller.
Detailed Description
Browser-based container for listing the Custom Forms library.
When first loaded this dialog lists all the forms imported into its file-based repository. Each list item has a link to a preview of the template, as well as links to a preview of any forms submitted against that template.
Definition at line 28 of file CCustomFormsDlg.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
IDD
Definition at line 40 of file CCustomFormsDlg.h.
Constructor & Destructor Documentation
CCustomFormsDlg::CCustomFormsDlg (CWnd * pParent, FmiApplicationLayer & aCom)
Constructor.
Definition at line 39 of file CCustomFormsDlg.cpp.
CCustomFormsDlg::~CCustomFormsDlg () virtual
Destructor.
Definition at line 50 of file CCustomFormsDlg.cpp.
Member Function Documentation
bool CCustomFormsDlg::buildCatalog (LPCTSTR filename) protected
Construct a catalog document based on the library structure.
Definition at line 274 of file CCustomFormsDlg.cpp.
BOOL CCustomFormsDlg::deleteFromDevice (int formId) protected
Definition at line 757 of file CCustomFormsDlg.cpp.
References FMI_CUSTOM_FORM_DEL_REQUEST, and TRUE.
void CCustomFormsDlg::DoDataExchange (CDataExchange * pDX) protected virtual
Perform dialog data exchange and validation.
Parameters
aDataExchange The DDX context
Definition at line 62 of file CCustomFormsDlg.cpp.
References IDC_EMBEDDED_BROWSER.
BOOL CCustomFormsDlg::importForm () protected
Definition at line 553 of file CCustomFormsDlg.cpp.
References FALSE, and TRUE.
BOOL CCustomFormsDlg::moveOnDevice (int formId, uint8 newPosition) protected
Definition at line 766 of file CCustomFormsDlg.cpp.
References FMI_CUSTOM_FORM_MOVE_REQUEST, custom_form_move_type::form_id, custom_form_move_type::new_position, and TRUE.
void CCustomFormsDlg::OnBeforeNavigate2 (LPDISPATCH pDisp, VARIANT * URL, VARIANT * Flags, VARIANT * TargetFrameName, VARIANT * PostData, VARIANT * Headers, BOOL * Cancel)
This catches navigation attempts for the purpose of handling application-specific navigation.
Handle application-specific navigation URLs.
Definition at line 442 of file CCustomFormsDlg.cpp.
References TRUE, and CWebBrowser2::URLDecode().
void CWndEventListener::onEvent (EventId aEventId, uint32 aEventData, void * aEventDataPtr) virtual inherited
Handles event callbacks by translating an EventId into a windows message.
Casts this to a CWnd then posts a Windows message to it. The use of dynamic_cast is used as an alternative to the "dreaded diamond" caused by C++ multiple inheritance.
Parameters
aEventId The event ID
aEventData The event data
aEventDataPtr Pointer to more event data
Note
Interested parties receive these events as Windows messages, i.e., ON_MESSAGE(aEventId, CallbackFunction). aEventData is the WPARAM, and aEventDataPtr is the LPARAM.
Implements EventListener.
Definition at line 29 of file CWndEventListener.cpp.
References EVENT_ID_CNT, and WM_EVENT.
LRESULT CCustomFormsDlg::OnFormDeleted (WPARAM wParam, LPARAM) protected
This function handles form delete ACK event from device.
Definition at line 147 of file CCustomFormsDlg.cpp.
LRESULT CCustomFormsDlg::OnFormPositionChanged (WPARAM wParam, LPARAM lParam) protected
This function handles form position report event from device.
Definition at line 159 of file CCustomFormsDlg.cpp.
LRESULT CCustomFormsDlg::OnFormSubmitReceived (WPARAM , LPARAM) protected
This function handles completed form submit event from device.
Definition at line 171 of file CCustomFormsDlg.cpp.
References SAVE_RECEIVED_FORM_SUBMIT, and unzip().
BOOL CCustomFormsDlg::OnInitDialog () protected
This function is called when the window is created.
Returns
TRUE, since this function does not set focus to a control
Definition at line 72 of file CCustomFormsDlg.cpp.
References TRUE.
void CCustomFormsDlg::OnSize (UINT aType, int aClientWidth, int aClientHeight) protected
Called after the dialog is resized; repositions the contents of the display.
Moves/sizes the contents as follows:
Moves the search box to the bottom-left corner, keeping its size
Moves the packet list to the top-left, expands vertically
Moves the packet detail to the right of the list, expands horizontally to fill the dialog and vertically to match the height of the packet list
Centers the buttons under the packet detail.
Parameters
aType The type of resizing requested (maximized, etc.)
aClientWidth The new width of the client area
aClientHeight The new height of the client area
Definition at line 124 of file CCustomFormsDlg.cpp.
void CCustomFormsDlg::refreshCatalog () protected
This function reconstructs catalog file and redisplays it.
Definition at line 243 of file CCustomFormsDlg.cpp.
References CWebBrowser2::URLDecode().
BOOL CCustomFormsDlg::requestPosition (int formId) protected
Definition at line 778 of file CCustomFormsDlg.cpp.
References FMI_CUSTOM_FORM_GET_POS_REQUEST, and TRUE.
BOOL CCustomFormsDlg::sendToDevice (LPCTSTR filename) protected
Definition at line 686 of file CCustomFormsDlg.cpp.
References FALSE, FMI_FILE_TYPE_CUSTOM_FORMS, minval, and TRUE.
void CCustomFormsDlg::transform (LPCTSTR src, XMLTransformer * transformer, CMapStringToString & params) protected
Transform specified XML document and display in web view.
Definition at line 405 of file CCustomFormsDlg.cpp.
References FileStream::OpenFile(), and XMLTransformer::transform().
Member Data Documentation
CWebBrowser2 CCustomFormsDlg::m_browser protected
Definition at line 70 of file CCustomFormsDlg.h.
XMLTransformer* CCustomFormsDlg::m_submittedTransform protected
cache the submitted form transformer for re-use
Definition at line 75 of file CCustomFormsDlg.h.
XMLTransformer* CCustomFormsDlg::m_templateTransform protected
cache the form template transformer for re-use
Definition at line 73 of file CCustomFormsDlg.h.
FmiApplicationLayer& CCustomFormsDlg::mCom protected
Reference to the FMI communication controller.
Definition at line 78 of file CCustomFormsDlg.h.
The documentation for this class was generated from the following files:
CCustomFormsDlg.h
CCustomFormsDlg.cpp