Garmin Fleet Management Controller: DriverLoginItem Class Reference
DriverLoginItem Class Reference
Data structure to holds an allowed driver login (ID and password). Used by the FmiApplicationLayer to validate logins when driver password support is enabled.
#include <DriverLoginItem.h>
Public Types
typedef std::string key_type
Public Member Functions
DriverLoginItem ()
Constructor.
virtual ~DriverLoginItem ()
Destructor.
void commitName ()
Commit the item name.
CString getCurrentName () const
Get the current name of this item.
CString getDriverId () const
Get the driver ID as a CString.
const key_type & getId () const
Get item's ID.
CString getPassword () const
Set the ID (key) of this item.
BOOL isValid () const
Check whether this item is valid.
void readFromStream (std::istream &aStream)
Read a DriverLoginItem from an input stream.
void save ()
Save this item.
void setId (const key_type &aId)
Set the ID (key) of this item.
void setParent (FileBackedMap< DriverLoginItem > *aParent)
Set the parent map of this item.
void setParent (FileBackedMap< ClientListItem > *aParent)
Set the parent.
void setPassword (const std::string &aPassword)
Set the password of this driver.
void setUpdateName (CString aName)
Set pending name.
void setValid (BOOL aValid=TRUE)
Set this item as valid.
void writeToStream (std::ofstream &aStream) const
Write a DriverLoginItem to an output stream.
Protected Attributes
CString mCurrentName
The last name acknowledged by the client.
key_type mId
The unique ID of this item.
BOOL mIsValid
True if this list item is mIsValid.
CString mUpdateName
The last name entered by the user.
Private Attributes
std::string mDriverId
The driver ID, UTF8 encoded.
std::string mDriverPassword
The driver password, UTF8 encoded.
FileBackedMap< DriverLoginItem > * mParent
The map that this DriverLoginItem is a part of.
Detailed Description
Data structure to holds an allowed driver login (ID and password). Used by the FmiApplicationLayer to validate logins when driver password support is enabled.
Since
Protocol A607
Definition at line 21 of file DriverLoginItem.h.
Member Typedef Documentation
typedef std::string DriverLoginItem::key_type
Definition at line 25 of file DriverLoginItem.h.
Constructor & Destructor Documentation
DriverLoginItem::DriverLoginItem ()
Constructor.
Definition at line 17 of file DriverLoginItem.cpp.
DriverLoginItem::~DriverLoginItem () virtual
Destructor.
Definition at line 26 of file DriverLoginItem.cpp.
Member Function Documentation
void ClientListItem::commitName () inherited
Commit the item name.
Commit the item name and set the ClientListItem as valid
Definition at line 29 of file ClientListItem.cpp.
References ClientListItem::mCurrentName, ClientListItem::mUpdateName, and ClientListItem::setValid().
Referenced by FmiApplicationLayer::rx().
CString ClientListItem::getCurrentName () const inherited
Get the current name of this item.
Returns
The current (committed) name
Definition at line 39 of file ClientListItem.cpp.
References ClientListItem::mCurrentName.
Referenced by CDriverIdAndStatusDlg::OnLbnSelchangeStatuslist(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
CString DriverLoginItem::getDriverId () const
Get the driver ID as a CString.
Returns
the driver ID, as a CString
Definition at line 34 of file DriverLoginItem.cpp.
References mDriverId.
Referenced by CDriverLoginDlg::OnLbnSelchangeDriverList().
const DriverLoginItem::key_type & DriverLoginItem::getId () const
Get item's ID.
Get the unique ID (driver ID) of this item
Returns
The item's ID
Reimplemented from ClientListItem.
Definition at line 49 of file DriverLoginItem.cpp.
References mDriverId.
CString DriverLoginItem::getPassword () const
Set the ID (key) of this item.
Sets the key associated with this item
Definition at line 58 of file DriverLoginItem.cpp.
References mDriverPassword.
Referenced by CDriverLoginDlg::OnLbnSelchangeDriverList(), and FmiApplicationLayer::rx().
BOOL ClientListItem::isValid () const inherited
Check whether this item is valid.
Returns
TRUE if the item is valid, FALSE otherwise
Definition at line 58 of file ClientListItem.cpp.
References ClientListItem::mIsValid.
Referenced by CAobrdDriversDlg::OnBnClickedSet(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
void DriverLoginItem::readFromStream (std::istream & aStream) virtual
Read a DriverLoginItem from an input stream.
Read id and password from the input stream, and updates the member variables appropriately.
Parameters
aStream The stream to read from
Reimplemented from ClientListItem.
Definition at line 75 of file DriverLoginItem.cpp.
References TRUE.
void DriverLoginItem::save () virtual
Save this item.
Invokes parent to save all items
Reimplemented from ClientListItem.
Definition at line 109 of file DriverLoginItem.cpp.
References mParent, and FileBackedMap< T >::save().
void DriverLoginItem::setId (const key_type & aId)
Set the ID (key) of this item.
Sets the key associated with this item
Parameters
aId The item's ID
Reimplemented from ClientListItem.
Definition at line 123 of file DriverLoginItem.cpp.
void DriverLoginItem::setParent (FileBackedMap< DriverLoginItem > * aParent)
Set the parent map of this item.
Sets the map that this item is in
Parameters
aParent The item's parent
Definition at line 136 of file DriverLoginItem.cpp.
void ClientListItem::setParent (FileBackedMap< ClientListItem > * aParent) inherited
Set the parent.
Parameters
aParent The FileBackedMap that contains this item
Definition at line 113 of file ClientListItem.cpp.
void DriverLoginItem::setPassword (const std::string & aPassword)
Set the password of this driver.
Sets the password for this driver login
Parameters
aPassword The driver's password
Definition at line 149 of file DriverLoginItem.cpp.
Referenced by CDriverLoginDlg::OnBnClickedSet().
void ClientListItem::setUpdateName (CString aName) inherited
Set pending name.
Set the pending name of this ClientListItem. This does not become the item's name until commitName is called.
Parameters
aName The pending name to set
Definition at line 127 of file ClientListItem.cpp.
Referenced by FmiApplicationLayer::sendCannedMessage(), FmiApplicationLayer::sendCannedResponse(), FmiApplicationLayer::sendCreateWaypointCat(), FmiApplicationLayer::sendDriverStatusListItem(), and FmiApplicationLayer::sendWaypoint().
void ClientListItem::setValid (BOOL aValid = TRUE) inherited
Set this item as valid.
Set the valid flag. If this item is part of a FileBackedMap, save the map.
Parameters
aValid If TRUE, the item is valid.
Definition at line 141 of file ClientListItem.cpp.
Referenced by ClientListItem::commitName(), CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendA603Stop(), FmiApplicationLayer::sendDeleteWaypointCat(), and CMapViewerDlg::sendRouteToDevice().
void DriverLoginItem::writeToStream (std::ofstream & aStream) const virtual
Write a DriverLoginItem to an output stream.
Append driver ID and password to the output stream.
Parameters
aStream The stream to write to
Reimplemented from ClientListItem.
Definition at line 164 of file DriverLoginItem.cpp.
Member Data Documentation
CString ClientListItem::mCurrentName protected inherited
The last name acknowledged by the client.
Definition at line 75 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), ClientListItem::commitName(), and ClientListItem::getCurrentName().
std::string DriverLoginItem::mDriverId private
The driver ID, UTF8 encoded.
Definition at line 45 of file DriverLoginItem.h.
Referenced by getDriverId(), and getId().
std::string DriverLoginItem::mDriverPassword private
The driver password, UTF8 encoded.
Definition at line 48 of file DriverLoginItem.h.
Referenced by getPassword().
key_type ClientListItem::mId protected inherited
The unique ID of this item.
Definition at line 84 of file ClientListItem.h.
Referenced by ClientListItem::getId().
BOOL ClientListItem::mIsValid protected inherited
True if this list item is mIsValid.
Definition at line 81 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::isValid().
FileBackedMap<DriverLoginItem>* DriverLoginItem::mParent private
The map that this DriverLoginItem is a part of.
Definition at line 51 of file DriverLoginItem.h.
Referenced by save().
CString ClientListItem::mUpdateName protected inherited
The last name entered by the user.
Definition at line 78 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::commitName().
The documentation for this class was generated from the following files:
DriverLoginItem.h
DriverLoginItem.cpp