Garmin Fleet Management Controller: CAobrdDriverShipmentsDlg Class Reference
CAobrdDriverShipmentsDlg Class Reference
Dialog allowing the user to manage AOBRD driver shipments.
#include <CAobrdDriverShipmentsDlg.h>
Public Member Functions
virtual ~CAobrdDriverShipmentsDlg ()
Destructor.
Static Public Member Functions
static BOOL ShowShipments (CWnd *aParent, AobrdDriverItem *driver)
Main entry point for showing the shipments editor.
Protected Member Functions
CAobrdDriverShipmentsDlg (CWnd *aParent, AobrdDriverItem *aDriver)
Constructor.
void clearData ()
Clear values from the editable fields.
virtual void DoDataExchange (CDataExchange *pDX)
Perform dialog data exchange and validation.
afx_msg void OnBnClickedDelete ()
Button handler for the Delete button.
afx_msg void OnBnClickedNew ()
Button handler for the New button.
afx_msg void OnBnClickedOk ()
Button handler for the OK button.
afx_msg void OnBnClickedSet ()
Button handler for the Set button.
afx_msg void OnCancel ()
Handler for the Cancel action.
afx_msg void OnChangeShipmentData ()
Edit/Change handler for the shipment-specific data controls.
afx_msg void OnDateTimeCtrlKillFocus (NMHDR *pNotifyStruct, LRESULT *result)
Handles the kill focus event for date time controls.
afx_msg void OnDateTimeCtrlSetFocus (NMHDR *pNotifyStruct, LRESULT *result)
Handles the set focus event for any date time ctrl.
afx_msg void OnEnKillfocusLoginEdit ()
Handles the kill focus event for the driver ID and password edit boxes.
afx_msg void OnEnSetfocusLoginEdit ()
Handles the set focus event for the driver ID and password edit boxes.
BOOL OnInitDialog ()
This function is called when the window is created.
afx_msg void OnLbnKillfocusShipmentList ()
Handles the kill focus event for the driver list.
afx_msg void OnLbnSelchangeShipmentList ()
Selection Changed handler for the Shipments List box.
afx_msg void OnLbnSetfocusShipmentList ()
Handles the set focus event for the driver list.
void PostNcDestroy ()
Called by MFC after the window has been destroyed; performs final termination activities.
void updateListBox ()
Update the shipments list box from the list owned by the driver.
Protected Attributes
CString mCommodity
DDX member: the contents of the Commodity edit box.
CString mDocumentNumber
DDX member: the contents of the Document Number edit box.
AobrdDriverItem * mDriver
pointer to the driver whose shipments are being edited
COleDateTime mEndTimeDate
DDX member: the contents of the End Time Date control.
COleDateTime mEndTimeTime
DDX member: the contents of the End Time Time control.
CListBox mListBox
List box control containing the shipments.
int mSelectedIndex
Index of the list box item currently selected.
CString mShipperName
DDX member: the contents of the Shipper Name edit box.
COleDateTime mStartTimeDate
DDX member: the contents of the Start Time Date control.
COleDateTime mStartTimeTime
DDX member: the contents of the Start Time Time control.
COleDateTime mTimestampDate
DDX member: the contents of the Timestamp Date control.
COleDateTime mTimestampTime
DDX member: the contents of the Timestamp Time control.
Detailed Description
Dialog allowing the user to manage AOBRD driver shipments.
This dialog allows the user to set up a database of driver shipments that are downloaded to device during driver login.
Since
Protocol A610
Definition at line 24 of file CAobrdDriverShipmentsDlg.h.
Constructor & Destructor Documentation
CAobrdDriverShipmentsDlg::~CAobrdDriverShipmentsDlg () virtual
Destructor.
Definition at line 97 of file CAobrdDriverShipmentsDlg.cpp.
CAobrdDriverShipmentsDlg::CAobrdDriverShipmentsDlg (CWnd * aParent, AobrdDriverItem * aDriver) protected
Constructor.
Parameters
aParent The parent window.
aDriver Reference to the driver being edited
Definition at line 75 of file CAobrdDriverShipmentsDlg.cpp.
Member Function Documentation
void CAobrdDriverShipmentsDlg::clearData () protected
Clear values from the editable fields.
Definition at line 155 of file CAobrdDriverShipmentsDlg.cpp.
void CAobrdDriverShipmentsDlg::DoDataExchange (CDataExchange * aDataExchange) protected virtual
Perform dialog data exchange and validation.
Parameters
aDataExchange The DDX context
Definition at line 106 of file CAobrdDriverShipmentsDlg.cpp.
References IDC_DRIVER_SHIPMENTS_EDIT_COMMODITY, IDC_DRIVER_SHIPMENTS_EDIT_DOC_NUM, IDC_DRIVER_SHIPMENTS_EDIT_SHIPPER, IDC_DRIVER_SHIPMENTS_END_TIME_DATE, IDC_DRIVER_SHIPMENTS_END_TIME_TIME, IDC_DRIVER_SHIPMENTS_LST_SHIPMENTS, IDC_DRIVER_SHIPMENTS_START_TIME_DATE, IDC_DRIVER_SHIPMENTS_START_TIME_TIME, IDC_DRIVER_SHIPMENTS_TIMESTAMP_DATE, and IDC_DRIVER_SHIPMENTS_TIMESTAMP_TIME.
void CAobrdDriverShipmentsDlg::OnBnClickedDelete () protected
Button handler for the Delete button.
Remove the selected driver from the allowed logins.
Definition at line 229 of file CAobrdDriverShipmentsDlg.cpp.
References FALSE, IDC_DRIVER_SHIPMENTS_BTN_DELETE, IDC_DRIVER_SHIPMENTS_BTN_NEW, IDC_DRIVER_SHIPMENTS_BTN_SET, and TRUE.
void CAobrdDriverShipmentsDlg::OnBnClickedNew () protected
Button handler for the New button.
Clears the edit controls and list box selection in order to allow a new item to be created
Definition at line 208 of file CAobrdDriverShipmentsDlg.cpp.
References FALSE, IDC_DRIVER_SHIPMENTS_BTN_DELETE, IDC_DRIVER_SHIPMENTS_BTN_NEW, IDC_DRIVER_SHIPMENTS_BTN_SET, and TRUE.
void CAobrdDriverShipmentsDlg::OnBnClickedOk () protected
Button handler for the OK button.
Closes the window.
Definition at line 402 of file CAobrdDriverShipmentsDlg.cpp.
void CAobrdDriverShipmentsDlg::OnBnClickedSet () protected
Button handler for the Set button.
Saves the new shipment info
Definition at line 297 of file CAobrdDriverShipmentsDlg.cpp.
References convertToTimeType(), FALSE, AobrdShipment::setCommodity(), AobrdShipment::setDocNumber(), AobrdShipment::setServerEndTime(), AobrdShipment::setServerStartTime(), AobrdShipment::setServerTimestamp(), AobrdShipment::setShipperName(), and TRUE.
void CAobrdDriverShipmentsDlg::OnCancel () protected
Handler for the Cancel action.
Closes the window.
Definition at line 411 of file CAobrdDriverShipmentsDlg.cpp.
void CAobrdDriverShipmentsDlg::OnChangeShipmentData () protected
Edit/Change handler for the shipment-specific data controls.
If any of controls are unset, disables the Set button; if all are specified, enables the Set button.
Definition at line 343 of file CAobrdDriverShipmentsDlg.cpp.
References FALSE, IDC_DRIVER_SHIPMENTS_BTN_SET, and TRUE.
void CAobrdDriverShipmentsDlg::OnDateTimeCtrlKillFocus (NMHDR * pNotifyStruct, LRESULT * result) protected
Handles the kill focus event for date time controls.
Sets the default control to the OK button so that it is activated if the user presses the Enter key.
Definition at line 462 of file CAobrdDriverShipmentsDlg.cpp.
void CAobrdDriverShipmentsDlg::OnDateTimeCtrlSetFocus (NMHDR * pNotifyStruct, LRESULT * result) protected
Handles the set focus event for any date time ctrl.
Sets the default control to the Set button so that it is activated if the user presses the Enter key.
Definition at line 441 of file CAobrdDriverShipmentsDlg.cpp.
References IDC_DRIVER_SHIPMENTS_BTN_SET.
void CAobrdDriverShipmentsDlg::OnEnKillfocusLoginEdit () protected
Handles the kill focus event for the driver ID and password edit boxes.
Sets the default control to the OK button so that it is activated if the user presses the Enter key.
Definition at line 452 of file CAobrdDriverShipmentsDlg.cpp.
void CAobrdDriverShipmentsDlg::OnEnSetfocusLoginEdit () protected
Handles the set focus event for the driver ID and password edit boxes.
Sets the default control to the Set button so that it is activated if the user presses the Enter key.
Definition at line 431 of file CAobrdDriverShipmentsDlg.cpp.
References IDC_DRIVER_SHIPMENTS_BTN_SET.
BOOL CAobrdDriverShipmentsDlg::OnInitDialog () protected
This function is called when the window is created.
This function is called when the window is created. It initializes the shipments list, and sets the initial position of the window.
Returns
TRUE, since this function does not set focus to a control
Definition at line 130 of file CAobrdDriverShipmentsDlg.cpp.
References FALSE, IDC_DRIVER_SHIPMENTS_BTN_DELETE, IDC_DRIVER_SHIPMENTS_BTN_NEW, IDC_DRIVER_SHIPMENTS_EDIT_COMMODITY, IDC_DRIVER_SHIPMENTS_EDIT_DOC_NUM, IDC_DRIVER_SHIPMENTS_EDIT_SHIPPER, and TRUE.
void CAobrdDriverShipmentsDlg::OnLbnKillfocusShipmentList () protected
Handles the kill focus event for the driver list.
Sets the default control to the OK button so that it is activated if the user presses the Enter key.
Definition at line 482 of file CAobrdDriverShipmentsDlg.cpp.
void CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList () protected
Selection Changed handler for the Shipments List box.
Fills in the fields of the dialog with the information from the selected list item, for easy editing.
Definition at line 366 of file CAobrdDriverShipmentsDlg.cpp.
References convertFromTimeType(), FALSE, AobrdShipment::getCommodity(), AobrdShipment::getDocNumber(), AobrdShipment::getServerEndTime(), AobrdShipment::getServerStartTime(), AobrdShipment::getServerTimestamp(), AobrdShipment::getShipperName(), IDC_DRIVER_SHIPMENTS_BTN_DELETE, IDC_DRIVER_SHIPMENTS_BTN_NEW, IDC_DRIVER_SHIPMENTS_LST_SHIPMENTS, and TRUE.
void CAobrdDriverShipmentsDlg::OnLbnSetfocusShipmentList () protected
Handles the set focus event for the driver list.
Sets the default control to the Delete button so that it is activated if the user presses the Enter key.
Definition at line 472 of file CAobrdDriverShipmentsDlg.cpp.
References IDC_DRIVER_SHIPMENTS_BTN_DELETE.
void CAobrdDriverShipmentsDlg::PostNcDestroy () protected
Called by MFC after the window has been destroyed; performs final termination activities.
Definition at line 420 of file CAobrdDriverShipmentsDlg.cpp.
BOOL CAobrdDriverShipmentsDlg::ShowShipments (CWnd * aParent, AobrdDriverItem * aDriver) static
Main entry point for showing the shipments editor.
Parameters
aParent The parent window.
aDriver Reference to the driver being edited
Definition at line 62 of file CAobrdDriverShipmentsDlg.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedShipments().
void CAobrdDriverShipmentsDlg::updateListBox () protected
Update the shipments list box from the list owned by the driver.
Definition at line 172 of file CAobrdDriverShipmentsDlg.cpp.
References AobrdShipment::getCommodity(), AobrdShipment::getDocNumber(), and AobrdShipment::getShipperName().
Member Data Documentation
CString CAobrdDriverShipmentsDlg::mCommodity protected
DDX member: the contents of the Commodity edit box.
Definition at line 77 of file CAobrdDriverShipmentsDlg.h.
CString CAobrdDriverShipmentsDlg::mDocumentNumber protected
DDX member: the contents of the Document Number edit box.
Definition at line 74 of file CAobrdDriverShipmentsDlg.h.
AobrdDriverItem* CAobrdDriverShipmentsDlg::mDriver protected
pointer to the driver whose shipments are being edited
Definition at line 98 of file CAobrdDriverShipmentsDlg.h.
COleDateTime CAobrdDriverShipmentsDlg::mEndTimeDate protected
DDX member: the contents of the End Time Date control.
Definition at line 92 of file CAobrdDriverShipmentsDlg.h.
COleDateTime CAobrdDriverShipmentsDlg::mEndTimeTime protected
DDX member: the contents of the End Time Time control.
Definition at line 95 of file CAobrdDriverShipmentsDlg.h.
CListBox CAobrdDriverShipmentsDlg::mListBox protected
List box control containing the shipments.
Definition at line 65 of file CAobrdDriverShipmentsDlg.h.
int CAobrdDriverShipmentsDlg::mSelectedIndex protected
Index of the list box item currently selected.
Definition at line 68 of file CAobrdDriverShipmentsDlg.h.
CString CAobrdDriverShipmentsDlg::mShipperName protected
DDX member: the contents of the Shipper Name edit box.
Definition at line 71 of file CAobrdDriverShipmentsDlg.h.
COleDateTime CAobrdDriverShipmentsDlg::mStartTimeDate protected
DDX member: the contents of the Start Time Date control.
Definition at line 86 of file CAobrdDriverShipmentsDlg.h.
COleDateTime CAobrdDriverShipmentsDlg::mStartTimeTime protected
DDX member: the contents of the Start Time Time control.
Definition at line 89 of file CAobrdDriverShipmentsDlg.h.
COleDateTime CAobrdDriverShipmentsDlg::mTimestampDate protected
DDX member: the contents of the Timestamp Date control.
Definition at line 80 of file CAobrdDriverShipmentsDlg.h.
COleDateTime CAobrdDriverShipmentsDlg::mTimestampTime protected
DDX member: the contents of the Timestamp Time control.
Definition at line 83 of file CAobrdDriverShipmentsDlg.h.
The documentation for this class was generated from the following files:
CAobrdDriverShipmentsDlg.h
CAobrdDriverShipmentsDlg.cpp