Garmin Fleet Management Controller: CTxtMsgFromClient Class Reference
CTxtMsgFromClient Class Reference
Modal pop up dialog displaying a client to server open text message.
#include <CTxtMsgFromClient.h>
Public Member Functions
CTxtMsgFromClient (CWnd *aParent, FmiApplicationLayer &aCom, const text_msg_from_client_event_type *aEvent)
Constructor.
virtual ~CTxtMsgFromClient ()
Destructor.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *aDataExchange)
Perform dialog data exchange and validation.
BOOL OnInitDialog ()
Initialize the dialog.
Protected Attributes
FmiApplicationLayer & mCom
Reference to the FMI communication controller.
CString mLatitude
String representation of device latitude.
CString mLinkId
String representation of the link ID (corresponding server to client message ID)
CString mLongitude
String representation of device longitude.
CString mMessageId
String representation of the message ID.
CString mMessageText
String representation of the text message.
CString mOriginationTime
String representation of the origination time on the client.
text_msg_from_client_event_type mTextMessageEvent
The text message event that caused this dialog to be displayed.
Detailed Description
Modal pop up dialog displaying a client to server open text message.
Displays the last client to server open text message in a dialog box. The mOriginationTime, message text, and message ID are retrieved from the event passed to the constructor.
Since
Protocol A603
Definition at line 24 of file CTxtMsgFromClient.h.
Constructor & Destructor Documentation
CTxtMsgFromClient::CTxtMsgFromClient (CWnd * aParent, FmiApplicationLayer & aCom, const text_msg_from_client_event_type * aEvent)
Constructor.
Parameters
aParent The parent of this dialog
aCom Reference to the FMI communication controller
aEvent The text message received from the client
Definition at line 28 of file CTxtMsgFromClient.cpp.
CTxtMsgFromClient::~CTxtMsgFromClient () virtual
Destructor.
Definition at line 48 of file CTxtMsgFromClient.cpp.
Member Function Documentation
void CTxtMsgFromClient::DoDataExchange (CDataExchange * aDataExchange) protected virtual
Perform dialog data exchange and validation.
Parameters
aDataExchange The DDX context
Definition at line 57 of file CTxtMsgFromClient.cpp.
References IDC_CLIENTMSG_TXT_ID, IDC_CLIENTMSG_TXT_LAT, IDC_CLIENTMSG_TXT_LINK_ID, IDC_CLIENTMSG_TXT_LON, IDC_CLIENTMSG_TXT_MESSAGE, and IDC_CLIENTMSG_TXT_TIME.
BOOL CTxtMsgFromClient::OnInitDialog () protected
Initialize the dialog.
This function is called when the window is created. It sets up the parent, so it can get info from and send a message to FmiApplicationLayer. It also initializes the text boxes from the FmiApplicationLayer members which contain the text message details.
Returns
TRUE, since this function does not set focus to a control
Definition at line 81 of file CTxtMsgFromClient.cpp.
References FALSE, INVALID_LAT, text_msg_from_client_event_type::latitude, text_msg_from_client_event_type::link_id, text_msg_from_client_event_type::longitude, FmiApplicationLayer::mClientCodepage, mCom, text_msg_from_client_event_type::message_id, text_msg_from_client_event_type::message_text, mLatitude, mLinkId, mLongitude, mMessageId, mMessageText, mOriginationTime, mTextMessageEvent, text_msg_from_client_event_type::origination_time, MessageId::toCString(), TRUE, UTIL_convert_seconds_to_time_type(), UTIL_convert_semicircles_to_degrees(), UTIL_convert_UTC_to_local(), and UTIL_format_time_string().
Member Data Documentation
FmiApplicationLayer& CTxtMsgFromClient::mCom protected
Reference to the FMI communication controller.
Definition at line 48 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
CString CTxtMsgFromClient::mLatitude protected
String representation of device latitude.
Definition at line 68 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
CString CTxtMsgFromClient::mLinkId protected
String representation of the link ID (corresponding server to client message ID)
Definition at line 64 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
CString CTxtMsgFromClient::mLongitude protected
String representation of device longitude.
Definition at line 66 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
CString CTxtMsgFromClient::mMessageId protected
String representation of the message ID.
Definition at line 60 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
CString CTxtMsgFromClient::mMessageText protected
String representation of the text message.
Definition at line 57 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
CString CTxtMsgFromClient::mOriginationTime protected
String representation of the origination time on the client.
Definition at line 54 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
text_msg_from_client_event_type CTxtMsgFromClient::mTextMessageEvent protected
The text message event that caused this dialog to be displayed.
Definition at line 51 of file CTxtMsgFromClient.h.
Referenced by OnInitDialog().
The documentation for this class was generated from the following files:
CTxtMsgFromClient.h
CTxtMsgFromClient.cpp