Garmin Fleet Management Controller: FileStream Class Reference
FileStream Class Reference
File-based implementation of IStream interface.
#include <FileStream.h>
Public Member Functions
FileStream (HANDLE hFile)
File-based implementation of IStream interface.
virtual ~FileStream (void)
virtual ULONG STDMETHODCALLTYPE AddRef (void)
virtual HRESULT STDMETHODCALLTYPE Clone (IStream **)
virtual HRESULT STDMETHODCALLTYPE Commit (DWORD)
virtual HRESULT STDMETHODCALLTYPE CopyTo (IStream *, ULARGE_INTEGER, ULARGE_INTEGER *, ULARGE_INTEGER *)
virtual HRESULT STDMETHODCALLTYPE LockRegion (ULARGE_INTEGER, ULARGE_INTEGER, DWORD)
virtual HRESULT STDMETHODCALLTYPE QueryInterface (REFIID iid, void **ppvObject)
virtual HRESULT STDMETHODCALLTYPE Read (void *pv, ULONG cb, ULONG *pcbRead)
virtual ULONG STDMETHODCALLTYPE Release (void)
virtual HRESULT STDMETHODCALLTYPE Revert (void)
virtual HRESULT STDMETHODCALLTYPE Seek (LARGE_INTEGER liDistanceToMove, DWORD dwOrigin, ULARGE_INTEGER *lpNewFilePointer)
virtual HRESULT STDMETHODCALLTYPE SetSize (ULARGE_INTEGER)
virtual HRESULT STDMETHODCALLTYPE Stat (STATSTG *pStatstg, DWORD grfStatFlag)
virtual HRESULT STDMETHODCALLTYPE UnlockRegion (ULARGE_INTEGER, ULARGE_INTEGER, DWORD)
virtual HRESULT STDMETHODCALLTYPE Write (void const *pv, ULONG cb, ULONG *pcbWritten)
Static Public Member Functions
static HRESULT OpenFile (LPCWSTR pName, IStream **ppStream, bool fWrite)
Private Attributes
HANDLE _hFile
LONG _refcount
Detailed Description
File-based implementation of IStream interface.
This is taken directly from the Microsoft SDK examples site for use with the MSXML XSL transformation module
Definition at line 18 of file FileStream.h.
Constructor & Destructor Documentation
FileStream::FileStream (HANDLE hFile)
File-based implementation of IStream interface.
This is taken directly from the Microsoft SDK examples site for use with the MSXML XSL transformation module
Definition at line 18 of file FileStream.cpp.
References _hFile, and _refcount.
Referenced by OpenFile().
FileStream::~FileStream (void) virtual
Definition at line 24 of file FileStream.cpp.
References _hFile.
Member Function Documentation
ULONG STDMETHODCALLTYPE FileStream::AddRef (void) virtual
Definition at line 61 of file FileStream.cpp.
References _refcount.
Referenced by QueryInterface().
virtual HRESULT STDMETHODCALLTYPE FileStream::Clone (IStream **) inline virtual
Definition at line 43 of file FileStream.h.
virtual HRESULT STDMETHODCALLTYPE FileStream::Commit (DWORD) inline virtual
Definition at line 39 of file FileStream.h.
virtual HRESULT STDMETHODCALLTYPE FileStream::CopyTo (IStream * , ULARGE_INTEGER , ULARGE_INTEGER * , ULARGE_INTEGER *) inline virtual
Definition at line 38 of file FileStream.h.
virtual HRESULT STDMETHODCALLTYPE FileStream::LockRegion (ULARGE_INTEGER , ULARGE_INTEGER , DWORD) inline virtual
Definition at line 41 of file FileStream.h.
HRESULT FileStream::OpenFile (LPCWSTR pName, IStream ** ppStream, bool fWrite) static
Definition at line 32 of file FileStream.cpp.
References FileStream().
Referenced by CCustomFormsDlg::transform().
HRESULT STDMETHODCALLTYPE FileStream::QueryInterface (REFIID iid, void ** ppvObject) virtual
Definition at line 48 of file FileStream.cpp.
References AddRef().
HRESULT STDMETHODCALLTYPE FileStream::Read (void * pv, ULONG cb, ULONG * pcbRead) virtual
Definition at line 74 of file FileStream.cpp.
References _hFile.
ULONG STDMETHODCALLTYPE FileStream::Release (void) virtual
Definition at line 66 of file FileStream.cpp.
References _refcount.
virtual HRESULT STDMETHODCALLTYPE FileStream::Revert (void) inline virtual
Definition at line 40 of file FileStream.h.
HRESULT STDMETHODCALLTYPE FileStream::Seek (LARGE_INTEGER liDistanceToMove, DWORD dwOrigin, ULARGE_INTEGER * lpNewFilePointer) virtual
Definition at line 86 of file FileStream.cpp.
References _hFile.
virtual HRESULT STDMETHODCALLTYPE FileStream::SetSize (ULARGE_INTEGER) inline virtual
Definition at line 37 of file FileStream.h.
HRESULT STDMETHODCALLTYPE FileStream::Stat (STATSTG * pStatstg, DWORD grfStatFlag) virtual
Definition at line 113 of file FileStream.cpp.
References _hFile.
virtual HRESULT STDMETHODCALLTYPE FileStream::UnlockRegion (ULARGE_INTEGER , ULARGE_INTEGER , DWORD) inline virtual
Definition at line 42 of file FileStream.h.
HRESULT STDMETHODCALLTYPE FileStream::Write (void const * pv, ULONG cb, ULONG * pcbWritten) virtual
Definition at line 80 of file FileStream.cpp.
References _hFile.
Member Data Documentation
HANDLE FileStream::_hFile private
Definition at line 50 of file FileStream.h.
Referenced by FileStream(), Read(), Seek(), Stat(), Write(), and ~FileStream().
LONG FileStream::_refcount private
Definition at line 51 of file FileStream.h.
Referenced by AddRef(), FileStream(), and Release().
The documentation for this class was generated from the following files:
FileStream.h
FileStream.cpp