Garmin Fleet Management Controller: InboxListItem Class Reference
InboxListItem Class Reference
Inbox List Item.
#include <InboxListItem.h>
Public Types
typedef MessageId key_type
Public Member Functions
void commitName ()
Commit the item name.
CString getCurrentName () const
Get the current name of this item.
const key_type & getId () const
Get the ID associated with this item.
BOOL isValid () const
Check whether this item is valid.
void readFromStream (std::istream &aStream)
Read an InboxListItem from an istream.
void setId (const key_type &aId)
Set the ID associated with this item.
void setId (const key_type &aId)
Set item's ID.
void setParent (FileBackedMap< InboxListItem > *aParent)
Set the parent of this item.
void setParent (FileBackedMap< ClientListItem > *aParent)
Set the parent.
void setUpdateName (CString aName)
Set pending name.
void setValid (BOOL aValid=TRUE)
Set this item as valid.
void writeToStream (std::ofstream &aStream)
Write an InboxListItem to an output stream.
virtual void writeToStream (std::ofstream &aStream) const
Write a ClientListItem to an output stream.
Protected Member Functions
virtual void save ()
Save this item.
Protected Attributes
CString mCurrentName
The last name acknowledged by the client.
key_type mId
The unique ID of this item.
BOOL mIsValid
True if this list item is mIsValid.
CString mUpdateName
The last name entered by the user.
Private Attributes
MessageId messageId
FileBackedMap< InboxListItem > * mParent
Detailed Description
Inbox List Item.
Definition at line 19 of file InboxListItem.h.
Member Typedef Documentation
typedef MessageId InboxListItem::key_type
Definition at line 22 of file InboxListItem.h.
Member Function Documentation
void ClientListItem::commitName () inherited
Commit the item name.
Commit the item name and set the ClientListItem as valid
Definition at line 29 of file ClientListItem.cpp.
References ClientListItem::mCurrentName, ClientListItem::mUpdateName, and ClientListItem::setValid().
Referenced by FmiApplicationLayer::rx().
CString ClientListItem::getCurrentName () const inherited
Get the current name of this item.
Returns
The current (committed) name
Definition at line 39 of file ClientListItem.cpp.
References ClientListItem::mCurrentName.
Referenced by CDriverIdAndStatusDlg::OnLbnSelchangeStatuslist(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
const InboxListItem::key_type & InboxListItem::getId () const
Get the ID associated with this item.
Returns
The item's ID
Reimplemented from ClientListItem.
Definition at line 29 of file InboxListItem.cpp.
References messageId.
BOOL ClientListItem::isValid () const inherited
Check whether this item is valid.
Returns
TRUE if the item is valid, FALSE otherwise
Definition at line 58 of file ClientListItem.cpp.
References ClientListItem::mIsValid.
Referenced by CAobrdDriversDlg::OnBnClickedSet(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
void InboxListItem::readFromStream (std::istream & aStream) virtual
Read an InboxListItem from an istream.
Parameters
aStream The stream to read from
Reimplemented from ClientListItem.
Definition at line 51 of file InboxListItem.cpp.
References TRUE.
void ClientListItem::save () protected virtual inherited
Save this item.
Invokes parent to save all items
Reimplemented in AobrdDriverItem, WaypointListItem, and DriverLoginItem.
Definition at line 172 of file ClientListItem.cpp.
References ClientListItem::mParent, and FileBackedMap< T >::save().
void InboxListItem::setId (const key_type & aId)
Set the ID associated with this item.
Parameters
aId The item's ID
Definition at line 18 of file InboxListItem.cpp.
void ClientListItem::setId (const key_type & aId) inherited
Set item's ID.
Parameters
aId The item's ID
Reimplemented in DriverLoginItem.
Definition at line 101 of file ClientListItem.cpp.
Referenced by CStopNewDlg::OnBnClickedOk(), and FmiApplicationLayer::sendCannedMessage().
void InboxListItem::setParent (FileBackedMap< InboxListItem > * aParent)
Set the parent of this item.
Parameters
aParent The item's parent
Definition at line 39 of file InboxListItem.cpp.
void ClientListItem::setParent (FileBackedMap< ClientListItem > * aParent) inherited
Set the parent.
Parameters
aParent The FileBackedMap that contains this item
Definition at line 113 of file ClientListItem.cpp.
void ClientListItem::setUpdateName (CString aName) inherited
Set pending name.
Set the pending name of this ClientListItem. This does not become the item's name until commitName is called.
Parameters
aName The pending name to set
Definition at line 127 of file ClientListItem.cpp.
Referenced by FmiApplicationLayer::sendCannedMessage(), FmiApplicationLayer::sendCannedResponse(), FmiApplicationLayer::sendCreateWaypointCat(), FmiApplicationLayer::sendDriverStatusListItem(), and FmiApplicationLayer::sendWaypoint().
void ClientListItem::setValid (BOOL aValid = TRUE) inherited
Set this item as valid.
Set the valid flag. If this item is part of a FileBackedMap, save the map.
Parameters
aValid If TRUE, the item is valid.
Definition at line 141 of file ClientListItem.cpp.
Referenced by ClientListItem::commitName(), CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendA603Stop(), FmiApplicationLayer::sendDeleteWaypointCat(), and CMapViewerDlg::sendRouteToDevice().
void InboxListItem::writeToStream (std::ofstream & aStream)
Write an InboxListItem to an output stream.
Parameters
aStream The stream to write to
Definition at line 83 of file InboxListItem.cpp.
void ClientListItem::writeToStream (std::ofstream & aStream) const virtual inherited
Write a ClientListItem to an output stream.
Append id and current name to the output stream.
Parameters
aStream The stream to write to
Reimplemented in AobrdDriverItem, DriverLoginItem, and WaypointListItem.
Definition at line 155 of file ClientListItem.cpp.
Referenced by WaypointListItem::writeToStream().
Member Data Documentation
CString ClientListItem::mCurrentName protected inherited
The last name acknowledged by the client.
Definition at line 75 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), ClientListItem::commitName(), and ClientListItem::getCurrentName().
MessageId InboxListItem::messageId private
Definition at line 39 of file InboxListItem.h.
Referenced by getId().
key_type ClientListItem::mId protected inherited
The unique ID of this item.
Definition at line 84 of file ClientListItem.h.
Referenced by ClientListItem::getId().
BOOL ClientListItem::mIsValid protected inherited
True if this list item is mIsValid.
Definition at line 81 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::isValid().
FileBackedMap<InboxListItem>* InboxListItem::mParent private
Definition at line 38 of file InboxListItem.h.
CString ClientListItem::mUpdateName protected inherited
The last name entered by the user.
Definition at line 78 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::commitName().
The documentation for this class was generated from the following files:
InboxListItem.h
InboxListItem.cpp