Garmin Fleet Management Controller: AobrdEventLogConverter Class Reference
AobrdEventLogConverter Class Reference
Utility for converting between raw AOBRD data to human- readable CSV file. Used to attempt to auto-convert files received from device and CSV files selected for upload as AOBRD content to device.
#include <AobrdEventLogConverter.h>
Public Types
enum evt_log_reason {
DRIVER_ANNOTATION,
DRIVER_STATUS_CHANGE,
DRIVER_VERIFIED_LOG,
DRIVER_COULD_NOT_VERIFY_LOG,
DRIVER_ADDED_NEW_SHIPMENT_ENTRY,
DRIVER_MODIFIED_EXISTING_SHIPMENT_ENTRY,
PND_FAILURE_DETECTION,
DRIVER_DELETED_SHIPMENT_ENTRY,
EVT_LOG_REASON_COUNT
}
Public Member Functions
AobrdEventLogConverter ()
Constructor.
bool convertAnnotation (std::vector< std::string > &record, fmi_driver_annotation_data_type *annotation)
Convert an Annotation record to structure sent to FMI device.
void convertToCsv (const char *source, const char *destFormat)
Convert raw file to CSV.
uint32 convertToRaw (const char *source, const char *dest)
Convert CSV file to raw.
uint16 countRecords (const char *source, evt_log_reason type)
Count records by type.
bool findRecordAt (const char *source, evt_log_reason type, uint16 index, bool(*visitor)(AobrdEventLogConverter *converter, std::vector< std::string > &record, void *data), void *data)
Visit records by type and index.
Detailed Description
Utility for converting between raw AOBRD data to human- readable CSV file. Used to attempt to auto-convert files received from device and CSV files selected for upload as AOBRD content to device.
Since
Protocol A610
Definition at line 26 of file AobrdEventLogConverter.h.
Member Enumeration Documentation
enum AobrdEventLogConverter::evt_log_reason
Enumerator:
DRIVER_ANNOTATION
DRIVER_STATUS_CHANGE
DRIVER_VERIFIED_LOG
DRIVER_COULD_NOT_VERIFY_LOG
DRIVER_ADDED_NEW_SHIPMENT_ENTRY
DRIVER_MODIFIED_EXISTING_SHIPMENT_ENTRY
PND_FAILURE_DETECTION
DRIVER_DELETED_SHIPMENT_ENTRY
EVT_LOG_REASON_COUNT
Definition at line 30 of file AobrdEventLogConverter.h.
Constructor & Destructor Documentation
AobrdEventLogConverter::AobrdEventLogConverter ()
Constructor.
Definition at line 55 of file AobrdEventLogConverter.cpp.
Member Function Documentation
bool AobrdEventLogConverter::convertAnnotation (std::vector< std::string > & record, fmi_driver_annotation_data_type * annotation)
Convert an Annotation record to structure sent to FMI device.
Definition at line 1052 of file AobrdEventLogConverter.cpp.
References cnt_of_array, parseDateTime(), fmi_driver_annotation_data_type::server_annotation, fmi_driver_annotation_data_type::server_end_time, fmi_driver_annotation_data_type::server_start_time, and fmi_driver_annotation_data_type::server_timestamp.
Referenced by convertAnnotationRecord().
void AobrdEventLogConverter::convertToCsv (const char * source, const char * destFormat)
Convert raw file to CSV.
Definition at line 360 of file AobrdEventLogConverter.cpp.
References convertTimeTypeToString(), encodeDegreeFields(), encodeStringFields(), encodeTimestampField(), encodeTimestampFields(), encodeUint16Fields(), encodeUint32Fields(), evt_log_header_fixed::field_flags, CsvWriter::Finish(), locateEventBeingVerified(), modifyStatusChangeRecord(), CsvWriter::NewLine(), evt_log_header_fixed::reason, updateEventBeingVerified(), evt_log_header_fixed::version, and CsvWriter::WriteValue().
Referenced by CFmiPcAppDlg::OnEventAobrdFileTransferReceived().
uint32 AobrdEventLogConverter::convertToRaw (const char * source, const char * dest)
Convert CSV file to raw.
Definition at line 769 of file AobrdEventLogConverter.cpp.
References checkFieldHeaders(), decodeDegreeFields(), decodeStringFields(), decodeTimestampFields(), decodeUint16Fields(), decodeUint32Fields(), evt_log_header_fixed::field_flags, readCSVRecord(), evt_log_header_fixed::reason, and evt_log_header_fixed::version.
Referenced by FmiApplicationLayer::rx().
uint16 AobrdEventLogConverter::countRecords (const char * source, evt_log_reason type)
Count records by type.
Definition at line 956 of file AobrdEventLogConverter.cpp.
References readCSVRecord().
Referenced by FmiApplicationLayer::rx().
bool AobrdEventLogConverter::findRecordAt (const char * source, evt_log_reason type, uint16 index, bool(*)(AobrdEventLogConverter *converter, std::vector< std::string > &record, void *data) visitor, void * data)
Visit records by type and index.
Definition at line 991 of file AobrdEventLogConverter.cpp.
References readCSVRecord().
Referenced by FmiApplicationLayer::sendNextAOBRDAnnotation().
The documentation for this class was generated from the following files:
AobrdEventLogConverter.h
AobrdEventLogConverter.cpp