Garmin Fleet Management Controller: AobrdShipment Class Reference
AobrdShipment Class Reference
Data structure to holds an AOBRD shipment info. Used by the FmiApplicationLayer to provision shipments.
#include <AobrdShipment.h>
Public Member Functions
AobrdShipment ()
Constructor.
virtual ~AobrdShipment ()
Destructor.
CString getCommodity () const
Get item's commodity.
CString getDocNumber () const
Get item's document number.
time_type getServerEndTime () const
Get item's server end time.
time_type getServerStartTime () const
Get item's server start time.
time_type getServerTimestamp () const
Get item's server timestamp.
CString getShipperName () const
Get item's shipper name.
void readFromStream (std::istream &aStream)
Read a AobrdShipment from an input stream.
void setCommodity (const std::string &aCommodity)
Set the Commodity for this item.
void setDocNumber (const std::string &aDocNumber)
Set the Document Number for this item.
void setServerEndTime (const time_type &aTimestamp)
Set the Server End Time for this item.
void setServerStartTime (const time_type &aTimestamp)
Set the Server Start Time for this item.
void setServerTimestamp (const time_type &aTimestamp)
Set the Server Timestamp for this item.
void setShipperName (const std::string &aShipperName)
Set the Shipper Name for this item.
void writeToStream (std::ofstream &aStream) const
Write a AobrdShipment to an output stream.
Private Attributes
std::string mCommodity
The commodity, UTF8 encoded.
std::string mDocNumber
The document number, UTF8 encoded.
time_type mServerEndTime
The server end time.
time_type mServerStartTime
The server start time.
time_type mServerTimestamp
The server timestamp.
std::string mShipperName
The shipper name, UTF8 encoded.
Detailed Description
Data structure to holds an AOBRD shipment info. Used by the FmiApplicationLayer to provision shipments.
Since
Protocol A610
Definition at line 23 of file AobrdShipment.h.
Constructor & Destructor Documentation
AobrdShipment::AobrdShipment ()
Constructor.
Definition at line 18 of file AobrdShipment.cpp.
AobrdShipment::~AobrdShipment () virtual
Destructor.
Definition at line 29 of file AobrdShipment.cpp.
Member Function Documentation
CString AobrdShipment::getCommodity () const
Get item's commodity.
Get the commodity of this item
Returns
The item's commodity
Definition at line 98 of file AobrdShipment.cpp.
References mCommodity.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList(), FmiApplicationLayer::sendNextAOBRDShipment(), and CAobrdDriverShipmentsDlg::updateListBox().
CString AobrdShipment::getDocNumber () const
Get item's document number.
Get the document number of this item
Returns
The item's document number
Definition at line 83 of file AobrdShipment.cpp.
References mDocNumber.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList(), FmiApplicationLayer::sendNextAOBRDShipment(), and CAobrdDriverShipmentsDlg::updateListBox().
time_type AobrdShipment::getServerEndTime () const
Get item's server end time.
Get the server end time of this item
Returns
The item's server end time
Definition at line 58 of file AobrdShipment.cpp.
References mServerEndTime.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList(), and FmiApplicationLayer::sendNextAOBRDShipment().
time_type AobrdShipment::getServerStartTime () const
Get item's server start time.
Get the server start time of this item
Returns
The item's server start time
Definition at line 48 of file AobrdShipment.cpp.
References mServerStartTime.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList(), and FmiApplicationLayer::sendNextAOBRDShipment().
time_type AobrdShipment::getServerTimestamp () const
Get item's server timestamp.
Get the server timestamp of this item
Returns
The item's server timestamp
Definition at line 38 of file AobrdShipment.cpp.
References mServerTimestamp.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList(), and FmiApplicationLayer::sendNextAOBRDShipment().
CString AobrdShipment::getShipperName () const
Get item's shipper name.
Get the shipper name of this item
Returns
The item's shipper name
Definition at line 68 of file AobrdShipment.cpp.
References mShipperName.
Referenced by CAobrdDriverShipmentsDlg::OnLbnSelchangeShipmentList(), FmiApplicationLayer::sendNextAOBRDShipment(), and CAobrdDriverShipmentsDlg::updateListBox().
void AobrdShipment::readFromStream (std::istream & aStream)
Read a AobrdShipment from an input stream.
Read values from the input stream, and updates the member variables appropriately.
Parameters
aStream The stream to read from
Definition at line 115 of file AobrdShipment.cpp.
Referenced by AobrdDriverItem::readFromStream().
void AobrdShipment::setCommodity (const std::string & aCommodity)
Set the Commodity for this item.
Sets the Commodity for this item
Parameters
aCommodity The commodity
Definition at line 189 of file AobrdShipment.cpp.
References mCommodity.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().
void AobrdShipment::setDocNumber (const std::string & aDocNumber)
Set the Document Number for this item.
Sets the Document Number for this item
Parameters
aDocNumber The document number
Definition at line 179 of file AobrdShipment.cpp.
References mDocNumber.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().
void AobrdShipment::setServerEndTime (const time_type & aTimestamp)
Set the Server End Time for this item.
Sets the Server End Time for this item
Parameters
aTimestamp The server end time
Definition at line 219 of file AobrdShipment.cpp.
References mServerEndTime.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().
void AobrdShipment::setServerStartTime (const time_type & aTimestamp)
Set the Server Start Time for this item.
Sets the Server Start Time for this item
Parameters
aTimestamp The server start time
Definition at line 209 of file AobrdShipment.cpp.
References mServerStartTime.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().
void AobrdShipment::setServerTimestamp (const time_type & aTimestamp)
Set the Server Timestamp for this item.
Sets the Server Timestamp for this item
Parameters
aTimestamp The server timestamp
Definition at line 199 of file AobrdShipment.cpp.
References mServerTimestamp.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().
void AobrdShipment::setShipperName (const std::string & aShipperName)
Set the Shipper Name for this item.
Sets the Shipper Name for this item
Parameters
aShipperName The shipper's name
Definition at line 169 of file AobrdShipment.cpp.
References mShipperName.
Referenced by CAobrdDriverShipmentsDlg::OnBnClickedSet().
void AobrdShipment::writeToStream (std::ofstream & aStream) const
Write a AobrdShipment to an output stream.
Append values to the output stream.
Parameters
aStream The stream to write to
Definition at line 230 of file AobrdShipment.cpp.
Referenced by AobrdDriverItem::writeToStream().
Member Data Documentation
std::string AobrdShipment::mCommodity private
The commodity, UTF8 encoded.
Definition at line 55 of file AobrdShipment.h.
Referenced by getCommodity(), and setCommodity().
std::string AobrdShipment::mDocNumber private
The document number, UTF8 encoded.
Definition at line 52 of file AobrdShipment.h.
Referenced by getDocNumber(), and setDocNumber().
time_type AobrdShipment::mServerEndTime private
The server end time.
Definition at line 64 of file AobrdShipment.h.
Referenced by getServerEndTime(), and setServerEndTime().
time_type AobrdShipment::mServerStartTime private
The server start time.
Definition at line 61 of file AobrdShipment.h.
Referenced by getServerStartTime(), and setServerStartTime().
time_type AobrdShipment::mServerTimestamp private
The server timestamp.
Definition at line 58 of file AobrdShipment.h.
Referenced by getServerTimestamp(), and setServerTimestamp().
std::string AobrdShipment::mShipperName private
The shipper name, UTF8 encoded.
Definition at line 49 of file AobrdShipment.h.
Referenced by getShipperName(), and setShipperName().
The documentation for this class was generated from the following files:
AobrdShipment.h
AobrdShipment.cpp