Garmin Fleet Management Controller: AobrdDriverItem Class Reference
AobrdDriverItem Class Reference
Data structure to holds an AOBRD driver info. Used by the FmiApplicationLayer to validate logins when driver password support is enabled.
#include <AobrdDriverItem.h>
Public Types
typedef std::string key_type
Public Member Functions
AobrdDriverItem ()
Constructor.
virtual ~AobrdDriverItem ()
Destructor.
void addShipment (AobrdShipment &shipment)
Add a shipment.
void commitName ()
Commit the item name.
void deleteShipment (int index)
Delete a shipment.
CString getCarrierID () const
Get item's carrier ID.
CString getCarrierName () const
Get item's carrier name.
CString getCurrentName () const
Get the current name of this item.
CString getDriverId () const
Get the driver ID as a CString.
CString getFirstName () const
Get item's first name.
const key_type & getId () const
Get item's ID.
CString getLastName () const
Get item's last name.
uint16 getLongTermRuleset () const
Get item's long term ruleset.
CString getPassword () const
Get item's password.
const std::vector
< AobrdShipment > & getShipments () const
Get the list of shipments.
uint16 getTimeZone () const
Get item's time zone.
BOOL isValid () const
Check whether this item is valid.
void readFromStream (std::istream &aStream)
Read a AobrdDriverItem from an input stream.
void replaceShipment (AobrdShipment &shipment, int index)
Update a shipment.
void save ()
Save this item.
void setCarrierID (const std::string &aCarrierID)
Set the carrier ID of this driver.
void setCarrierName (const std::string &aCarrierName)
Set the carrier name of this driver.
void setFirstName (const std::string &aFirstName)
Set the first name of this driver.
void setId (const key_type &aId)
Set item's ID.
void setId (const key_type &aId)
Set the ID (key) of this item.
void setLastName (const std::string &aLastName)
Set the last name of this driver.
void setLongTermRuleset (const uint16 aRuleset)
Set the long term ruleset of this driver.
void setParent (FileBackedMap< ClientListItem > *aParent)
Set the parent.
void setParent (FileBackedMap< AobrdDriverItem > *aParent)
Set the parent map of this item.
void setPassword (const std::string &aPassword)
Set the password of this driver.
void setTimeZone (const uint16 aTimeZone)
Set the time zone of this driver.
void setUpdateName (CString aName)
Set pending name.
void setValid (BOOL aValid=TRUE)
Set this item as valid.
void writeToStream (std::ofstream &aStream) const
Write a AobrdDriverItem to an output stream.
Protected Attributes
CString mCurrentName
The last name acknowledged by the client.
key_type mId
The unique ID of this item.
BOOL mIsValid
True if this list item is mIsValid.
CString mUpdateName
The last name entered by the user.
Private Attributes
std::string mCarrierID
The driver first name, UTF8 encoded.
std::string mCarrierName
The driver carrier name, UTF8 encoded.
std::string mDriverId
The driver ID, UTF8 encoded.
std::string mDriverPassword
The driver password, UTF8 encoded.
std::string mFirstName
The driver first name, UTF8 encoded.
std::string mLastName
The driver last name, UTF8 encoded.
uint16 mLongTermRuleset
The driver long term ruleset.
FileBackedMap< AobrdDriverItem > * mParent
The map that this DriverItem is a part of.
std::vector< AobrdShipment > mShipments
The shipments.
uint16 mTimeZone
The driver time zone.
Detailed Description
Data structure to holds an AOBRD driver info. Used by the FmiApplicationLayer to validate logins when driver password support is enabled.
Since
Protocol A610
Definition at line 24 of file AobrdDriverItem.h.
Member Typedef Documentation
typedef std::string AobrdDriverItem::key_type
Definition at line 28 of file AobrdDriverItem.h.
Constructor & Destructor Documentation
AobrdDriverItem::AobrdDriverItem ()
Constructor.
Definition at line 20 of file AobrdDriverItem.cpp.
AobrdDriverItem::~AobrdDriverItem () virtual
Destructor.
Definition at line 34 of file AobrdDriverItem.cpp.
Member Function Documentation
void AobrdDriverItem::addShipment (AobrdShipment & shipment)
Add a shipment.
Adds a shipment to the list of shipments
Parameters
shipment The shipment to add
Definition at line 173 of file AobrdDriverItem.cpp.
References mShipments.
void ClientListItem::commitName () inherited
Commit the item name.
Commit the item name and set the ClientListItem as valid
Definition at line 29 of file ClientListItem.cpp.
References ClientListItem::mCurrentName, ClientListItem::mUpdateName, and ClientListItem::setValid().
Referenced by FmiApplicationLayer::rx().
void AobrdDriverItem::deleteShipment (int index)
Delete a shipment.
Removes a shipment from the list of shipments
Parameters
index The index of the shipment to remove
Definition at line 195 of file AobrdDriverItem.cpp.
References mShipments.
Referenced by replaceShipment().
CString AobrdDriverItem::getCarrierID () const
Get item's carrier ID.
Get the carrier ID of this item
Returns
The item's carrier ID
Definition at line 128 of file AobrdDriverItem.cpp.
References mCarrierID.
Referenced by CAobrdDriversDlg::OnLbnSelchangeDriverList(), FmiApplicationLayer::rx(), and FmiApplicationLayer::sendAOBRDDriverProfile().
CString AobrdDriverItem::getCarrierName () const
Get item's carrier name.
Get the carrier name of this item
Returns
The item's carrier name
Definition at line 113 of file AobrdDriverItem.cpp.
References mCarrierName.
Referenced by CAobrdDriversDlg::OnLbnSelchangeDriverList(), FmiApplicationLayer::rx(), and FmiApplicationLayer::sendAOBRDDriverProfile().
CString ClientListItem::getCurrentName () const inherited
Get the current name of this item.
Returns
The current (committed) name
Definition at line 39 of file ClientListItem.cpp.
References ClientListItem::mCurrentName.
Referenced by CDriverIdAndStatusDlg::OnLbnSelchangeStatuslist(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
CString AobrdDriverItem::getDriverId () const
Get the driver ID as a CString.
Returns
the driver ID, as a CString
Definition at line 43 of file AobrdDriverItem.cpp.
References mDriverId.
Referenced by CAobrdDriversDlg::OnLbnSelchangeDriverList(), and FmiApplicationLayer::sendAOBRDDriverProfile().
CString AobrdDriverItem::getFirstName () const
Get item's first name.
Get the first name of this item
Returns
The item's first name
Definition at line 83 of file AobrdDriverItem.cpp.
References mFirstName.
Referenced by CAobrdDriversDlg::OnBnClickedSet(), CAobrdDriversDlg::OnLbnSelchangeDriverList(), FmiApplicationLayer::rx(), and FmiApplicationLayer::sendAOBRDDriverProfile().
const AobrdDriverItem::key_type & AobrdDriverItem::getId () const
Get item's ID.
Get the unique ID (driver ID) of this item
Returns
The item's ID
Reimplemented from ClientListItem.
Definition at line 58 of file AobrdDriverItem.cpp.
References mDriverId.
CString AobrdDriverItem::getLastName () const
Get item's last name.
Get the last name of this item
Returns
The item's last name
Definition at line 98 of file AobrdDriverItem.cpp.
References mLastName.
Referenced by CAobrdDriversDlg::OnBnClickedSet(), CAobrdDriversDlg::OnLbnSelchangeDriverList(), FmiApplicationLayer::rx(), and FmiApplicationLayer::sendAOBRDDriverProfile().
uint16 AobrdDriverItem::getLongTermRuleset () const
Get item's long term ruleset.
Get the long term ruleset of this item
Returns
The item's long term ruleset
Definition at line 143 of file AobrdDriverItem.cpp.
References mLongTermRuleset.
Referenced by CAobrdDriversDlg::OnLbnSelchangeDriverList(), FmiApplicationLayer::rx(), and FmiApplicationLayer::sendAOBRDDriverProfile().
CString AobrdDriverItem::getPassword () const
Get item's password.
Get the password of this item
Returns
The item's password
Definition at line 68 of file AobrdDriverItem.cpp.
References mDriverPassword.
Referenced by CAobrdDriversDlg::OnLbnSelchangeDriverList(), and FmiApplicationLayer::rx().
const std::vector< AobrdShipment > & AobrdDriverItem::getShipments () const
Get the list of shipments.
Get the shipments for this item
Returns
The item's shipments
Definition at line 163 of file AobrdDriverItem.cpp.
References mShipments.
Referenced by FmiApplicationLayer::rx(), and FmiApplicationLayer::sendNextAOBRDShipment().
uint16 AobrdDriverItem::getTimeZone () const
Get item's time zone.
Get the time zone of this item
Returns
The item's time zone
Definition at line 153 of file AobrdDriverItem.cpp.
References mTimeZone.
Referenced by CAobrdDriversDlg::OnLbnSelchangeDriverList(), FmiApplicationLayer::rx(), and FmiApplicationLayer::sendAOBRDDriverProfile().
BOOL ClientListItem::isValid () const inherited
Check whether this item is valid.
Returns
TRUE if the item is valid, FALSE otherwise
Definition at line 58 of file ClientListItem.cpp.
References ClientListItem::mIsValid.
Referenced by CAobrdDriversDlg::OnBnClickedSet(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
void AobrdDriverItem::readFromStream (std::istream & aStream) virtual
Read a AobrdDriverItem from an input stream.
Read id and password from the input stream, and updates the member variables appropriately.
Parameters
aStream The stream to read from
Reimplemented from ClientListItem.
Definition at line 207 of file AobrdDriverItem.cpp.
References AobrdShipment::readFromStream(), RECORD_SEPARATOR, and TRUE.
void AobrdDriverItem::replaceShipment (AobrdShipment & shipment, int index)
Update a shipment.
Replaces a shipment at existing location with a new one
Parameters
shipment The new shipment
index The index of the existing shipment to replace
Definition at line 184 of file AobrdDriverItem.cpp.
References deleteShipment(), and mShipments.
void AobrdDriverItem::save () virtual
Save this item.
Invokes parent to save all items
Reimplemented from ClientListItem.
Definition at line 325 of file AobrdDriverItem.cpp.
References mParent, and FileBackedMap< T >::save().
void AobrdDriverItem::setCarrierID (const std::string & aCarrierID)
Set the carrier ID of this driver.
Sets the carrier ID for this driver
Parameters
aCarrierID The driver's carrier ID
Definition at line 425 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void AobrdDriverItem::setCarrierName (const std::string & aCarrierName)
Set the carrier name of this driver.
Sets the carrier name for this driver
Parameters
aCarrierName The driver's carrier name
Definition at line 410 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void AobrdDriverItem::setFirstName (const std::string & aFirstName)
Set the first name of this driver.
Sets the first name for this driver
Parameters
aFirstName The driver's first name
Definition at line 380 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void ClientListItem::setId (const key_type & aId) inherited
Set item's ID.
Parameters
aId The item's ID
Reimplemented in DriverLoginItem.
Definition at line 101 of file ClientListItem.cpp.
Referenced by CStopNewDlg::OnBnClickedOk(), and FmiApplicationLayer::sendCannedMessage().
void AobrdDriverItem::setId (const key_type & aId)
Set the ID (key) of this item.
Sets the key associated with this item
Parameters
aId The item's ID
Definition at line 339 of file AobrdDriverItem.cpp.
void AobrdDriverItem::setLastName (const std::string & aLastName)
Set the last name of this driver.
Sets the last name for this driver
Parameters
aLastName The driver's last name
Definition at line 395 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void AobrdDriverItem::setLongTermRuleset (const uint16 aRuleset)
Set the long term ruleset of this driver.
Sets the long term ruleset for this driver
Parameters
aRuleset The driver's long term ruleset
Definition at line 440 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void ClientListItem::setParent (FileBackedMap< ClientListItem > * aParent) inherited
Set the parent.
Parameters
aParent The FileBackedMap that contains this item
Definition at line 113 of file ClientListItem.cpp.
void AobrdDriverItem::setParent (FileBackedMap< AobrdDriverItem > * aParent)
Set the parent map of this item.
Sets the map that this item is in
Parameters
aParent The item's parent
Definition at line 352 of file AobrdDriverItem.cpp.
void AobrdDriverItem::setPassword (const std::string & aPassword)
Set the password of this driver.
Sets the password for this driver
Parameters
aPassword The driver's password
Definition at line 365 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void AobrdDriverItem::setTimeZone (const uint16 aTimeZone)
Set the time zone of this driver.
Sets the time zone for this driver
Parameters
aTimeZone The driver's time zone
Definition at line 482 of file AobrdDriverItem.cpp.
Referenced by CAobrdDriversDlg::OnBnClickedSet().
void ClientListItem::setUpdateName (CString aName) inherited
Set pending name.
Set the pending name of this ClientListItem. This does not become the item's name until commitName is called.
Parameters
aName The pending name to set
Definition at line 127 of file ClientListItem.cpp.
Referenced by FmiApplicationLayer::sendCannedMessage(), FmiApplicationLayer::sendCannedResponse(), FmiApplicationLayer::sendCreateWaypointCat(), FmiApplicationLayer::sendDriverStatusListItem(), and FmiApplicationLayer::sendWaypoint().
void ClientListItem::setValid (BOOL aValid = TRUE) inherited
Set this item as valid.
Set the valid flag. If this item is part of a FileBackedMap, save the map.
Parameters
aValid If TRUE, the item is valid.
Definition at line 141 of file ClientListItem.cpp.
Referenced by ClientListItem::commitName(), CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendA603Stop(), FmiApplicationLayer::sendDeleteWaypointCat(), and CMapViewerDlg::sendRouteToDevice().
void AobrdDriverItem::writeToStream (std::ofstream & aStream) const virtual
Write a AobrdDriverItem to an output stream.
Append driver ID and password to the output stream.
Parameters
aStream The stream to write to
Reimplemented from ClientListItem.
Definition at line 497 of file AobrdDriverItem.cpp.
References CURRENT_VERSION, RECORD_SEPARATOR, and AobrdShipment::writeToStream().
Member Data Documentation
std::string AobrdDriverItem::mCarrierID private
The driver first name, UTF8 encoded.
Definition at line 87 of file AobrdDriverItem.h.
Referenced by getCarrierID().
std::string AobrdDriverItem::mCarrierName private
The driver carrier name, UTF8 encoded.
Definition at line 84 of file AobrdDriverItem.h.
Referenced by getCarrierName().
CString ClientListItem::mCurrentName protected inherited
The last name acknowledged by the client.
Definition at line 75 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), ClientListItem::commitName(), and ClientListItem::getCurrentName().
std::string AobrdDriverItem::mDriverId private
The driver ID, UTF8 encoded.
Definition at line 72 of file AobrdDriverItem.h.
Referenced by getDriverId(), and getId().
std::string AobrdDriverItem::mDriverPassword private
The driver password, UTF8 encoded.
Definition at line 75 of file AobrdDriverItem.h.
Referenced by getPassword().
std::string AobrdDriverItem::mFirstName private
The driver first name, UTF8 encoded.
Definition at line 78 of file AobrdDriverItem.h.
Referenced by getFirstName().
key_type ClientListItem::mId protected inherited
The unique ID of this item.
Definition at line 84 of file ClientListItem.h.
Referenced by ClientListItem::getId().
BOOL ClientListItem::mIsValid protected inherited
True if this list item is mIsValid.
Definition at line 81 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::isValid().
std::string AobrdDriverItem::mLastName private
The driver last name, UTF8 encoded.
Definition at line 81 of file AobrdDriverItem.h.
Referenced by getLastName().
uint16 AobrdDriverItem::mLongTermRuleset private
The driver long term ruleset.
Definition at line 90 of file AobrdDriverItem.h.
Referenced by getLongTermRuleset().
FileBackedMap<AobrdDriverItem>* AobrdDriverItem::mParent private
The map that this DriverItem is a part of.
Definition at line 104 of file AobrdDriverItem.h.
Referenced by save().
std::vector<AobrdShipment> AobrdDriverItem::mShipments private
The shipments.
Definition at line 101 of file AobrdDriverItem.h.
Referenced by addShipment(), deleteShipment(), getShipments(), and replaceShipment().
uint16 AobrdDriverItem::mTimeZone private
The driver time zone.
Definition at line 98 of file AobrdDriverItem.h.
Referenced by getTimeZone().
CString ClientListItem::mUpdateName protected inherited
The last name entered by the user.
Definition at line 78 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::commitName().
The documentation for this class was generated from the following files:
AobrdDriverItem.h
AobrdDriverItem.cpp