Garmin Fleet Management Controller: FmiApplicationLayer Class Reference
FmiApplicationLayer Class Reference
Serial communication controller for Garmin and FMI packets.
#include <FmiApplicationLayer.h>
Public Types
enum transfer_state {
TRANSFER_NOT_STARTED,
TRANSFER_STARTED,
TRANSFER_IN_PROGRESS,
TRANSFER_COMPLETED,
TRANSFER_FAILED
}
Enum to track file transfer status.
Public Member Functions
FmiApplicationLayer (id_type freeformFmiPacketId)
Constructor.
virtual ~FmiApplicationLayer ()
Destructor.
void clearError ()
Clear any communication error.
virtual void disconnectTransportLayer ()
Disconnect the TransportLayer from this ApplicationLayer.
uint32 getNextStopId ()
Find an available stop ID.
const char * getReceiveFilename (uint8 file_type) const
Determine which filename to store a received file under.
virtual void onAck (const Packet *aPacket)
Callback when a packet is ACKed by the client.
void rebootDevice ()
Send a command to the attached device to reboot it.
void removeStopByIndex (uint16 aDeletedStopIndex)
Remove a deleted stop.
virtual bool rx (const Packet *aPacket)
Handle a packet received from the client.
void sendA602Stop (double aLatitude, double aLongitude, char *aStopName)
Initiates the A602 stop protocol.
void sendA602TextMessage (fmi_id_type aFmiPacketId, char *aMessageText, const MessageId &aMessageId)
Send a server to client text message, for all A602 FMI protocols.
void sendA603Stop (double aLatitude, double aLongitude, char *aStopName, uint32 aStopId)
Initiates the A603 stop protocol.
void sendA604TextMessage (const char *aMessageText, const MessageId &aMessageId, uint8 aMessageType=A604_MESSAGE_TYPE_NORMAL)
Send an A604 server to client open text message.
void sendA607DriverIdRequest (uint8 aDriverIndex)
Ask the client for the current Driver ID.
void sendA607DriverIdUpdate (char *aDriverId, uint8 aIndex)
Send an A607 Driver ID Update to the client.
void sendA607DriverStatusRequest (uint8 aDriverIndex)
Ask the client for the current Driver Status.
void sendA607DriverStatusUpdate (uint32 aDriverStatusId, uint8 aIndex)
Initiate the A607 Driver Status Update protocol.
bool sendA611LongTextMessage (const char *aMessageText, const MessageId &aMessageId, uint8 aMessageType)
Send an A611 server to client long text message.
void sendAOBRDDriverProfile (const AobrdDriverItem &driver)
Send an AOBRD driver profile to the device.
void sendAOBRDOdometerValue (uint32 aOdometer)
Send AOBRD Odometer value to device.
void sendAutoArrival (uint32 aArrivalTime, uint32 aArrivalDistance)
Send a request to update the auto-arrival preferences.
void sendCannedMessage (uint32 aMessageId, CString aMessageText)
Transmit a new or updated canned message to the client.
void sendCannedResponse (uint32 aResponseId, CString aResponseText)
Transmit a new or updated canned response to the client.
bool sendCannedResponseTextMessage (const char *aMessageText, const MessageId &aMessageId, uint8 aResponseCount, const uint32 *aResponseList, uint8 aMessageType)
Initiate the canned response text message protocol.
void sendCreateWaypointCat (uint8 aCatId, CString &aCatName)
Create waypoint category.
void sendDataDeletionRequest (del_data aDataType)
Send a data deletion request and remove the appropriate data from the server.
void sendDeleteCannedMessageRequest (uint32 aMessageId)
Send a request to the client to delete a canned message.
void sendDeleteCannedResponseRequest (uint32 aResponseId)
Send a request to the client to delete a canned response.
void sendDeleteDriverStatusListItem (uint32 aDriverStatusId)
Initiate the Delete Driver Status List Item protocol.
void sendDeleteWaypoint (uint16 aUniqueId)
Delete a waypoint.
void sendDeleteWaypointCat (uint16 aCatIdx)
Delete waypoint category.
void sendDriverIdRequest ()
Ask the client for the current Driver ID.
void sendDriverIdUpdate (char *aDriverId)
Send a Driver ID Update to the client.
void sendDriverStatusListItem (uint32 aDriverStatusId, CString aDriverStatusText)
Initiate the Set Driver Status List Item protocol.
void sendDriverStatusRequest ()
Asks the client for the current driver status.
void sendDriverStatusUpdate (uint32 aDriverStatusId)
Initiate the Driver Status Update protocol.
void sendEnable (uint16 *aFeatureCodes=NULL, uint8 aFeatureCount=0)
Transmit an FMI Enable packet, and clear any error state.
void sendEnablePvtCommand (bool aEnable)
Send an Enable PVT or Disable PVT command.
void sendEtaRequest ()
Send a request for ETA data.
void sendFile (char *aFilename, uint8 aVersionLength, uint8 *aVersion, uint8 aFileType, BOOL gzipIt=FALSE)
Start a file transfer protocol.
void sendFmiPacket (uint16 aFmiPacketId, uint8 *aFmiPayload, uint8 aFmiPayloadSize)
Send an arbitrary FMI packet.
void sendFmiSafeModeSpeed (float speed)
Set FMI safe mode speed.
void sendFreeformFmiPacket (fmi_id_type const aFmiPacketId, uint8 const *const aFmiPayload, uint8 const aFmiPayloadSize)
void sendGpiFileInfoRequest ()
Send a GPI File Information Request to the client.
void sendMessageDeleteRequest (const MessageId &aMessageId)
Ask the server to delete a text message.
void sendMessageThrottlingQuery ()
Initiate the Message Throttling Query protocol.
void sendMessageThrottlingUpdate (uint16 aPacketId, uint16 aNewState)
Sends an update to the client to tell it whether to enable or disable a protocol.
void sendPing ()
Send a ping packet to the client.
void sendProductRequest ()
Send an FMI Product ID request.
void sendSetSpeedLimitAlerts (uint8 aMode, uint8 aTimeOver, uint8 aTimeUnder, boolean aAlertUser, float aThreshold)
Set FMI speed limit alerts.
void sendStopMoveRequest (uint16 aMoveToIndex, uint16 aMoveFromIndex)
Send a stop move request.
void sendStopSortRequest ()
Sends a sort stop list request to the client.
void sendStopStatusRequest (uint32 aStopId, stop_status_status_type aStopStatus, uint16 aMoveToIndex=INVALID16)
Initiate the Stop Status protocol to update an A603 stop.
void sendTextMessageStatusRequest (const MessageId &aMessageId)
Ask the server for the aStopStatus of a text message.
void sendUnitIdRequest ()
Request the Unit ID (ESN) from the client.
void sendUserInterfaceText (uint32 aElementId, char *aText)
Request that the text of a particular user interface text element be changed.
void sendWaypoint (uint16 aUniqueId, double aLat, double aLon, uint16 aSymbol, CString &aName, uint16 aCat, CString &aComment)
Send a waypoint.
void stopFileTransfer ()
Stop a file transfer protocol.
Public Attributes
FileBackedMap< StopListItem > mA603Stops
Map of unique ID to stop details for all A603 stops on the client.
bool mActiveRoute
If TRUE, the client has a stop active.
uint32 mActiveStopId
Unique ID of the active stop.
FileBackedMap< AobrdDriverItem > mAOBRDDrivers
Map of allowed driver IDs and passwords.
FileBackedMap< ClientListItem > mCannedMessages
Map of canned message IDs to names.
FileBackedMap< ClientListItem > mCannedResponses
Map of canned response IDs to names.
FileBackedMap< ClientListItem > mCategories
Map of waypoint category IDs to names.
codepage_type mClientCodepage
Code page used for encoding of text fields when communicating with the client.
int mClientPingCount
Number of client-to-server pings received; can be reset by the user.
uint16 mClientProductId
Numeric product ID reported by the client.
sint16 mClientSoftwareVersion
Raw software version reported by the client.
char mClientUnitId [11]
Null-terminated ASCII string containing the Unit ID (ESN) of the client.
char mDriverId [FMI_DRIVER_COUNT][50]
Last driver ID received from the client.
FileBackedMap< DriverLoginItem > mDriverLogins
Map of allowed driver IDs and passwords.
char mDriverStatus [FMI_DRIVER_COUNT][50]
Last driver status received from the client.
FileBackedMap< ClientListItem > mDriverStatuses
Map of driver status IDs to names.
bool mEnablePending
If true, the FMI Enable protocol is in progress.
char mEtaDistance [13]
Null-terminated ASCII string containing the distance to the current destination, including units.
char mEtaLatitude [14]
String representing the latitude in decimal degrees (and N or S)
char mEtaLongitude [14]
String representing the longitude in decimal degrees (and E or W)
char mEtaTime [13]
String containing the ETA time from the client, or "invalid".
uint32 mFileSize
file size (FMI_GPI_FILE_INFORMATION)
uint32 mFileTransferBytesDone
Number of bytes of the file that have been transferred so far.
uint32 mFileTransferSize
Total number of bytes in the file being transferred.
transfer_state mFileTransferState
State of the current file transfer (in progress, completed, etc.)
uint8 mFileVersion [16]
file version (FMI_GPI_FILE_INFORMATION)
uint8 mFileVersionLength
Number of significant bytes in mFileVersion.
id_type mFreeformFmiPacketId
Defaults to ID_FMI_PACKET unless overridden on command line.
char mHorizontalVelocity [15]
2-D velocity in the horizontal plane in meters per second from the last PVT packet, as an ASCII null-terminated string
CTime mLastClientPingTime
Last time when a client to server ping was received.
CTime mLastServerPingTime
Last time when a server to client ping was received.
char mProtocols [PROTOCOL_SIZE]
Null-terminated ASCII string containing the protocols supported by the client.
char mPvtAltitude [13]
Altitude in meters from the last PVT packet, as an ASCII null-terminated string.
char mPvtDate [11]
Date from the last PVT packet, as an ASCII null-terminated string of the form MM/DD/YYYY.
char mPvtEastWestVelocity [15]
East-west velocity in meters per second from the last PVT packet, as an ASCII null-terminated string.
char mPVTFixType [9]
GPS fix type from the last PVT packet, interpreted as an null-terminated ASCII string.
char mPvtLatitude [14]
Latitude in degrees from the last PVT packet, as an ASCII null-terminated string.
char mPvtLongitude [14]
Longitude in degrees from the last PVT packet, as an ASCII null-terminated string.
char mPvtNorthSouthVelocity [15]
North-south velocity in meters per second from the last PVT packet, as an ASCII null-terminated string.
char mPvtTime [13]
Time from the last PVT packet.
char mPvtUpDownVelocity [15]
Up-down velocity in meters per second from the last PVT packet, as an ASCII null-terminated string.
FileBackedMap< InboxListItem > mSentCannedResponseMessages
List of message IDs for canned response text messages.
int mServerPingCount
Number of server-to-client pings sent; can be reset by the user.
bool mStopFileTransfer
Flag to indicate that the user wants to stop the file transfer.
std::vector< uint32 > mStopIndexInList
Vector relating the stop list to unique_ids.
bool mStopListInitialized
If TRUE, the stop list has been initialized.
message_throttling_data_type mThrottledProtocols [60]
Response from the last Message Throttling Query Protocol.
bool mUseAOBRD
If true, allow AOBRD driver provisioning.
bool mUseMultipleDrivers
If true, multiple driver support is enabled.
bool mUsePasswords
If true, driver password support is enabled.
FileBackedMap< WaypointListItem > mWaypoints
Map of waypoint IDs to names.
Protected Attributes
TransportLayer * mTransportLayer
The next layer down in the stack.
Private Member Functions
void beginA611LongTextMessage (const char *aMessageText, const MessageId &aMessageId, uint8 aMessageType)
Send the first packet of an A611 server to client long text message.
void calculate2DVelocity (float32 aNorthVelocity, float32 aEastVelocity)
Calculate and format a 2D velocity given the north and east components.
void continueFileReceive (uint32 offset, uint8 length, uint8 const *data)
Save received file chunk.
void endFileReceive ()
Save received file chunk.
boolean procDriverStatusUpdate (uint32 aDriverStatusId, uint8 aDriverIndex=0)
Process a Driver Status Update from the client.
void removeStopById (uint32 aStopId)
Find the index of the deleted stop corresponding to a stop ID.
void resetCannedMessages ()
Clear the canned messages on the server.
void resetCannedResponseMessages ()
Clear the canned response text messages on the server.
void resetCannedResponses ()
Clear the canned responses on the server.
void resetDriverStatusList ()
Clear the driver statuses on the server.
void resetSavedStops ()
Clear the stop list on the server.
void resetWaypoints ()
Clear the waypoint and waypoint category lists on the server.
void sendNextAOBRDAnnotation (char *driver_id)
Send next AOBRD annotation to device.
void sendNextAOBRDShipment (char *driver_id)
Send next AOBRD shipment to device.
void startFileReceive (const file_info_data_type &file_size)
Save received file chunk.
void txCommand (command_type const aCommandId)
Transmit Garmin command packet (packet ID = ID_COMMAND_BYTE)
void txFmi (fmi_id_type const aFmiPacketId, uint8 const *const aFmiPayload, uint8 const aFmiPayloadSize, bool const aSendNow=false)
Transmit FMI packet (packet ID = ID_FMI_BYTE)
Private Attributes
CString mAOBRDAnnotationDriverId
Driver ID for annotations being sent to device.
int mAOBRDCurrentAnnotationTxIndex
Iterator for annotations being sent to device.
int mAOBRDCurrentShipmentTxIndex
Iterator for shipments being sent to device.
CString mAOBRDShipmentDriverId
Driver ID for shipments being sent to device.
int mAOBRDStopAnnotationTxIndex
Iterator end for annotations being sent to device.
int mAOBRDStopShipmentTxIndex
Iterator end for shipments being sent to device.
char mCannedResponseMessageBody [TEXT_MSG_BUFFER_MAX_SIZE]
The message text for the server to client canned text message.
uint8 mCannedResponseMessageType
The message_type for the server to client canned text message.
file_info_data_type mCurrentReceiptFile
Current file being received.
uint8 mCurrentSendFileType
Current file type for file being sent.
char mFilePath [200]
Path to the file that is being transferred to the client.
file_packet_data_type mLastFilePacketSent
The last file packet that was sent.
long_text_msg_data_type mLongTextMessage [10]
Contains the data for the most recent long text message.
bool mLongTextMessageInProgress
Indicates whether a long text message is in progress.
uint8 mLongTextMessagePayloadSize [10]
Indicates the lengths of the long text message packets.
bool mRefreshingCannedMessages
If TRUE, FmiApplicationLayer is handling a request to refresh the canned message list.
bool mRefreshingCannedResponses
If TRUE, FmiApplicationLayer is handling a request to refresh the canned response list.
bool mRefreshingDriverStatusList
If TRUE, FmiApplicationLayer is handling a request to refresh the driver status list.
char mSentDriverId [50]
The last driver ID that was sent to the client.
uint32 mSentDriverStatus
The last driver status that was sent to the client.
Detailed Description
Serial communication controller for Garmin and FMI packets.
The FmiApplicationLayer class performs the application- level communication with the client device.
Note
This implementation makes the assumption that the client correctly follows the protocols. If the client follows the link-layer protocol but does not send the application-level response, the protocol will not continue. For example, during a file transfer, a file data packet is not sent until the receipt is received for the previous packet; if the previous packet is ACKed but a receipt is not received, the file transfer will stall. A robust implementation should include appropriate timeouts at the application layer to account for this possibility.
Definition at line 65 of file FmiApplicationLayer.h.
Member Enumeration Documentation
enum FmiApplicationLayer::transfer_state
Enum to track file transfer status.
Since
Protocol A604
Enumerator:
TRANSFER_NOT_STARTED
TRANSFER_STARTED
TRANSFER_IN_PROGRESS
TRANSFER_COMPLETED
TRANSFER_FAILED
Definition at line 75 of file FmiApplicationLayer.h.
Constructor & Destructor Documentation
FmiApplicationLayer::FmiApplicationLayer (id_type freeformFmiPacketId)
Constructor.
Definition at line 85 of file FmiApplicationLayer.cpp.
References CODEPAGE_ASCII, FALSE, INVALID32, mActiveRoute, mActiveStopId, mAOBRDCurrentShipmentTxIndex, mAOBRDStopShipmentTxIndex, mCannedResponseMessageBody, mCannedResponseMessageType, mClientCodepage, mClientPingCount, mClientProductId, mClientSoftwareVersion, mClientUnitId, mCurrentReceiptFile, mDriverId, mDriverStatus, mEnablePending, mEtaDistance, mEtaLatitude, mEtaLongitude, mEtaTime, mFilePath, mFileSize, mFileTransferBytesDone, mFileTransferSize, mFileTransferState, mFileVersion, mFileVersionLength, mFreeformFmiPacketId, mHorizontalVelocity, mLastFilePacketSent, mProtocols, mPvtAltitude, mPvtDate, mPvtEastWestVelocity, mPVTFixType, mPvtLatitude, mPvtLongitude, mPvtNorthSouthVelocity, mPvtTime, mPvtUpDownVelocity, mRefreshingCannedMessages, mRefreshingCannedResponses, mRefreshingDriverStatusList, mSentDriverId, mSentDriverStatus, mServerPingCount, mStopFileTransfer, mStopListInitialized, mUseMultipleDrivers, mUsePasswords, and TRANSFER_NOT_STARTED.
FmiApplicationLayer::~FmiApplicationLayer () virtual
Destructor.
Definition at line 183 of file FmiApplicationLayer.cpp.
Member Function Documentation
void FmiApplicationLayer::beginA611LongTextMessage (const char * aMessageText, const MessageId & aMessageId, uint8 aMessageType) private
Send the first packet of an A611 server to client long text message.
This function is called to set up and begin sending an A611 server to client long text message. Subsequent packets of the long text message will be sent only once the previous packets have been acknowledged. Do not call this function if a long text message is already in progress.
Parameters
aMessageText Message text, as a null-terminated string in the client codepage
aMessageId The message ID
Since
Protocol A611
Definition at line 2557 of file FmiApplicationLayer.cpp.
References FMI_ID_LONG_TEXT_MSG, MessageId::getId(), MessageId::getIdSize(), LONG_TEXT_MSG_CHUNK_SIZE, offset_of, and UTIL_get_current_garmin_time().
void FmiApplicationLayer::calculate2DVelocity (float32 aNorthVelocity, float32 aEasstVelocity) private
Calculate and format a 2D velocity given the north and east components.
Formats into a human-readable speed and direction in m/s, and updates the member variable mHorizontalVelocity.
Parameters
aNorthVelocity The north velocity in m/s; negative values represent south
aEasstVelocity The east velocity in m/s; negative values represent west
Definition at line 3840 of file FmiApplicationLayer.cpp.
References UTIL_calc_2d_direction(), and UTIL_calc_2d_speed().
void FmiApplicationLayer::clearError ()
Clear any communication error.
Instructs the TransportLayer to retry sending the last packet.
Definition at line 1930 of file FmiApplicationLayer.cpp.
References ApplicationLayer::mTransportLayer, and TransportLayer::retry().
Referenced by CCommErrorDlg::OnBnClickedRetry().
void FmiApplicationLayer::continueFileReceive (uint32 offset, uint8 length, uint8 const * data) private
Save received file chunk.
Parameters
offset Current offset
length Length of recieved data
data Received data
Definition at line 3595 of file FmiApplicationLayer.cpp.
References FMI_ID_FILE_PACKET_RCPT, packet_receipt_data_type::next_offset, and packet_receipt_data_type::offset.
void ApplicationLayer::disconnectTransportLayer () virtual inherited
Disconnect the TransportLayer from this ApplicationLayer.
Definition at line 40 of file ApplicationLayer.cpp.
References ApplicationLayer::mTransportLayer.
void FmiApplicationLayer::endFileReceive () private
Save received file chunk.
Parameters
crc CRC
Definition at line 3659 of file FmiApplicationLayer.cpp.
References EVENT_FMI_AOBRD_FILE_TRANSFER_RECEIVED, EVENT_FMI_FORM_SUBMIT_RECEIVED, file_info_data_type::file_type, file_receipt_from_srvr_data_type::file_type, FMI_FILE_RESULT_SUCCESS, FMI_FILE_TYPE_AOBRD, FMI_FILE_TYPE_CUSTOM_FORMS, FMI_ID_FILE_END_RCPT, mCurrentReceiptFile, Event::post(), file_receipt_from_srvr_data_type::result_code, and txFmi().
uint32 FmiApplicationLayer::getNextStopId ()
Find an available stop ID.
Returns
A stop ID that is not in the map.
Since
Protocol A603
Definition at line 2153 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::begin(), FileBackedMap< T >::contains(), FileBackedMap< T >::empty(), FileBackedMap< T >::end(), and mA603Stops.
Referenced by CStopNewDlg::OnBnClickedOk(), and CStopNewDlg::OnInitDialog().
const char * FmiApplicationLayer::getReceiveFilename (uint8 file_type) const
Determine which filename to store a received file under.
Parameters
file_type The information about the file.
Definition at line 3530 of file FmiApplicationLayer.cpp.
References FMI_FILE_TYPE_AOBRD, FMI_FILE_TYPE_CUSTOM_FORMS, SAVE_RECEIVED_AOBRD_LOG, and SAVE_RECEIVED_FORM_SUBMIT.
void FmiApplicationLayer::onAck (const Packet * aPacket) virtual
Callback when a packet is ACKed by the client.
If the packet that was sent was an FMI Enable packet, clear the flag that indicates that protocol is in progress.
Parameters
aPacket The packet that the client ACKed
Implements ApplicationLayer.
Definition at line 1778 of file FmiApplicationLayer.cpp.
References data_deletion_data_type::data_type, DISABLE_FMI, EVENT_FMI_DISABLE_COMPLETE, FMI_ID_DATA_DELETION, FMI_ID_ENABLE, FMI_SUPPORT_A604, ID_FMI_PACKET, GarminPacket::mPacketId, GarminPacket::mPayload, and Event::post().
boolean FmiApplicationLayer::procDriverStatusUpdate (uint32 aDriverStatusId, uint8 aDriverIndex = 0) private
Process a Driver Status Update from the client.
Parameters
aDriverStatusId The new driver status.
aDriverIndex The driver index; must be zero if A607 support is not enabled.
Since
Protocol A604
Definition at line 4047 of file FmiApplicationLayer.cpp.
References EVENT_FMI_DRIVER_STATUS_CHANGED, FALSE, FMI_DRIVER_COUNT, ClientListItem::getCurrentName(), INVALID32, ClientListItem::isValid(), Event::post(), and TRUE.
void FmiApplicationLayer::rebootDevice ()
Send a command to the attached device to reboot it.
Definition at line 4087 of file FmiApplicationLayer.cpp.
References FMI_REBOOT_DEVICE_REQUEST, and txFmi().
void FmiApplicationLayer::removeStopById (uint32 aUniqueId) private
Find the index of the deleted stop corresponding to a stop ID.
Since the index in the stop list is not sent back on a stop status update for a deleted stop, we must find the index that needs to be deleted before calling update_delete_stop.
Parameters
aUniqueId The unique_id of the stop to delete
Since
Protocol A603
Definition at line 2188 of file FmiApplicationLayer.cpp.
void FmiApplicationLayer::removeStopByIndex (uint16 aStopIndex)
Remove a deleted stop.
This function is called when the client deletes a stop or responds to a delete request by the server. It removes the unique id from the mA603Stops, updates the mStopIndexInList vector, and deletes the stop from the save file.
Parameters
aStopIndex The index of the stop in the list.
Since
Protocol A603
Definition at line 2211 of file FmiApplicationLayer.cpp.
References INVALID32.
void FmiApplicationLayer::resetCannedMessages () private
Clear the canned messages on the server.
Since
Protocol A604
Definition at line 3936 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::clear(), EVENT_FMI_CANNED_MSG_LIST_CHANGED, mCannedMessages, and Event::post().
void FmiApplicationLayer::resetCannedResponseMessages () private
Clear the canned response text messages on the server.
Since
Protocol A604
Definition at line 3947 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::clear(), and mSentCannedResponseMessages.
void FmiApplicationLayer::resetCannedResponses () private
Clear the canned responses on the server.
Since
Protocol A604
Definition at line 3956 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::clear(), EVENT_FMI_CANNED_RESP_LIST_CHANGED, mCannedResponses, and Event::post().
void FmiApplicationLayer::resetDriverStatusList () private
Clear the driver statuses on the server.
Since
Protocol A604
Definition at line 3967 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::clear(), EVENT_FMI_DRIVER_STATUS_LIST_CHANGED, mDriverStatuses, and Event::post().
void FmiApplicationLayer::resetSavedStops () private
Clear the stop list on the server.
Since
Protocol A603
Definition at line 3908 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::clear(), mA603Stops, and mStopIndexInList.
void FmiApplicationLayer::resetWaypoints () private
Clear the waypoint and waypoint category lists on the server.
Since
Protocol A607
Definition at line 3921 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::clear(), EVENT_FMI_CATEGORY_LIST_CHANGED, EVENT_FMI_WAYPOINT_LIST_CHANGED, mCategories, mWaypoints, and Event::post().
bool FmiApplicationLayer::rx (const Packet * aPacket) virtual
Handle a packet received from the client.
This is where all the magic happens. This function sets up the state variables containing the data received from the client to be displayed by the fmi_pc_app user interface, and dispatches Windows messages as appropriate for the user interface to process. It also transmits the next packet in the protocol when there is one.
Parameters
aPacket The received packet to process
Returns
true if the packet was handled, false if an error occurred (for example, a packet was to be sent in response, but the send failed)
Implements ApplicationLayer.
Definition at line 201 of file FmiApplicationLayer.cpp.
References text_msg_ack_event_type::ack_text, pvt_data_type::altitude, FileBackedMap< T >::begin(), CANNED_RESP_LIST_SUCCESS, fmi_driver_profile_data_type::carrier_id, fmi_driver_profile_data_type::carrier_name, delete_by_category_rcpt_data_type::cat_id, cnt_of_array, CODEPAGE_UNICODE, ClientListItem::commitName(), AobrdEventLogConverter::convertToRaw(), AobrdEventLogConverter::countRecords(), file_end_data_type::crc, custom_form_position_ack_type::current_position, protocol_support_data_type::data, file_packet_data_type::data_length, stop_calc_ack_type::distance, eta_data_type::distance_to_destination, AobrdEventLogConverter::DRIVER_ANNOTATION, driver_id_data_type::driver_id, driver_id_D607_data_type::driver_id, driver_login_service_data_type::driver_id, fmi_driver_profile_type::driver_id, fmi_driver_profile_data_type::driver_id, fmi_driver_status_update_request_data_type::driver_id, fmi_driver_status_log_dnld_resp_data_type::driver_id, fmi_driver_shipment_data_type::driver_id, fmi_shipment_download_receipt_data_type::driver_id, fmi_annotation_download_request_data_type::driver_id, fmi_driver_annotation_data_type::driver_id, fmi_driver_aobrd_ack_data_type::driver_id, driver_id_D607_data_type::driver_idx, driver_id_receipt_data_type::driver_idx, driver_status_D607_data_type::driver_idx, driver_status_receipt_data_type::driver_idx, driver_login_service_data_type::driver_password, driver_status_data_type::driver_status, driver_status_D607_data_type::driver_status, pvt_data_type::east_velocity, EMPTY_DATA, FileBackedMap< T >::end(), eta_data_type::eta_time, EVENT_ESN_RECEIVED, EVENT_FMI_A604_TXT_MSG_ERROR, EVENT_FMI_CANNED_MSG_LIST_CHANGED, EVENT_FMI_CANNED_RESP_LIST_CHANGED, EVENT_FMI_CANNED_RESP_LIST_RCPT_ERROR, EVENT_FMI_CATEGORY_LIST_CHANGED, EVENT_FMI_DELETE_TEXT_MESSAGE_STATUS, EVENT_FMI_DRIVER_ID_CHANGED, EVENT_FMI_DRIVER_STATUS_LIST_CHANGED, EVENT_FMI_DRIVER_STATUS_LIST_DELETE_FAILED, EVENT_FMI_ETA_RECEIVED, EVENT_FMI_FILE_TRANSFER_PROGRESS, EVENT_FMI_FILE_TRANSFER_STATE_CHANGED, EVENT_FMI_FORM_DELETED, EVENT_FMI_FORM_POSITION_CHANGED, EVENT_FMI_GPI_FILE_INFO_RECEIVED, EVENT_FMI_LONG_TEXT_MSG_ERROR, EVENT_FMI_MSG_THROTTLE_ERROR, EVENT_FMI_MSG_THROTTLE_QUERY_RESP_RECEIVED, EVENT_FMI_PING_RECEIVED, EVENT_FMI_PING_RESPONSE_RECEIVED, EVENT_FMI_ROUTE_CALCULATED, EVENT_FMI_SAFE_MODE_ERROR, EVENT_FMI_SPEED_LIMIT_SET_RESULT, EVENT_FMI_STOP_STATUS_CHANGED, EVENT_FMI_TXT_MSG_ACK, EVENT_FMI_TXT_MSG_FROM_CLIENT, EVENT_FMI_TXT_MSG_STATUS_RECEIVED, EVENT_FMI_UI_UPDATE_ERROR, EVENT_FMI_WAYPOINT_LIST_CHANGED, EVENT_PRODUCT_ID_RECEIVED, EVENT_PROTOCOLS_RECEIVED, EVENT_PVT_RECEIVED, FALSE, file_packet_data_type::file_data, file_info_data_type::file_size, file_info_data_type::file_version, file_info_data_type::file_version_length, fmi_driver_profile_data_type::first_name, FMI_ANNOTATION_DOWNLOAD_RECEIPT, FMI_ANNOTATION_DOWNLOAD_REQUEST, FMI_ANNOTATION_DOWNLOAD_RESPONSE, FMI_CUSTOM_FORM_DEL_RECEIPT, FMI_CUSTOM_FORM_GET_POS_RECEIPT, FMI_CUSTOM_FORM_MOVE_RECEIPT, FMI_DOWNLOAD_SHIPMENTS_REQUEST, FMI_DRIVER_COUNT, FMI_DRIVER_LOGIN_REQUEST, FMI_DRIVER_LOGIN_RESPONSE, FMI_DRIVER_PROFILE_DOWNLOAD_REQUEST, FMI_DRIVER_PROFILE_DOWNLOAD_RESPONSE, FMI_DRIVER_STATUS_UPDATE_RECEIPT, FMI_DRIVER_STATUS_UPDATE_REQUEST, FMI_DRIVER_STATUS_UPDATE_RESPONSE, FMI_FILE_TYPE_AOBRD, FMI_ID_A604_OPEN_TEXT_MSG_RCPT, FMI_ID_A607_CLIENT_OPEN_TXT_MSG, FMI_ID_CANNED_RESP_LIST_RCPT, FMI_ID_CLIENT_OPEN_TXT_MSG, FMI_ID_CLIENT_TXT_MSG_RCPT, FMI_ID_CREATE_WAYPOINT_CAT_RCPT, FMI_ID_DEL_DRIVER_STATUS_LIST_ITEM_RCPT, FMI_ID_DELETE_CANNED_MSG_RCPT, FMI_ID_DELETE_CANNED_RESPONSE_RCPT, FMI_ID_DELETE_WAYPOINT_CAT_RCPT, FMI_ID_DRIVER_ID_RCPT, FMI_ID_DRIVER_ID_UPDATE, FMI_ID_DRIVER_ID_UPDATE_D607, FMI_ID_DRIVER_STATUS_LIST_REFRESH, FMI_ID_DRIVER_STATUS_RCPT, FMI_ID_DRIVER_STATUS_UPDATE, FMI_ID_DRIVER_STATUS_UPDATE_D607, FMI_ID_ETA_DATA, FMI_ID_ETA_DATA_RCPT, FMI_ID_FILE_DATA_PACKET, FMI_ID_FILE_END_RCPT, FMI_ID_FILE_PACKET_RCPT, FMI_ID_FILE_START_RCPT, FMI_ID_FILE_TRANSFER_END, FMI_ID_FILE_TRANSFER_START, FMI_ID_GPI_FILE_INFORMATION, FMI_ID_LONG_TEXT_MSG, FMI_ID_LONG_TEXT_MSG_RCPT, FMI_ID_MSG_THROTTLING_QUERY_RESPONSE, FMI_ID_MSG_THROTTLING_RESPONSE, FMI_ID_PING, FMI_ID_PING_RESPONSE, FMI_ID_PRODUCT_ID_DATA, FMI_ID_PROTOCOL_DATA, FMI_ID_REFRESH_CANNED_MSG_LIST, FMI_ID_REFRESH_CANNED_RESP_LIST, FMI_ID_SET_CANNED_MSG_RCPT, FMI_ID_SET_CANNED_RESPONSE_RCPT, FMI_ID_SET_DRIVER_STATUS_LIST_ITEM_RCPT, FMI_ID_SORT_STOP_LIST_ACK, FMI_ID_STOP_STATUS, FMI_ID_STOP_STATUS_RCPT, FMI_ID_TEXT_MSG_ACK, FMI_ID_TEXT_MSG_ACK_RCPT, FMI_ID_TEXT_MSG_DELETE_RESPONSE, FMI_ID_TEXT_MSG_STATUS, FMI_ID_UNICODE_REQUEST, FMI_ID_UNICODE_RESPONSE, FMI_ID_USER_INTERFACE_TEXT_RCPT, FMI_ID_WAYPOINT_DELETED, FMI_ID_WAYPOINT_DELETED_RCPT, FMI_ID_WAYPOINT_RCPT, FMI_LOGIN_NO_ERRORS, FMI_SAFE_MODE_RESP, FMI_SHIPMENT_DOWNLOAD_RECEIPT, FMI_SHIPMENT_DOWNLOAD_RESPONSE, FMI_SPEED_LIMIT_ALERT, FMI_SPEED_LIMIT_ALERT_RCPT, FMI_SPEED_LIMIT_RCPT, FMI_STOP_CALC_ACK_RECEIPT, FMI_STOP_CALC_ACK_REQUEST, custom_form_delete_ack_type::form_id, custom_form_position_ack_type::form_id, AobrdDriverItem::getCarrierID(), AobrdDriverItem::getCarrierName(), ClientListItem::getCurrentName(), AobrdDriverItem::getFirstName(), ClientListItem::getId(), SerialPort::getInstance(), AobrdDriverItem::getLastName(), AobrdDriverItem::getLongTermRuleset(), DriverLoginItem::getPassword(), AobrdDriverItem::getPassword(), AobrdDriverItem::getShipments(), AobrdDriverItem::getTimeZone(), GPS_FIX_2D, GPS_FIX_2D_DIFF, GPS_FIX_3D, GPS_FIX_3D_DIFF, GPS_FIX_INVALID, GPS_FIX_UNUSABLE, text_msg_ack_data_type::id, client_to_server_D607_open_text_msg_data_type::id, server_to_client_text_msg_receipt_data_type::id, canned_response_list_receipt_data_type::id, message_status_data_type::id, text_msg_id_data_type::id, category_rcpt_data_type::id, long_text_msg_receipt_data_type::id, ID_FMI_PACKET, ID_PRODUCT_DATA, ID_PVT_DATA, text_msg_ack_data_type::id_size, client_to_server_D607_open_text_msg_data_type::id_size, server_to_client_text_msg_receipt_data_type::id_size, canned_response_list_receipt_data_type::id_size, message_status_data_type::id_size, text_msg_id_data_type::id_size, long_text_msg_receipt_data_type::id_size, ID_UNIT_ID, INVALID16, INVALID32, INVALID_LAT, ClientListItem::isValid(), fmi_driver_profile_data_type::last_name, sc_position_type::lat, double_position_type::lat, text_msg_from_client_event_type::latitude, pvt_data_type::leap_seconds, text_msg_from_client_event_type::link_id, sc_position_type::lon, double_position_type::lon, fmi_driver_profile_data_type::long_term_rule_set, LONG_TEXT_MSG_CHUNK_SIZE, LONG_TEXT_SUCCESS, text_msg_from_client_event_type::longitude, MAX_THROTTLED_PROTOCOLS, maxval, text_msg_ack_event_type::message_id, text_msg_from_client_event_type::message_id, canned_message_receipt_data_type::message_id, text_msg_status_event_type::message_status, text_msg_from_client_event_type::message_text, MESSAGE_THROTTLE_STATE_DISABLE, MESSAGE_THROTTLE_STATE_ENABLE, minval, GarminPacket::mPacketId, GarminPacket::mPayload, GarminPacket::mPayloadSize, text_msg_ack_data_type::msg_ack_type, text_msg_status_event_type::msg_id, message_throttling_data_type::new_state, packet_receipt_data_type::next_offset, NO_ACK, pvt_data_type::north_velocity, file_packet_data_type::offset, packet_receipt_data_type::offset, OK_ACK, text_msg_from_client_event_type::origination_time, client_to_server_open_text_msg_data_type::origination_time, client_to_server_D607_open_text_msg_data_type::origination_time, message_throttling_data_type::packet_id, driver_id_D607_data_type::password, pvt_data_type::position, eta_data_type::position_of_destination, Event::post(), product_id_data_type::product_id, REQUEST_STOP_STATUS, request_canned_response_list_refresh_data_type::response_count, message_throttling_list_data_type::response_count, canned_response_receipt_data_type::response_id, request_canned_response_list_refresh_data_type::response_id, message_throttling_list_data_type::response_list, file_receipt_data_type::result_code, server_to_client_text_msg_receipt_data_type::result_code, canned_response_receipt_data_type::result_code, canned_response_list_receipt_data_type::result_code, driver_id_receipt_data_type::result_code, driver_status_list_item_receipt_data_type::result_code, driver_status_receipt_data_type::result_code, canned_message_receipt_data_type::result_code, user_interface_text_receipt_data_type::result_code, safe_mode_speed_receipt_data_type::result_code, speed_limit_receipt_data_type::result_code, waypoint_rcpt_data_type::result_code, category_rcpt_data_type::result_code, delete_message_response_data_type::result_code, driver_login_service_receipt::result_code, fmi_driver_profile_data_type::result_code, fmi_driver_status_log_dnld_resp_data_type::result_code, fmi_shipment_download_receipt_data_type::result_code, fmi_driver_aobrd_ack_data_type::result_code, long_text_msg_receipt_data_type::result_code, stop_calc_ack_type::result_code, custom_form_delete_ack_type::return_code, custom_form_position_ack_type::return_code, SAVE_AOBRD_LOG, SAVE_CONVERTED_AOBRD_LOG, client_to_server_D607_open_text_msg_data_type::scposn, long_text_msg_receipt_data_type::sequence_number, fmi_driver_shipment_data_type::server_result_code, fmi_driver_annotation_data_type::server_result_code, SerialPort::setBaudRate(), setbit, ClientListItem::setValid(), product_id_data_type::software_version, fmi_driver_profile_data_type::status, driver_id_data_type::status_change_id, driver_id_D607_data_type::status_change_id, driver_id_receipt_data_type::status_change_id, driver_status_data_type::status_change_id, driver_status_D607_data_type::status_change_id, driver_status_receipt_data_type::status_change_id, message_status_data_type::status_code, driver_status_list_item_receipt_data_type::status_id, stop_status_data_type::stop_index_in_list, stop_status_data_type::stop_status, STOP_STATUS_ACTIVE, STOP_STATUS_DELETED, protocol_support_data_type::tag, client_to_server_open_text_msg_data_type::text_message, client_to_server_D607_open_text_msg_data_type::text_message, gps_time_type::time_of_week, pvt_data_type::time_of_week, fmi_driver_profile_data_type::time_zone, speed_limit_alert_data_type::timestamp, speed_limit_alert_receipt_data_type::timestamp, TRUE, pvt_data_type::type_of_gps_fix, driver_login_service_data_type::ui_timestamp, driver_login_service_receipt::ui_timestamp, client_to_server_open_text_msg_data_type::unique_id, client_to_server_text_msg_receipt_data_type::unique_id, client_to_server_D607_open_text_msg_data_type::unique_id, stop_status_data_type::unique_id, stop_status_receipt_data_type::unique_id, eta_data_type::unique_id, eta_data_receipt_type::unique_id, waypoint_rcpt_data_type::unique_id, stop_calc_ack_type::unique_id, stop_calc_ack_rcpt_type::unique_id, unit_id_data_type::unit_id, UNKNOWN_DRIVER, pvt_data_type::up_velocity, UTIL_convert_gps_time_to_seconds(), UTIL_convert_radians_to_degrees(), UTIL_convert_seconds_to_date_type(), UTIL_convert_seconds_to_time_type(), UTIL_convert_semicircles_to_degrees(), UTIL_convert_UTC_to_local(), UTIL_format_date_string(), UTIL_format_time_string(), UTIL_hex_to_uint8(), UTL_calc_crc32(), gps_time_type::week_number_days, pvt_data_type::week_number_days, and YES_ACK.
void FmiApplicationLayer::sendA602Stop (double aDegreesLatitude, double aDegreesLongitude, char * aStopName)
Initiates the A602 stop protocol.
Parameters
aDegreesLatitude The destination latitude, in degrees (positive is north)
aDegreesLongitude The destination longitude, in degrees (positive is east)
aStopName A null-terminated string in the client codepage containing the name of the stop.
Note
This does not include a stop id, so no further updates will be sent about this stop.
Since
Protocol A602
Definition at line 1950 of file FmiApplicationLayer.cpp.
References FMI_ID_A602_STOP, sc_position_type::lat, sc_position_type::lon, offset_of, A602_stop_data_type::origination_time, A602_stop_data_type::stop_position, A602_stop_data_type::text, UTIL_convert_degrees_to_semicircles(), and UTIL_get_current_garmin_time().
Referenced by CStopNewDlg::OnBnClickedOk().
void FmiApplicationLayer::sendA602TextMessage (fmi_id_type aFmiPacketId, char * aMessageText, const MessageId & aMessageId)
Send a server to client text message, for all A602 FMI protocols.
This function is called for all A602 FMI text messages. Since these text message protocols don't need an id or id_size, these arguments are given default values of NULL and 0 respectively
Parameters
aFmiPacketId FMI packet ID for the protocol to use
aMessageText Message text, as a null-terminated string in the client codepage
aMessageId The message ID.
Since
Protocol A602
Definition at line 1991 of file FmiApplicationLayer.cpp.
References FMI_ID_SERVER_OPEN_TXT_MSG, MessageId::getId(), MessageId::getIdSize(), server_to_client_ack_text_msg_data_type::id, server_to_client_ack_text_msg_data_type::id_size, offset_of, A602_server_to_client_open_text_msg_data_type::origination_time, server_to_client_ack_text_msg_data_type::origination_time, A602_server_to_client_open_text_msg_data_type::text_message, server_to_client_ack_text_msg_data_type::text_message, and UTIL_get_current_garmin_time().
Referenced by CTxtMsgNewDlg::OnBnClickedOk().
void FmiApplicationLayer::sendA603Stop (double aLatitude, double aLongitude, char * aStopName, uint32 aStopId)
Initiates the A603 stop protocol.
Parameters
aLatitude The destination latitude, in degrees (positive is north)
aLongitude The destination longitude, in degrees (positive is east)
aStopName A null-terminated string containing the name of the stop.
aStopId The stop ID to use.
Since
Protocol A603
Definition at line 2262 of file FmiApplicationLayer.cpp.
References FMI_ID_A603_STOP, sc_position_type::lat, sc_position_type::lon, minval, offset_of, A603_stop_data_type::origination_time, StopListItem::setCurrentName(), StopListItem::setStopStatus(), ClientListItem::setValid(), A603_stop_data_type::stop_position, STOP_STATUS_UNREAD, A603_stop_data_type::text, A603_stop_data_type::unique_id, UTIL_convert_degrees_to_semicircles(), and UTIL_get_current_garmin_time().
Referenced by CStopNewDlg::OnBnClickedOk().
void FmiApplicationLayer::sendA604TextMessage (const char * aMessageText, const MessageId & aMessageId, uint8 aMessageType = A604_MESSAGE_TYPE_NORMAL)
Send an A604 server to client open text message.
This function is called to send an A604 server to client text message.
Parameters
aMessageText Message text, as a null-terminated string in the client codepage
aMessageId The message ID.
aMessageType The message type, a value from the a604_message_type enum
Since
Protocol A604
Definition at line 2605 of file FmiApplicationLayer.cpp.
References FMI_ID_A604_OPEN_TEXT_MSG, MessageId::getId(), MessageId::getIdSize(), A604_server_to_client_open_text_msg_data_type::id, A604_server_to_client_open_text_msg_data_type::id_size, A604_server_to_client_open_text_msg_data_type::message_type, offset_of, A604_server_to_client_open_text_msg_data_type::origination_time, A604_server_to_client_open_text_msg_data_type::text_message, and UTIL_get_current_garmin_time().
Referenced by CTxtMsgNewDlg::OnBnClickedOk().
void FmiApplicationLayer::sendA607DriverIdRequest (uint8 aDriverIndex)
Ask the client for the current Driver ID.
Parameters
aDriverIndex The index of the driver
Since
Protocol A607
Definition at line 2815 of file FmiApplicationLayer.cpp.
References driver_id_request_data_type::driver_idx, and FMI_ID_DRIVER_ID_REQUEST.
void FmiApplicationLayer::sendA607DriverIdUpdate (char * aDriverId, uint8 aIndex)
Send an A607 Driver ID Update to the client.
Parameters
aDriverId The new driver ID, in the client's code page
aIndex The driver index
Since
Protocol A607
Definition at line 3983 of file FmiApplicationLayer.cpp.
References cnt_of_array, driver_id_D607_data_type::driver_id, driver_id_D607_data_type::driver_idx, FMI_ID_DRIVER_ID_UPDATE_D607, offset_of, driver_id_D607_data_type::status_change_id, driver_id_D607_data_type::status_change_time, and UTIL_get_current_garmin_time().
void FmiApplicationLayer::sendA607DriverStatusRequest (uint8 aDriverIndex)
Ask the client for the current Driver Status.
Parameters
aDriverIndex The index of the driver
Since
Protocol A607
Definition at line 2832 of file FmiApplicationLayer.cpp.
References driver_id_request_data_type::driver_idx, and FMI_ID_DRIVER_STATUS_REQUEST.
void FmiApplicationLayer::sendA607DriverStatusUpdate (uint32 aDriverStatusId, uint8 aIndex)
Initiate the A607 Driver Status Update protocol.
Parameters
aDriverStatusId The new driver status.
aIndex The driver index.
Note
The driver_status specified must already have been sent to the client using the Set Driver Status List Item protocol.
Since
Protocol A607
Definition at line 4016 of file FmiApplicationLayer.cpp.
References driver_status_D607_data_type::driver_idx, driver_status_D607_data_type::driver_status, FMI_ID_DRIVER_STATUS_UPDATE_D607, driver_status_D607_data_type::status_change_id, driver_status_D607_data_type::status_change_time, and UTIL_get_current_garmin_time().
bool FmiApplicationLayer::sendA611LongTextMessage (const char * aMessageText, const MessageId & aMessageId, uint8 aMessageType)
Send an A611 server to client long text message.
This function is called to send an A611 server to client long text message. It will fail if a long text message is already in progress.
Parameters
aMessageText Message text, as a null-terminated string in the client codepage
aMessageId The message ID
Returns
True if the text message is being sent, false if another long text message is already in progress
Since
Protocol A611
Definition at line 2528 of file FmiApplicationLayer.cpp.
Referenced by CTxtMsgNewDlg::OnBnClickedOk().
void FmiApplicationLayer::sendAOBRDDriverProfile (const AobrdDriverItem & driver)
Send an AOBRD driver profile to the device.
Send updated driver profile to device.
Parameters
driver The driver profile
Since
Protocol A610
Definition at line 3423 of file FmiApplicationLayer.cpp.
References fmi_driver_profile_data_type::carrier_id, fmi_driver_profile_data_type::carrier_name, fmi_driver_profile_data_type::driver_id, fmi_driver_profile_data_type::first_name, FMI_DRIVER_PROFILE_UPDATE, AobrdDriverItem::getCarrierID(), AobrdDriverItem::getCarrierName(), AobrdDriverItem::getDriverId(), AobrdDriverItem::getFirstName(), AobrdDriverItem::getLastName(), AobrdDriverItem::getLongTermRuleset(), AobrdDriverItem::getTimeZone(), fmi_driver_profile_data_type::last_name, fmi_driver_profile_data_type::long_term_rule_set, fmi_driver_profile_data_type::result_code, fmi_driver_profile_data_type::status, and fmi_driver_profile_data_type::time_zone.
void FmiApplicationLayer::sendAOBRDOdometerValue (uint32 aOdometer)
Send AOBRD Odometer value to device.
Set AOBRD odometer value.
This function sets odometer value on the client.
Parameters
aOdometer New odometer value
Since
Protocol A610
Definition at line 3337 of file FmiApplicationLayer.cpp.
References FMI_SET_ODOMETER_REQUEST, and set_odometer_request_data_type::odometer_value.
Referenced by CAobrdOdometerDlg::OnBnClickedOk().
void FmiApplicationLayer::sendAutoArrival (uint32 aAutoArrivalTime, uint32 aAutoArrivalDistance)
Send a request to update the auto-arrival preferences.
Parameters
aAutoArrivalTime The minimum stop time, in seconds
aAutoArrivalDistance The minimum stop distance, in meters
Since
Protocol A603
Definition at line 2313 of file FmiApplicationLayer.cpp.
References FMI_ID_AUTO_ARRIVAL, auto_arrival_data_type::stop_distance, and auto_arrival_data_type::stop_time.
Referenced by CAutoArrivalDlg::OnBnClickedOk().
void FmiApplicationLayer::sendCannedMessage (uint32 aMessageId, CString aMessageText)
Transmit a new or updated canned message to the client.
Parameters
aMessageId The canned message ID
aMessageText The message text associated with the ID
Since
Protocol A604
Definition at line 2728 of file FmiApplicationLayer.cpp.
References FMI_ID_SET_CANNED_MSG, canned_message_data_type::message, canned_message_data_type::message_id, offset_of, ClientListItem::setId(), and ClientListItem::setUpdateName().
void FmiApplicationLayer::sendCannedResponse (uint32 aResponseId, CString aResponseText)
Transmit a new or updated canned response to the client.
Parameters
aResponseId The canned response ID
aResponseText The response text associated with the ID
Since
Protocol A604
Definition at line 2695 of file FmiApplicationLayer.cpp.
References FMI_ID_SET_CANNED_RESPONSE, offset_of, canned_response_data_type::response_id, canned_response_data_type::response_text, and ClientListItem::setUpdateName().
bool FmiApplicationLayer::sendCannedResponseTextMessage (const char * aMessageText, const MessageId & aMessageId, uint8 aResponseCount, const uint32 * aResponseList, uint8 aMessageType)
Initiate the canned response text message protocol.
Send a Canned Response List packet, and save the values (message text, message type, etc.) that are sent in later packets. The actual text message will be sent by handle_rx when the canned response list receipt is processed.
Parameters
aMessageText The message text, as a null-terminated string in the client codepage
aMessageId The message ID
aResponseCount The number of allowed responses
aResponseList Pointer to an array of allowed responses.
aMessageType The aMessageType for the message; see the a604_message_type enum.
Returns
False if A611 protocol is available, a long text message is necessary, and a long text message is in progress. Otherwise true.
Since
Protocol A604
Definition at line 2647 of file FmiApplicationLayer.cpp.
References cnt_of_array, FMI_ID_SET_CANNED_RESP_LIST, MessageId::getId(), MessageId::getIdSize(), canned_response_list_data_type::id, canned_response_list_data_type::id_size, LONG_TEXT_MSG_CHUNK_SIZE, minval, offset_of, canned_response_list_data_type::response_count, and canned_response_list_data_type::response_id.
void FmiApplicationLayer::sendCreateWaypointCat (uint8 aCatId, CString & aCatName)
Create waypoint category.
Parameters
aCatId The category ID (0-15)
aCatName The category name
Definition at line 3290 of file FmiApplicationLayer.cpp.
References FMI_ID_CREATE_WAYPOINT_CAT, category_data_type::id, category_data_type::name, and ClientListItem::setUpdateName().
Referenced by CWaypointDlg::OnBnClickedWptBtnCreateCat().
void FmiApplicationLayer::sendDataDeletionRequest (del_data aDelDataType)
Send a data deletion request and remove the appropriate data from the server.
Parameters
aDelDataType The type of data that the client should delete
Since
Protocol A603
Definition at line 2355 of file FmiApplicationLayer.cpp.
References data_deletion_data_type::data_type, DELETE_ALL_MESSAGES, DELETE_ALL_STOPS, DELETE_CANNED_MESSAGES, DELETE_CANNED_RESPONSES, DELETE_DRIVER_ID_AND_STATUS, DELETE_WAYPOINTS, DISABLE_FMI, and FMI_ID_DATA_DELETION.
void FmiApplicationLayer::sendDeleteCannedMessageRequest (uint32 aMessageId)
Send a request to the client to delete a canned message.
Parameters
aMessageId The canned message ID to delete
Since
Protocol A604
Definition at line 2775 of file FmiApplicationLayer.cpp.
References FMI_ID_DELETE_CANNED_MSG, and canned_message_delete_data_type::message_id.
void FmiApplicationLayer::sendDeleteCannedResponseRequest (uint32 aResponseId)
Send a request to the client to delete a canned response.
Parameters
aResponseId The canned response ID to delete
Since
Protocol A604
Definition at line 2760 of file FmiApplicationLayer.cpp.
References FMI_ID_DELETE_CANNED_RESPONSE, and canned_response_delete_data_type::response_id.
void FmiApplicationLayer::sendDeleteDriverStatusListItem (uint32 aStatusId)
Initiate the Delete Driver Status List Item protocol.
Parameters
aStatusId The ID of the item to be deleted on the client
Since
Protocol A604
Definition at line 2790 of file FmiApplicationLayer.cpp.
References FMI_ID_DELETE_DRIVER_STATUS_LIST_ITEM, and driver_status_list_item_delete_data_type::status_id.
void FmiApplicationLayer::sendDeleteWaypoint (uint16 aUniqueId)
Delete a waypoint.
Parameters
aUniqueId The unique ID of the waypoint to delete
Since
Protocol A607
Definition at line 3237 of file FmiApplicationLayer.cpp.
References EVENT_FMI_WAYPOINT_LIST_CHANGED, FMI_ID_WAYPOINT_DELETE, and Event::post().
Referenced by CWaypointDlg::OnBnClickedWptBtnDelete().
void FmiApplicationLayer::sendDeleteWaypointCat (uint16 aCatIdx)
Delete waypoint category.
Parameters
aCatIdx The category to delete
Since
Protocol A607
Definition at line 3255 of file FmiApplicationLayer.cpp.
References FileBackedMap< T >::begin(), FileBackedMap< T >::end(), EVENT_FMI_WAYPOINT_LIST_CHANGED, FALSE, FMI_ID_DELETE_WAYPOINT_CAT, Event::post(), and ClientListItem::setValid().
Referenced by CWaypointDlg::OnBnClickedWptBtnDeleteCat().
void FmiApplicationLayer::sendDriverIdRequest ()
Ask the client for the current Driver ID.
Since
Protocol A604
Definition at line 2803 of file FmiApplicationLayer.cpp.
References FMI_ID_DRIVER_ID_REQUEST, and txFmi().
void FmiApplicationLayer::sendDriverIdUpdate (char * aDriverId)
Send a Driver ID Update to the client.
Parameters
aDriverId The new driver ID, in the client's code page
Since
Protocol A604
Definition at line 2850 of file FmiApplicationLayer.cpp.
References cnt_of_array, driver_id_data_type::driver_id, FMI_ID_DRIVER_ID_UPDATE, offset_of, driver_id_data_type::status_change_id, driver_id_data_type::status_change_time, and UTIL_get_current_garmin_time().
void FmiApplicationLayer::sendDriverStatusListItem (uint32 aStatusId, CString aStatusText)
Initiate the Set Driver Status List Item protocol.
Parameters
aStatusId The ID of the aStatusText item to be added (or updated) on the client
aStatusText The textual description corresponding to the id
Since
Protocol A604
Definition at line 2880 of file FmiApplicationLayer.cpp.
References FMI_ID_SET_DRIVER_STATUS_LIST_ITEM, offset_of, ClientListItem::setUpdateName(), driver_status_list_item_data_type::status, and driver_status_list_item_data_type::status_id.
void FmiApplicationLayer::sendDriverStatusRequest ()
Asks the client for the current driver status.
Since
Protocol A604
Definition at line 2910 of file FmiApplicationLayer.cpp.
References FMI_ID_DRIVER_STATUS_REQUEST, and txFmi().
void FmiApplicationLayer::sendDriverStatusUpdate (uint32 aDriverStatusId)
Initiate the Driver Status Update protocol.
Parameters
aDriverStatusId The new driver status.
Note
The driver_status specified must already have been sent to the client using the Set Driver Status List Item protocol.
Since
Protocol A604
Definition at line 2923 of file FmiApplicationLayer.cpp.
References driver_status_data_type::driver_status, FMI_ID_DRIVER_STATUS_UPDATE, driver_status_data_type::status_change_id, driver_status_data_type::status_change_time, and UTIL_get_current_garmin_time().
void FmiApplicationLayer::sendEnable (uint16 * aFeatureCodes = NULL, uint8 aFeatureCount = 0)
Transmit an FMI Enable packet, and clear any error state.
Make sure there is an FMI Enable packet at the head of the tx queue, then send it. This packet may already be present if a previous enable timed out.
Parameters
aFeatureCodes Array of feature codes to send
aFeatureCount Number of feature codes to send. To send an A602 enable, this must be zero.
Since
Protocol A602
Definition at line 2049 of file FmiApplicationLayer.cpp.
References fmi_features_data_type::feature_count, fmi_features_data_type::features, FMI_ID_ENABLE, offset_of, fmi_features_data_type::reserved, and TRUE.
Referenced by CFeatureDlg::OnBnClickedOk(), and CCommErrorDlg::OnBnClickedRetry().
void FmiApplicationLayer::sendEnablePvtCommand (bool aEnable)
Send an Enable PVT or Disable PVT command.
Parameters
aEnable If TRUE, send an enable PVT command, else send a disable PVT command
Definition at line 1831 of file FmiApplicationLayer.cpp.
References COMMAND_TURN_OFF_PVT_DATA, and COMMAND_TURN_ON_PVT_DATA.
void FmiApplicationLayer::sendEtaRequest ()
Send a request for ETA data.
Since
Protocol A603
Definition at line 2414 of file FmiApplicationLayer.cpp.
References FMI_ID_ETA_DATA_REQUEST, and txFmi().
void FmiApplicationLayer::sendFile (char * aFilename, uint8 aVersionLength, uint8 * aVersion, uint8 aFileType, BOOL gzipIt = FALSE)
Start a file transfer protocol.
This sends the start request, the rest of the transfer is performed in rx when the receipt packets are received.
Parameters
aFilename The local file name to transfer
aVersionLength The number of significant bytes of aVersion (must be between 0 and 16, inclusive)
aVersion An array of bytes of aVersion data to associate with this file.
aFileType One of several options that the device should be aware of
gzipIt A flag for determining if the file should be compressed before sending
Since
Protocol A604
Definition at line 2977 of file FmiApplicationLayer.cpp.
References cnt_of_array, EVENT_FMI_FILE_TRANSFER_STATE_CHANGED, FALSE, file_info_data_type::file_size, file_info_data_type::file_type, file_info_data_type::file_version, file_info_data_type::file_version_length, FMI_ID_FILE_TRANSFER_START, GZIPPED_TRANSFER_FILENAME, minval, and Event::post().
Referenced by CStopNewDlg::OnBnClickedOk().
void FmiApplicationLayer::sendFmiPacket (uint16 aFmiPacketId, uint8 * aFmiPayload, uint8 aFmiPayloadSize)
Send an arbitrary FMI packet.
Sends a user-specified FMI packet to the client. This packet is not checked for errors, and no data structures are updated when the packet is sent. However, packets received in response to this packet are handled normally.
Parameters
aFmiPacketId The FMI packet ID
aFmiPayload The FMI payload
aFmiPayloadSize The size of the FMI payload
Since
Protocol A602
Definition at line 2095 of file FmiApplicationLayer.cpp.
Referenced by CFeatureDlg::OnBnClickedOk().
void FmiApplicationLayer::sendFmiSafeModeSpeed (float aSpeed)
Set FMI safe mode speed.
This function sets safe mode speed on the client
Parameters
aSpeed Safe mode speed
Returns
TRUE if the packet was ACK'd, FALSE if a timeout occurred
Since
Protocol A606
Definition at line 2333 of file FmiApplicationLayer.cpp.
References FMI_SAFE_MODE, and safe_mode_speed_data_type::speed.
Referenced by CSafeModeDlg::OnBnClickedOk().
void FmiApplicationLayer::sendFreeformFmiPacket (fmi_id_type const aFmiPacketId, uint8 const *const aFmiPayload, uint8 const aFmiPayloadSize)
Definition at line 2105 of file FmiApplicationLayer.cpp.
References MAX_PAYLOAD_SIZE.
void FmiApplicationLayer::sendGpiFileInfoRequest ()
Send a GPI File Information Request to the client.
Since
Protocol A604
Definition at line 3049 of file FmiApplicationLayer.cpp.
References FMI_ID_GPI_FILE_INFORMATION_REQUEST, and txFmi().
Referenced by CGpiQueryDlg::OnBnClickedUpdate().
void FmiApplicationLayer::sendMessageDeleteRequest (const MessageId & aMessageId)
Ask the server to delete a text message.
Parameters
aMessageId The message ID
Since
Protocol A607
Definition at line 3315 of file FmiApplicationLayer.cpp.
References FMI_ID_TEXT_MSG_DELETE_REQUEST, MessageId::getId(), MessageId::getIdSize(), delete_message_request_data_type::id, and delete_message_request_data_type::id_size.
Referenced by CTxtMsgDeleteRequestDlg::OnBnClickedOk().
void FmiApplicationLayer::sendMessageThrottlingQuery ()
Initiate the Message Throttling Query protocol.
Since
Protocol A605
Definition at line 3178 of file FmiApplicationLayer.cpp.
References FMI_ID_MSG_THROTTLING_QUERY, and txFmi().
Referenced by CMsgThrottlingDlg::OnInitDialog().
void FmiApplicationLayer::sendMessageThrottlingUpdate (uint16 aPacketId, uint16 aThrottleState)
Sends an update to the client to tell it whether to enable or disable a protocol.
Parameters
aPacketId The packet ID of the first packet in the protocol
aThrottleState The new state (0=disable, 1=enable)
Since
Protocol A604
Definition at line 2950 of file FmiApplicationLayer.cpp.
References FMI_ID_MSG_THROTTLING_COMMAND, message_throttling_data_type::new_state, and message_throttling_data_type::packet_id.
Referenced by CMsgThrottlingDlg::OnBnClickedUpdate().
void FmiApplicationLayer::sendNextAOBRDAnnotation (char * driver_id) private
Send next AOBRD annotation to device.
Parameters
driver The driver profile
Since
Protocol A610
Definition at line 3478 of file FmiApplicationLayer.cpp.
References cnt_of_array, CONTAINS_DATA, convertAnnotationRecord(), AobrdEventLogConverter::DRIVER_ANNOTATION, fmi_driver_annotation_data_type::driver_id, EMPTY_DATA, AobrdEventLogConverter::findRecordAt(), FMI_ANNOTATION_DOWNLOAD_RESPONSE, mAOBRDAnnotationDriverId, mAOBRDCurrentAnnotationTxIndex, mAOBRDStopAnnotationTxIndex, SAVE_CONVERTED_AOBRD_LOG, fmi_driver_annotation_data_type::server_result_code, txFmi(), and UNKNOWN_DRIVER.
void FmiApplicationLayer::sendNextAOBRDShipment (char * driver_id) private
Send next AOBRD shipment to device.
Parameters
driver The driver profile
Since
Protocol A610
Definition at line 3354 of file FmiApplicationLayer.cpp.
References cnt_of_array, CONTAINS_DATA, fmi_driver_shipment_data_type::driver_id, EMPTY_DATA, FMI_SHIPMENT_DOWNLOAD_RESPONSE, FileBackedMap< T >::get(), AobrdShipment::getCommodity(), AobrdShipment::getDocNumber(), AobrdShipment::getServerEndTime(), AobrdShipment::getServerStartTime(), AobrdShipment::getServerTimestamp(), AobrdDriverItem::getShipments(), AobrdShipment::getShipperName(), mAOBRDCurrentShipmentTxIndex, mAOBRDDrivers, mAOBRDShipmentDriverId, mAOBRDStopShipmentTxIndex, mClientCodepage, fmi_driver_shipment_data_type::server_commodity, fmi_driver_shipment_data_type::server_doc_number, fmi_driver_shipment_data_type::server_end_time, fmi_driver_shipment_data_type::server_result_code, fmi_driver_shipment_data_type::server_shipper_name, fmi_driver_shipment_data_type::server_start_time, fmi_driver_shipment_data_type::server_timestamp, txFmi(), and UNKNOWN_DRIVER.
void FmiApplicationLayer::sendPing ()
Send a ping packet to the client.
Since
Protocol A604
Definition at line 3072 of file FmiApplicationLayer.cpp.
References FMI_ID_PING, and txFmi().
Referenced by CPingStatusDlg::OnBnClickedSendPing().
void FmiApplicationLayer::sendProductRequest ()
Send an FMI Product ID request.
Since
Protocol A602
Definition at line 2141 of file FmiApplicationLayer.cpp.
References FMI_ID_PRODUCT_ID_SUPPORT_RQST, and txFmi().
void FmiApplicationLayer::sendSetSpeedLimitAlerts (uint8 aMode, uint8 aTimeOver, uint8 aTimeUnder, boolean aAlertUser, float aThreshold)
Set FMI speed limit alerts.
This function sets speed limit alerts on the client
Parameters
aMode Mode
aTimeOver Time over in seconds
aTimeUnder Time under in seconds
aAlertUser Alert audibly when speeding event begins
aThreshold Threshold in m/s over speed limit
Since
Protocol A608
Definition at line 3154 of file FmiApplicationLayer.cpp.
References speed_limit_data_type::alert_user, FMI_SPEED_LIMIT_SET, speed_limit_data_type::mode, speed_limit_data_type::threshold, speed_limit_data_type::time_over, and speed_limit_data_type::time_under.
Referenced by CSpeedLimitAlertsDlg::OnBnClickedSend().
void FmiApplicationLayer::sendStopMoveRequest (uint16 aMoveToIndex, uint16 aMoveFromIndex)
Send a stop move request.
Parameters
aMoveToIndex The index that the stop should be moved to
aMoveFromIndex The index that the stop should be moved from
Since
Protocol A603
Definition at line 2426 of file FmiApplicationLayer.cpp.
References REQUEST_MOVE_STOP.
void FmiApplicationLayer::sendStopSortRequest ()
Sends a sort stop list request to the client.
Note
Once the request is completed, the server will send stop aStopStatus requests for all A603 stops to determine their new position in the list. These requests are sent in rx().
Since
Protocol A604
Definition at line 3084 of file FmiApplicationLayer.cpp.
References FMI_ID_SORT_STOP_LIST, and txFmi().
void FmiApplicationLayer::sendStopStatusRequest (uint32 aStopId, stop_status_status_type aStopStatus, uint16 aMoveToIndex = INVALID16)
Initiate the Stop Status protocol to update an A603 stop.
Parameters
aStopId The unique_id of the stop to update
aStopStatus The new stop aStopStatus
aMoveToIndex The stop_position_in_list if this is a move stop request. Defaults to INVALID16 (0xFFFF)
Since
Protocol A603
Definition at line 2484 of file FmiApplicationLayer.cpp.
References FMI_ID_STOP_STATUS_REQUEST, INVALID16, REQUEST_ACTIVATE_STOP, REQUEST_DELETE_STOP, REQUEST_MARK_STOP_DONE, REQUEST_MOVE_STOP, REQUEST_STOP_STATUS, stop_status_data_type::stop_index_in_list, stop_status_data_type::stop_status, and stop_status_data_type::unique_id.
void FmiApplicationLayer::sendTextMessageStatusRequest (const MessageId & aMessageId)
Ask the server for the aStopStatus of a text message.
Parameters
aMessageId The message ID
Since
Protocol A604
Definition at line 3095 of file FmiApplicationLayer.cpp.
References FMI_ID_TEXT_MSG_STATUS_REQUEST, MessageId::getId(), MessageId::getIdSize(), message_status_request_data_type::id, and message_status_request_data_type::id_size.
Referenced by CTxtMsgStatusRequestDlg::OnBnClickedOk().
void FmiApplicationLayer::sendUnitIdRequest ()
Request the Unit ID (ESN) from the client.
Definition at line 1920 of file FmiApplicationLayer.cpp.
References COMMAND_REQ_UNIT_ID, and txCommand().
void FmiApplicationLayer::sendUserInterfaceText (uint32 aElementId, char * aNewText)
Request that the text of a particular user interface text element be changed.
Parameters
aElementId The ID of the element
aNewText A null-terminated string (50 characters max) containing the new text for the element.
Since
Protocol A604
Definition at line 3117 of file FmiApplicationLayer.cpp.
References FMI_ID_USER_INTERFACE_TEXT, minval, user_interface_text_data_type::new_text, offset_of, and user_interface_text_data_type::text_element_id.
Referenced by CUITextChangeDlg::OnBnClickedOk().
void FmiApplicationLayer::sendWaypoint (uint16 aUniqueId, double aLat, double aLon, uint16 aSymbol, CString & aName, uint16 aCat, CString & aComment)
Send a waypoint.
Parameters
aUniqueId Server-assigned unique ID for the waypoint
aLat The waypoint latitude, in degrees (east is positive)
aLon The waypoint longitude, in degrees (north is positive)
aSymbol The waypoint symbol
aName The waypoint name
aCat Categories that this waypoint is part of (bit mapped)
aComment The waypoint comment
Since
Protocol A607
Definition at line 3197 of file FmiApplicationLayer.cpp.
References waypoint_data_type::cat, waypoint_data_type::comment, FMI_ID_WAYPOINT, sc_position_type::lat, sc_position_type::lon, waypoint_data_type::name, waypoint_data_type::posn, WaypointListItem::setCategories(), ClientListItem::setUpdateName(), waypoint_data_type::symbol, waypoint_data_type::unique_id, and UTIL_convert_degrees_to_semicircles().
Referenced by CWaypointDlg::OnBnClickedWptBtnSend().
void FmiApplicationLayer::startFileReceive (const file_info_data_type & file) private
Save received file chunk.
Parameters
file_size The size of the file
Definition at line 3564 of file FmiApplicationLayer.cpp.
References file_info_data_type::file_type, file_receipt_from_srvr_data_type::file_type, FMI_FILE_RESULT_SUCCESS, FMI_ID_FILE_START_RCPT, and file_receipt_from_srvr_data_type::result_code.
void FmiApplicationLayer::stopFileTransfer ()
Stop a file transfer protocol.
This sets a flag to stop a file transfer. The flag will be processed when the next file or packet receipt is processed in handle_rx().
Since
Protocol A604
Definition at line 3061 of file FmiApplicationLayer.cpp.
References EVENT_FMI_FILE_TRANSFER_STATE_CHANGED, mFileTransferState, mStopFileTransfer, Event::post(), TRANSFER_FAILED, and TRUE.
Referenced by CFileTransferProgressDlg::OnBnClickedStop().
void FmiApplicationLayer::txCommand (command_type const aCommandId) private
Transmit Garmin command packet (packet ID = ID_COMMAND_BYTE)
Parameters
aCommandId The command ID to send to the client.
Definition at line 3859 of file FmiApplicationLayer.cpp.
References FALSE, and ID_COMMAND_BYTE.
Referenced by sendUnitIdRequest().
void FmiApplicationLayer::txFmi (fmi_id_type const aFmiPacketId, uint8 const *const aData, uint8 const aSize, bool const aSendNow = false) private
Transmit FMI packet (packet ID = ID_FMI_BYTE)
This procedure frames and transmits a FMI specific packet.
Parameters
aFmiPacketId The FMI packet ID
aData The FMI payload. This may be NULL if aSize is 0.
aSize The number of bytes in the FMI payload.
aSendNow If TRUE, place this packet at the head of the tx_queue and send it immediately; otherwise add it to the end of the queue and send it after any other packets that are outstanding.
Since
Protocol A602
Definition at line 3881 of file FmiApplicationLayer.cpp.
References ID_FMI_PACKET, and MAX_PAYLOAD_SIZE.
Referenced by endFileReceive(), rebootDevice(), sendDriverIdRequest(), sendDriverStatusRequest(), sendEtaRequest(), sendGpiFileInfoRequest(), sendMessageThrottlingQuery(), sendNextAOBRDAnnotation(), sendNextAOBRDShipment(), sendPing(), sendProductRequest(), and sendStopSortRequest().
Member Data Documentation
FileBackedMap<StopListItem> FmiApplicationLayer::mA603Stops
Map of unique ID to stop details for all A603 stops on the client.
Since
Protocol A603
Definition at line 546 of file FmiApplicationLayer.h.
Referenced by getNextStopId(), CStopNewDlg::OnBnClickedOk(), and resetSavedStops().
bool FmiApplicationLayer::mActiveRoute
If TRUE, the client has a stop active.
This is derived from the ETA data so that it is correct for all stop types.
Since
Protocol A603
Definition at line 542 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
uint32 FmiApplicationLayer::mActiveStopId
Unique ID of the active stop.
Since
Protocol A603
Definition at line 530 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
CString FmiApplicationLayer::mAOBRDAnnotationDriverId private
Driver ID for annotations being sent to device.
Definition at line 845 of file FmiApplicationLayer.h.
Referenced by sendNextAOBRDAnnotation().
int FmiApplicationLayer::mAOBRDCurrentAnnotationTxIndex private
Iterator for annotations being sent to device.
Definition at line 848 of file FmiApplicationLayer.h.
Referenced by sendNextAOBRDAnnotation().
int FmiApplicationLayer::mAOBRDCurrentShipmentTxIndex private
Iterator for shipments being sent to device.
Definition at line 839 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and sendNextAOBRDShipment().
FileBackedMap<AobrdDriverItem> FmiApplicationLayer::mAOBRDDrivers
Map of allowed driver IDs and passwords.
Definition at line 664 of file FmiApplicationLayer.h.
Referenced by sendNextAOBRDShipment().
CString FmiApplicationLayer::mAOBRDShipmentDriverId private
Driver ID for shipments being sent to device.
Definition at line 836 of file FmiApplicationLayer.h.
Referenced by sendNextAOBRDShipment().
int FmiApplicationLayer::mAOBRDStopAnnotationTxIndex private
Iterator end for annotations being sent to device.
Definition at line 851 of file FmiApplicationLayer.h.
Referenced by sendNextAOBRDAnnotation().
int FmiApplicationLayer::mAOBRDStopShipmentTxIndex private
Iterator end for shipments being sent to device.
Definition at line 842 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and sendNextAOBRDShipment().
FileBackedMap<ClientListItem> FmiApplicationLayer::mCannedMessages
Map of canned message IDs to names.
Since
Protocol A604
Definition at line 597 of file FmiApplicationLayer.h.
Referenced by resetCannedMessages().
char FmiApplicationLayer::mCannedResponseMessageBody[TEXT_MSG_BUFFER_MAX_SIZE] private
The message text for the server to client canned text message.
Stored so that the server can send it in response to the canned response list ack message.
Since
Protocol A604
Definition at line 806 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
uint8 FmiApplicationLayer::mCannedResponseMessageType private
The message_type for the server to client canned text message.
Stored so that the server can send it in response to the canned response list ack message.
Since
Protocol A604
Definition at line 812 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
FileBackedMap<ClientListItem> FmiApplicationLayer::mCannedResponses
Map of canned response IDs to names.
Since
Protocol A604
Definition at line 594 of file FmiApplicationLayer.h.
Referenced by resetCannedResponses().
FileBackedMap<ClientListItem> FmiApplicationLayer::mCategories
Map of waypoint category IDs to names.
Definition at line 624 of file FmiApplicationLayer.h.
Referenced by CWaypointDlg::getCatIds(), resetWaypoints(), and CWaypointDlg::updateCatBox().
codepage_type FmiApplicationLayer::mClientCodepage
Code page used for encoding of text fields when communicating with the client.
Definition at line 402 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), CFeatureDlg::OnBnClickedOk(), CSafeModeDlg::OnBnClickedOk(), CAobrdOdometerDlg::OnBnClickedOk(), CTxtMsgStatusRequestDlg::OnBnClickedOk(), CUITextChangeDlg::OnBnClickedOk(), CTxtMsgDeleteRequestDlg::OnBnClickedOk(), CStopNewDlg::OnBnClickedOk(), CTxtMsgNewDlg::OnBnClickedOk(), CGpiQueryDlg::OnGpiInfoReceived(), CTxtMsgAckDlg::OnInitDialog(), CTxtMsgFromClient::OnInitDialog(), CTxtMsgStatusDlg::OnInitDialog(), and sendNextAOBRDShipment().
int FmiApplicationLayer::mClientPingCount
Number of client-to-server pings received; can be reset by the user.
Since
Protocol A604
Definition at line 579 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), CPingStatusDlg::OnBnClickedResetClient(), and CPingStatusDlg::updateTextFields().
uint16 FmiApplicationLayer::mClientProductId
Numeric product ID reported by the client.
See Also
CFmiPcAppDlg::getProductName() for one way to translate this into a human-readable description of the client.
Definition at line 470 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
sint16 FmiApplicationLayer::mClientSoftwareVersion
Raw software version reported by the client.
This should be divided by 100 to obtain a formatted representation. For example, 312 means software version 3.12.
Definition at line 476 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mClientUnitId[11]
Null-terminated ASCII string containing the Unit ID (ESN) of the client.
Definition at line 409 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
file_info_data_type FmiApplicationLayer::mCurrentReceiptFile private
Current file being received.
Definition at line 833 of file FmiApplicationLayer.h.
Referenced by endFileReceive(), and FmiApplicationLayer().
uint8 FmiApplicationLayer::mCurrentSendFileType private
Current file type for file being sent.
Definition at line 830 of file FmiApplicationLayer.h.
char FmiApplicationLayer::mDriverId[FMI_DRIVER_COUNT][50]
Last driver ID received from the client.
Since
Protocol A604
Definition at line 552 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
FileBackedMap<DriverLoginItem> FmiApplicationLayer::mDriverLogins
Map of allowed driver IDs and passwords.
Definition at line 630 of file FmiApplicationLayer.h.
char FmiApplicationLayer::mDriverStatus[FMI_DRIVER_COUNT][50]
Last driver status received from the client.
Since
Protocol A604
Definition at line 555 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
FileBackedMap<ClientListItem> FmiApplicationLayer::mDriverStatuses
Map of driver status IDs to names.
Since
Protocol A604
Definition at line 600 of file FmiApplicationLayer.h.
Referenced by resetDriverStatusList().
bool FmiApplicationLayer::mEnablePending
If true, the FMI Enable protocol is in progress.
Definition at line 487 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mEtaDistance[13]
Null-terminated ASCII string containing the distance to the current destination, including units.
This will be in meters if the distance is less than 1 km, otherwise the units are km. If either the ETA time or ETA distance received from the client is invalid, this will be an empty string.
Since
Protocol A603
Definition at line 508 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mEtaLatitude[14]
String representing the latitude in decimal degrees (and N or S)
Null-terminated ASCII string containing the latitude of the current destination in positive decimal degrees, followed by a direction suffix (N or S). This information is current as of the last ETA packet received. If the last ETA indicated that the ETA time or distance were invalid, this will be an empty string.
Since
Protocol A603
Definition at line 517 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mEtaLongitude[14]
String representing the longitude in decimal degrees (and E or W)
Null-terminated ASCII string containing the longitude of the current destination in positive decimal degrees, followed by a direction suffix (E or W). This information is current as of the last ETA packet received. If the last ETA indicated that the ETA time or distance were invalid, this will be an empty string.
Since
Protocol A603
Definition at line 526 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mEtaTime[13]
String containing the ETA time from the client, or "invalid".
This is a null-terminated ASCII string of the form "HH:MM:SS AA" (hours, minutes, seconds, AM/PM, respectively), or the ASCII string "invalid" if the ETA time or distance received from the client is invalid.
Since
Protocol A603
Definition at line 500 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mFilePath[200] private
Path to the file that is being transferred to the client.
Since
Protocol A604
Definition at line 797 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
uint32 FmiApplicationLayer::mFileSize
file size (FMI_GPI_FILE_INFORMATION)
Since
Protocol A604
Definition at line 566 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and CGpiQueryDlg::OnGpiInfoReceived().
uint32 FmiApplicationLayer::mFileTransferBytesDone
Number of bytes of the file that have been transferred so far.
Since
Protocol A604
Definition at line 569 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and CFileTransferProgressDlg::OnFileTransferProgress().
uint32 FmiApplicationLayer::mFileTransferSize
Total number of bytes in the file being transferred.
Since
Protocol A604
Definition at line 572 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), CFileTransferProgressDlg::OnFileTransferProgress(), and CFileTransferProgressDlg::OnFileTransferStateChange().
transfer_state FmiApplicationLayer::mFileTransferState
State of the current file transfer (in progress, completed, etc.)
Since
Protocol A604
Definition at line 575 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), CFileTransferProgressDlg::OnFileTransferStateChange(), and stopFileTransfer().
uint8 FmiApplicationLayer::mFileVersion[16]
file version (FMI_GPI_FILE_INFORMATION)
Since
Protocol A604
Definition at line 559 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and CGpiQueryDlg::OnGpiInfoReceived().
uint8 FmiApplicationLayer::mFileVersionLength
Number of significant bytes in mFileVersion.
Since
Protocol A604
Definition at line 562 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and CGpiQueryDlg::OnGpiInfoReceived().
id_type FmiApplicationLayer::mFreeformFmiPacketId
Defaults to ID_FMI_PACKET unless overridden on command line.
Definition at line 490 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mHorizontalVelocity[15]
2-D velocity in the horizontal plane in meters per second from the last PVT packet, as an ASCII null-terminated string
String is formatted with three decimal places and includes the unit "m/s" and heading as the nearest cardinal (N, E, S, W) or inter-cardinal direction (NE, SE, NW, SW)
Definition at line 465 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
CTime FmiApplicationLayer::mLastClientPingTime
Last time when a client to server ping was received.
Since
Protocol A604
Definition at line 586 of file FmiApplicationLayer.h.
Referenced by CPingStatusDlg::updateTextFields().
file_packet_data_type FmiApplicationLayer::mLastFilePacketSent private
The last file packet that was sent.
Since
Protocol A604
Definition at line 800 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
CTime FmiApplicationLayer::mLastServerPingTime
Last time when a server to client ping was received.
Since
Protocol A604
Definition at line 590 of file FmiApplicationLayer.h.
Referenced by CPingStatusDlg::updateTextFields().
long_text_msg_data_type FmiApplicationLayer::mLongTextMessage[10] private
Contains the data for the most recent long text message.
Definition at line 859 of file FmiApplicationLayer.h.
bool FmiApplicationLayer::mLongTextMessageInProgress private
Indicates whether a long text message is in progress.
Definition at line 856 of file FmiApplicationLayer.h.
uint8 FmiApplicationLayer::mLongTextMessagePayloadSize[10] private
Indicates the lengths of the long text message packets.
Definition at line 862 of file FmiApplicationLayer.h.
char FmiApplicationLayer::mProtocols[PROTOCOL_SIZE]
Null-terminated ASCII string containing the protocols supported by the client.
The list is space-delimited, and each protocol is in the format Xnnn where X is the protocol type (A/D/L/T) and nnn is the number (602, etc.)
Definition at line 483 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtAltitude[13]
Altitude in meters from the last PVT packet, as an ASCII null-terminated string.
Altitude is formatted with three decimal places and is relative to the WGS84 ellipsoid.
Definition at line 440 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtDate[11]
Date from the last PVT packet, as an ASCII null-terminated string of the form MM/DD/YYYY.
Definition at line 417 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtEastWestVelocity[15]
East-west velocity in meters per second from the last PVT packet, as an ASCII null-terminated string.
String is formatted with three decimal places and includes the unit "m/s" and direction (W or E)
Definition at line 446 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPVTFixType[9]
GPS fix type from the last PVT packet, interpreted as an null-terminated ASCII string.
Definition at line 413 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtLatitude[14]
Latitude in degrees from the last PVT packet, as an ASCII null-terminated string.
Latitude is formatted with six decimal places and is suffixed by the degree symbol and N or S.
Definition at line 428 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtLongitude[14]
Longitude in degrees from the last PVT packet, as an ASCII null-terminated string.
Longitude is formatted with six decimal places and is suffixed by the degree symbol and E or W.
Definition at line 434 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtNorthSouthVelocity[15]
North-south velocity in meters per second from the last PVT packet, as an ASCII null-terminated string.
String is formatted with three decimal places and includes the unit "m/s" and direction (N or S)
Definition at line 452 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtTime[13]
Time from the last PVT packet.
This is an ASCII null-terminated string of the form HH:MM:SS AA (AA is AM or PM) in the server's time zone
Definition at line 422 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
char FmiApplicationLayer::mPvtUpDownVelocity[15]
Up-down velocity in meters per second from the last PVT packet, as an ASCII null-terminated string.
String is formatted with three decimal places and includes the unit "m/s" and direction (U or D)
Definition at line 458 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
bool FmiApplicationLayer::mRefreshingCannedMessages private
If TRUE, FmiApplicationLayer is handling a request to refresh the canned message list.
Since
Protocol A604
Definition at line 825 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
bool FmiApplicationLayer::mRefreshingCannedResponses private
If TRUE, FmiApplicationLayer is handling a request to refresh the canned response list.
Since
Protocol A604
Definition at line 821 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
bool FmiApplicationLayer::mRefreshingDriverStatusList private
If TRUE, FmiApplicationLayer is handling a request to refresh the driver status list.
Since
Protocol A604
Definition at line 817 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
FileBackedMap<InboxListItem> FmiApplicationLayer::mSentCannedResponseMessages
List of message IDs for canned response text messages.
Used in the handler for the text message ack to determine whether the ID corresponds to OK/Yes/No or a canned response id.
Since
Protocol A604
Definition at line 606 of file FmiApplicationLayer.h.
Referenced by resetCannedResponseMessages().
char FmiApplicationLayer::mSentDriverId[50] private
The last driver ID that was sent to the client.
This is a null-terminated string in the client's codepage.
Since
Protocol A604
Definition at line 793 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
uint32 FmiApplicationLayer::mSentDriverStatus private
The last driver status that was sent to the client.
Since
Protocol A604
Definition at line 788 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
int FmiApplicationLayer::mServerPingCount
Number of server-to-client pings sent; can be reset by the user.
Since
Protocol A604
Definition at line 582 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), CPingStatusDlg::OnBnClickedResetServer(), and CPingStatusDlg::updateTextFields().
bool FmiApplicationLayer::mStopFileTransfer
Flag to indicate that the user wants to stop the file transfer.
Processed when the next file data receipt is received.
Since
Protocol A604
Definition at line 613 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and stopFileTransfer().
std::vector<uint32> FmiApplicationLayer::mStopIndexInList
Vector relating the stop list to unique_ids.
mStopIndexInList[n] contains the unique_id of the nth stop in the list. n=0 is the first stop in the list.
Since
Protocol A603
Definition at line 536 of file FmiApplicationLayer.h.
Referenced by resetSavedStops().
bool FmiApplicationLayer::mStopListInitialized
If TRUE, the stop list has been initialized.
Definition at line 405 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer().
message_throttling_data_type FmiApplicationLayer::mThrottledProtocols[60]
Response from the last Message Throttling Query Protocol.
Since
Protocol A605
Definition at line 619 of file FmiApplicationLayer.h.
TransportLayer* ApplicationLayer::mTransportLayer protected inherited
The next layer down in the stack.
Definition at line 56 of file ApplicationLayer.h.
Referenced by ApplicationLayer::ApplicationLayer(), clearError(), ApplicationLayer::disconnectTransportLayer(), and ApplicationLayer::~ApplicationLayer().
bool FmiApplicationLayer::mUseAOBRD
If true, allow AOBRD driver provisioning.
Definition at line 667 of file FmiApplicationLayer.h.
Referenced by CFeatureDlg::OnBnClickedOk().
bool FmiApplicationLayer::mUseMultipleDrivers
If true, multiple driver support is enabled.
Definition at line 633 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and CFeatureDlg::OnBnClickedOk().
bool FmiApplicationLayer::mUsePasswords
If true, driver password support is enabled.
Definition at line 636 of file FmiApplicationLayer.h.
Referenced by FmiApplicationLayer(), and CFeatureDlg::OnBnClickedOk().
FileBackedMap<WaypointListItem> FmiApplicationLayer::mWaypoints
Map of waypoint IDs to names.
Definition at line 627 of file FmiApplicationLayer.h.
Referenced by CWaypointDlg::OnBnClickedWptBtnDelete(), resetWaypoints(), and CWaypointDlg::updateListBox().
The documentation for this class was generated from the following files:
FmiApplicationLayer.h
FmiApplicationLayer.cpp