Garmin Fleet Management Controller: CFmiPcAppDlg Class Reference
CFmiPcAppDlg Class Reference
Main application dialog.
#include <CFmiPcAppDlg.h>
Public Member Functions
CFmiPcAppDlg (id_type freeformFmiPacketId, CWnd *aParent=NULL)
Constructor.
~CFmiPcAppDlg ()
Destructor.
void onEvent (EventId aEventId, uint32 aEventData, void *aEventDataPtr)
Handles event callbacks by translating an EventId into a windows message.
Protected Member Functions
void doComPortQuestion ()
Ask the user to select a mCom port.
virtual void DoDataExchange (CDataExchange *aDataExchange)
Perform dialog data exchange and validation.
void doOpenLogFileQuestion ()
Ask the user whether to open a log file.
CString getProductName (uint16 aProductId)
Translate a product ID into a display name.
void initProductNames ()
Initialize the list of product names.
void initStopList ()
Initialize the stop list.
afx_msg void OnBnClickedAobrdOdometer ()
Click handler for the AOBRD Set Odometer button.
afx_msg void OnBnClickedAutoETA ()
Event handler for Auto ETA Request check box.
afx_msg void OnBnClickedCannedResponses ()
Click handler for the Canned Responses button.
afx_msg void OnBnClickedCheckPVT ()
Click handler for the Enable PVT check box.
afx_msg void OnBnClickedChgAutoArvl ()
Click handler for the Change Auto-Arrival button.
afx_msg void OnBnClickedChgComPort ()
Click handler for the Change Com Port button.
afx_msg void OnBnClickedDelData ()
Click handler for the Delete Data button.
afx_msg void OnBnClickedEnable ()
Click handler for the Send Enable button.
afx_msg void OnBnClickedFileTrans ()
Click handler for the Transfer File button.
afx_msg void OnBnClickedGpiQuery ()
Click handler for the GPI Query button.
afx_msg void OnBnClickedIdStatus ()
Click handler for the Driver ID and Status button.
afx_msg void OnBnClickedManageCannedMsg ()
Click handler for the Canned Messages button.
afx_msg void OnBnClickedManageStops ()
Click handler for the Manage Stops button.
afx_msg void OnBnClickedMsgDelete ()
Click handler for the Message Delete button.
afx_msg void OnBnClickedMsgStatus ()
Click handler for the Message Status button.
afx_msg void OnBnClickedMsgThrottling ()
Click handler for the Message Throttling button.
afx_msg void OnBnClickedOk ()
Click handler for the OK button. Close the app.
afx_msg void OnBnClickedPing ()
Click handler for the Ping button.
afx_msg void OnBnClickedReqETA ()
Click handler for the Request ETA button.
afx_msg void OnBnClickedSafeMode ()
Click handler for the FMI Safe Mode button.
afx_msg void OnBnClickedSend ()
Click handler for the Send (FMI Packet) button.
afx_msg void OnBnClickedSpeedLimit ()
Click handler for the FMI Speed Limit Alerts button.
afx_msg void OnBnClickedTxt ()
Click handler for the Send Text Message button.
afx_msg void OnBnClickedUiTxtChg ()
Click handler for the Change UI Text button.
afx_msg void OnBnClickedViewlog ()
Click handler for the View Packet Log button.
afx_msg void OnBnClickedWaypoints ()
Click handler for the Waypoints button.
afx_msg LRESULT OnEventAobrdFileTransferReceived (WPARAM, LPARAM)
afx_msg LRESULT OnEventCannedMessageDlgClosed (WPARAM, LPARAM)
Handler for Canned Text Message Dialog Closed event.
afx_msg LRESULT OnEventCannedRespListReceiptError (WPARAM aResultCode, LPARAM)
Handler for the Canned Response List Rcpt Error event.
afx_msg LRESULT OnEventCannedResponseDlgClosed (WPARAM, LPARAM)
Handler for Canned Response Dialog Closed event.
afx_msg LRESULT OnEventCommErrorDlgClosed (WPARAM, LPARAM)
Handle the Comm Error Dlg Closed event.
afx_msg LRESULT OnEventCommTimeout (WPARAM, LPARAM)
Display the Com Time Out error dialog.
afx_msg LRESULT OnEventDeleteTextMessageStatus (WPARAM aEventData, LPARAM)
Handler for the Delete Text Message Status event from Com.
afx_msg LRESULT OnEventDriverIdAndStatusDlgClosed (WPARAM, LPARAM)
Handler for Driver ID and Status Dialog Closed event.
afx_msg LRESULT OnEventDriverStatusListDeleteFailed (WPARAM, LPARAM)
Handler for the Delete Driver Status Failed event from Com.
afx_msg LRESULT OnEventEsnReceived (WPARAM, LPARAM)
Handler for the Unit ID (ESN) Received event from Com.
afx_msg LRESULT OnEventEtaReceived (WPARAM, LPARAM)
Handler for the ETA Received event from Com.
afx_msg LRESULT OnEventFmiDisabled (WPARAM, LPARAM)
Set FMI as disabled.
afx_msg LRESULT OnEventFmiSafeModeError (WPARAM, LPARAM)
Handler for the FMI Safe Mode event from Com.
afx_msg LRESULT OnEventLogViewerClosed (WPARAM, LPARAM)
Handler for Log Viewer Closed event.
afx_msg LRESULT OnEventLongTextMsgError (WPARAM, LPARAM)
Handler for the Server to Client Long Text Message Error event from Com.
afx_msg LRESULT OnEventMainDlgInit (WPARAM, LPARAM)
Handler for Main Dialog Init question.
afx_msg LRESULT OnEventMsgThrottleFailed (WPARAM, LPARAM)
Handler for the Message Throttle Failed event from Com.
afx_msg LRESULT OnEventOpenTextMsgError (WPARAM, LPARAM aEventDataPtr)
Handler for the Server to Client Text Message Error event from Com.
afx_msg LRESULT OnEventProductIdReceived (WPARAM, LPARAM)
Handler for the Product ID Received event from Com.
afx_msg LRESULT OnEventProtocolsReceived (WPARAM, LPARAM)
Handler for the Protocols Received event from Com.
afx_msg LRESULT OnEventPvtReceived (WPARAM, LPARAM)
Handler for the PVT Data Received event from Com.
afx_msg LRESULT OnEventStopDone (WPARAM, LPARAM)
Handler for the Stop Done event from Com.
afx_msg LRESULT OnEventStopListDlgClosed (WPARAM, LPARAM)
Handler for Stop List Dialog Closed event.
afx_msg LRESULT OnEventTextMsgAck (WPARAM, LPARAM aEventDataPtr)
Handler for the Text Message Ack Received event from Com.
afx_msg LRESULT OnEventTxtMsgFromClient (WPARAM, LPARAM aEventDataPtr)
Handler for the Text Message Received event from Com.
afx_msg LRESULT OnEventTxtMsgStatus (WPARAM, LPARAM)
Handler for the Text Message Status Received event from Com.
afx_msg LRESULT OnEventUserInterfaceTextChangeFailed (WPARAM, LPARAM)
Handler for the UI Text Change Failed event from Com.
afx_msg LRESULT OnEventWaypointDlgClosed (WPARAM, LPARAM)
Handler for Stop List Dialog Closed event.
afx_msg void OnFileAOBRDDrivers ()
Handler for the File > AOBRD Drivers.
afx_msg void OnFileClearPacketLog ()
Handler for the File > Clear Packet Log action.
afx_msg void OnFileClose ()
Handler for the File > Close action. Close the app.
afx_msg void OnFileRebootDevice ()
Handler for the File > Reboot Device.
afx_msg void OnHelpAbout ()
Opens the About Dialog box.
virtual BOOL OnInitDialog ()
Initialize the dialog.
afx_msg void OnPaint ()
Handler for WM_PAINT message. If the dialog is minimized, draw the icon centered in the client rectangle, else call the base class implementation of OnPaint.
afx_msg HCURSOR OnQueryDragIcon ()
The system calls this function to obtain the cursor to display while the user drags the minimized window.
afx_msg void OnSysCommand (UINT nID, LPARAM lParam)
Called when the user selects a command from the Control menu, or when the user selects the Maximize or Minimize button.
afx_msg void OnTimer (UINT aTimerId)
WM_TIMER event handler.
afx_msg void OnToolsCustomForms ()
Handler for the Tools > Custom Forms action.
afx_msg void OnToolsMapViewer ()
Handler for the Tools > Map Viewer action.
afx_msg void OnUpdateFileAOBRDDrivers (CCmdUI *aCmdUI)
ON_UPDATE_COMMAND_UI handler for File > AOBRD Drivers menu item.
afx_msg void OnUpdateFileRebootDevice (CCmdUI *aCmdUI)
ON_UPDATE_COMMAND_UI handler for File > Reboot Device menu item.
afx_msg void OnUpdateFileViewlog (CCmdUI *aCmdUI)
ON_UPDATE_COMMAND_UI handler for File > View Log menu item.
afx_msg void OnViewlog (BOOL aOpenOther=FALSE)
Display the log viewer.
BOOL selectComPort ()
Show the Select Comm Port dialog.
Protected Attributes
CString m2DVelocity
Contents of PVT text box: 2-D velocity.
CString mAltitude
Contents of PVT text box: Altitude.
BOOL mAutoEtaChecked
If TRUE, the Auto ETA Request text box is checked.
CManageCannedResponseDlg * mCannedResponseDlg
Pointer to the Canned Response dialog, or NULL if no such dialog is displayed.
CCannedTxtMsgDlg * mCannedTxtMsgDlg
Pointer to the Canned Text Message dialog, or NULL if no such dialog is displayed.
FmiApplicationLayer mCom
The FmiApplicationLayer object used to communicate with the client.
CCommErrorDlg * mCommErrorDlg
Pointer to the comm error dialog, or NULL if the dialog is not open.
BOOL mComPortSelected
If TRUE, the user has selected a FmiApplicationLayer port.
CCustomFormsDlg * mCustomFormsDlg
Pointer to the Custom Forms dailog, or NULL if no such dialog is displayed.
CDriverIdAndStatusDlg * mDriverIdAndStatusDlg
Pointer to the Driver ID and Status dialog, or NULL if no such dialog is displayed.
CString mEastWestVelocity
Contents of PVT text box: East-West velocity.
CString mEtaDistance
Contents of the ETA Distance text box (distance to destination)
CString mEtaLatitude
Contents of the ETA Latitude text box (latitude of destination)
CString mEtaLongitude
Contents of the ETA Longitude text box (longitude of destination)
CString mEtaTime
Contents of the ETA Time text box (arrival time at destination)
UINT_PTR mEtaTimer
Pointer to the timer ID for the ETA timer (used to disable the timer when needed)
bool mEtaTimerEnabled
If true, mEtaTimer is a valid timer ID.
CString mGpsFix
Contents of PVT text box: GPS fix.
HICON mIconHandle
Handle to the dialog's icon.
BOOL mIgnoreTimer
If TRUE, all timers should be ignored.
LogParser * mLogParser
The log parser to use.
CLogViewerDlg * mLogViewerDlg
Pointer to the log viewer dialog, or NULL if the dialog is not open.
CMapViewerDlg * mMapViewerDlg
Pointer to the Map Viewer dailog, or NULL if no such dialog is displayed.
CString mNorthSouthVelocity
Contents of PVT text box: North-South velocity.
CString mPacketData
Contents of the FMI Packet (payload) edit box.
CString mPacketId
Contents of the FMI Packet ID edit box.
CString mProductId
Contents of Product ID text box.
std::map< uint16, CString > mProductNames
Map of numeric product IDs to displayable names.
BOOL mPvtChecked
If true, the Enable PVT check box is selected.
CString mPvtDate
Contents of PVT text box: Date.
CString mPvtLatitude
Contents of PVT text box: Latitude.
CString mPvtLongitude
Contents of PVT text box: Longitude.
CString mPvtTime
Contents of PVT text box: Time.
CString mSoftwareVersion
Contents of Software Version text box.
CStopListDlg * mStopListDlg
Pointer to the stop list dialog, or NULL if the dialog is not open.
CString mSupportedProtocols
Contents of Protocols text box.
CTxtMsgStatusDlg * mTxtMsgStatusDlg
Pointer to the message status dialog, or NULL if no text message status dialog is displayed.
CString mUnitId
Contents of the Unit ID (ESN) text box.
CString mUpDownVelocity
Contents of PVT text box: Up-Down velocity.
CWaypointDlg * mWaypointDlg
Pointer to the Waypoints dialog, or NULL if no such dialog is displayed.
Detailed Description
Main application dialog.
This is the main application dialog; it allows the user to select any FMI operation to perform. Displays show the details of the client device that is connected as well as the last ETA and PVT information received.
Definition at line 54 of file CFmiPcAppDlg.h.
Constructor & Destructor Documentation
CFmiPcAppDlg::CFmiPcAppDlg (id_type freeformFmiPacketId, CWnd * aParent = NULL)
Constructor.
Parameters
aParent The parent of this dialog
Definition at line 216 of file CFmiPcAppDlg.cpp.
References IDR_MAINFRAME.
CFmiPcAppDlg::~CFmiPcAppDlg ()
Destructor.
Definition at line 287 of file CFmiPcAppDlg.cpp.
Member Function Documentation
void CFmiPcAppDlg::doComPortQuestion () protected
Ask the user to select a mCom port.
Call selectComPort, if a port was selected send the FMI enable and start processing timer events. If the user canceled the Select Com Port dialog, close the app.
Definition at line 1375 of file CFmiPcAppDlg.cpp.
References TRUE.
void CFmiPcAppDlg::DoDataExchange (CDataExchange * aDataExchange) protected virtual
Perform dialog data exchange and validation.
Parameters
aDataExchange The DDX context
Definition at line 323 of file CFmiPcAppDlg.cpp.
References IDC_MAIN_EDIT_FMI_DATA, IDC_MAIN_EDIT_FMI_ID, IDC_MAIN_TXT_ESN, IDC_MAIN_TXT_ETA_DISTANCE, IDC_MAIN_TXT_ETA_LAT, IDC_MAIN_TXT_ETA_LON, IDC_MAIN_TXT_ETA_TIME, IDC_MAIN_TXT_PRODUCT_ID, IDC_MAIN_TXT_PVT_2D_VEL, IDC_MAIN_TXT_PVT_ALTITUDE, IDC_MAIN_TXT_PVT_DATE, IDC_MAIN_TXT_PVT_EW_VEL, IDC_MAIN_TXT_PVT_GPS_FIX, IDC_MAIN_TXT_PVT_LAT, IDC_MAIN_TXT_PVT_LON, IDC_MAIN_TXT_PVT_NS_VEL, IDC_MAIN_TXT_PVT_TIME, IDC_MAIN_TXT_PVT_UD_VEL, and IDC_MAIN_TXT_SW_VERSION.
void CFmiPcAppDlg::doOpenLogFileQuestion () protected
Ask the user whether to open a log file.
Display a message box with the question; if the user selects Yes open the log viewer, else ask the user to select a mCom port.
Definition at line 1356 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
CString CFmiPcAppDlg::getProductName (uint16 aProductId) protected
Translate a product ID into a display name.
Display an error message pop up.
Parameters
aProductId A numeric product ID returned in the Product ID and Support protocol.
Returns
A string representation of the product name
Since
Protocol A604
Note
The only product IDs that are translated are those that are known as of the date this app was published; the list is not guaranteed to be exhaustive. If this function returns Unknown as the product name, add the product ID and corresponding name to the list in initProductNames.
Definition at line 1210 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::initProductNames () protected
Initialize the list of product names.
Definition at line 1231 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::initStopList () protected
Initialize the stop list.
Send the second wave of update stop requests that actually initialize the index in the stop list.
Since
Protocol A603
Definition at line 1306 of file CFmiPcAppDlg.cpp.
References FileBackedMap< T >::begin(), FileBackedMap< T >::end(), REQUEST_STOP_STATUS, and TRUE.
void CFmiPcAppDlg::OnBnClickedAobrdOdometer () protected
Click handler for the AOBRD Set Odometer button.
Display a modal dialog allowing the user to set AOBRD Odometer reading.
Since
Protocol A610
Definition at line 2039 of file CFmiPcAppDlg.cpp.
afx_msg void CFmiPcAppDlg::OnBnClickedAutoETA () protected
Event handler for Auto ETA Request check box.
Set or kill the MAIN_ETA_TIMER_ID as appropriate.
Definition at line 1467 of file CFmiPcAppDlg.cpp.
References FALSE, MAIN_ETA_TIMER_ID, MAIN_ETA_TIMER_INTERVAL, and TRUE.
void CFmiPcAppDlg::OnBnClickedCannedResponses () protected
Click handler for the Canned Responses button.
Display the monitor for canned responses; this is implemented as a modeless dialog (i.e., does not stop input to the main window.
Since
Protocol A604
Definition at line 1613 of file CFmiPcAppDlg.cpp.
References FALSE, and IDD_CANNED_RESPONSE.
void CFmiPcAppDlg::OnBnClickedCheckPVT () protected
Click handler for the Enable PVT check box.
Send an Enable PVT or Disable PVT command as appropriate for the new state of the check box. If disabling PVT, clear the corresponding text boxes.
Definition at line 551 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
afx_msg void CFmiPcAppDlg::OnBnClickedChgAutoArvl () protected
Click handler for the Change Auto-Arrival button.
Display a modal dialog allowing the user to edit the auto-arrival options.
Since
Protocol A603
Definition at line 1503 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedChgComPort () protected
Click handler for the Change Com Port button.
Show the Select Comm Port dialog; if a mCom port was selected, send the enable.
Definition at line 581 of file CFmiPcAppDlg.cpp.
afx_msg void CFmiPcAppDlg::OnBnClickedDelData () protected
Click handler for the Delete Data button.
Display a modal dialog allowing the user to delete FMI data on the client.
Since
Protocol A603
Definition at line 1515 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedEnable () protected
Click handler for the Send Enable button.
Initiates the Enable FMI protocol, requests the ESN, requests updated status for all A603 stops, and enables PVT data and the automatic ETA request timer.
Deleting stops normally requires the data structures to be valid, but they can't possibly be since this function initializes communication. These updates will be used to clear all deleted stops out of the save file and stop id_hex list. When the user wants to view the stops, another wave of updates will be requested that will set up their position in the list.
Definition at line 599 of file CFmiPcAppDlg.cpp.
References FileBackedMap< T >::begin(), FileBackedMap< T >::end(), FALSE, CCustomFormsDlg::IDD, REQUEST_STOP_STATUS, and TRUE.
void CFmiPcAppDlg::OnBnClickedFileTrans () protected
Click handler for the Transfer File button.
Display a modal dialog allowing the user to select and transfer a file to the client.
Since
Protocol A604
Definition at line 1629 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedGpiQuery () protected
Click handler for the GPI Query button.
Display a modal dialog allowing the user to display the information associated with the FMI GPI file on the client.
Since
Protocol A604
Definition at line 1641 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedIdStatus () protected
Click handler for the Driver ID and Status button.
Display the monitor for Driver ID and Status; this is implemented as a modeless dialog (i.e., does not stop input to the main window.
Since
Protocol A604
Definition at line 1654 of file CFmiPcAppDlg.cpp.
References FALSE, and IDD_DRIVER_ID_STATUS.
void CFmiPcAppDlg::OnBnClickedManageCannedMsg () protected
Click handler for the Canned Messages button.
Display the monitor for canned messages; this is implemented as a modeless dialog (i.e., does not stop input to the main window.
Since
Protocol A604
Definition at line 1672 of file CFmiPcAppDlg.cpp.
References FALSE, and IDD_CANNED_TXT_MSG.
void CFmiPcAppDlg::OnBnClickedManageStops () protected
Click handler for the Manage Stops button.
Display the monitor for stops; this is implemented as a modeless dialog (i.e., does not stop input to the main window.
Definition at line 674 of file CFmiPcAppDlg.cpp.
References FALSE, and IDD_STOP_LIST.
void CFmiPcAppDlg::OnBnClickedMsgDelete () protected
Click handler for the Message Delete button.
Display a modal dialog allowing the user to request that a particular text message be deleted.
Since
A607
Definition at line 1983 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedMsgStatus () protected
Click handler for the Message Status button.
Display a modal dialog allowing the user to request message status for a particular message.
Since
Protocol A604
Definition at line 1689 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedMsgThrottling () protected
Click handler for the Message Throttling button.
Display a modal dialog allowing the user to change which protocols are throttled (disabled unless initiated by the server).
Since
Protocol A604
Definition at line 1702 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedOk () protected
Click handler for the OK button. Close the app.
Definition at line 713 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedPing () protected
Click handler for the Ping button.
Display a modal dialog allowing the user to view and reset ping counts and last ping times.
Since
Protocol A604
Definition at line 1714 of file CFmiPcAppDlg.cpp.
afx_msg void CFmiPcAppDlg::OnBnClickedReqETA () protected
Click handler for the Request ETA button.
Initiate an ETA Request protocol. The results will be displayed in the ETA group of text boxes when the ETA is received from the client.
Since
Protocol A603
Definition at line 1528 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedSafeMode () protected
Click handler for the FMI Safe Mode button.
Display a modal dialog allowing the user to set FMI Safe Mode Speed.
Since
Protocol A606
Definition at line 1954 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedSend () protected
Click handler for the Send (FMI Packet) button.
Sends an FMI packet containing the FMI packet ID and FMI payload entered by the user in the corresponding edit boxes.
Warning
This is intended for debugging purposes only. The user is responsible for assuring that the packet is well-formed. The app will respond to any packets sent by the client.
Since
Protocol A604
Definition at line 1394 of file CFmiPcAppDlg.cpp.
References MAX_PAYLOAD_SIZE, TRUE, UTIL_hex_to_uint16(), and UTIL_hex_to_uint8().
afx_msg void CFmiPcAppDlg::OnBnClickedSpeedLimit () protected
Click handler for the FMI Speed Limit Alerts button.
Display a modal dialog allowing the user to configure FMI speed limit alerts
Since
Protocol A608
Definition at line 2025 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedTxt () protected
Click handler for the Send Text Message button.
Display a modal dialog allowing the user to send a text message to the client.
Definition at line 723 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedUiTxtChg () protected
Click handler for the Change UI Text button.
Display a modal dialog allowing the user to change the text of certain UI elements on the client.
Since
Protocol A604
Definition at line 1726 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnBnClickedViewlog () protected
Click handler for the View Packet Log button.
Display the log viewer; this is implemented as a modeless dialog (i.e., does not stop input to the main window.
Since
Protocol A604
Definition at line 735 of file CFmiPcAppDlg.cpp.
afx_msg void CFmiPcAppDlg::OnBnClickedWaypoints () protected
Click handler for the Waypoints button.
Display the monitor for waypoints. This is implemented as a modeless dialog so that it does not stop input to the main window.
Since
Protocol A607
Definition at line 700 of file CFmiPcAppDlg.cpp.
References FALSE, and IDD_WAYPOINT.
void CWndEventListener::onEvent (EventId aEventId, uint32 aEventData, void * aEventDataPtr) virtual inherited
Handles event callbacks by translating an EventId into a windows message.
Casts this to a CWnd then posts a Windows message to it. The use of dynamic_cast is used as an alternative to the "dreaded diamond" caused by C++ multiple inheritance.
Parameters
aEventId The event ID
aEventData The event data
aEventDataPtr Pointer to more event data
Note
Interested parties receive these events as Windows messages, i.e., ON_MESSAGE(aEventId, CallbackFunction). aEventData is the WPARAM, and aEventDataPtr is the LPARAM.
Implements EventListener.
Definition at line 29 of file CWndEventListener.cpp.
References EVENT_ID_CNT, and WM_EVENT.
afx_msg LRESULT CFmiPcAppDlg::OnEventAobrdFileTransferReceived (WPARAM , LPARAM) protected
Attempt to convert received file into human-readable CSV.
Definition at line 1018 of file CFmiPcAppDlg.cpp.
References AobrdEventLogConverter::convertToCsv(), SAVE_CONVERTED_AOBRD_LOG, and SAVE_RECEIVED_AOBRD_LOG.
afx_msg LRESULT CFmiPcAppDlg::OnEventCannedMessageDlgClosed (WPARAM , LPARAM) protected
Handler for Canned Text Message Dialog Closed event.
Re-enable the button, and delete the dialog object.
Returns
0, always
Since
Protocol A604
Definition at line 1738 of file CFmiPcAppDlg.cpp.
References TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventCannedRespListReceiptError (WPARAM aResultCode, LPARAM) protected
Handler for the Canned Response List Rcpt Error event.
Show a pop up containing the error.
Parameters
aResultCode The result code sent by the client
Returns
0, always
Since
Protocol A604
Definition at line 1755 of file CFmiPcAppDlg.cpp.
References CANNED_RESP_LIST_DUPLICATE_MSG_ID, CANNED_RESP_LIST_FULL, CANNED_RESP_LIST_INVALID_COUNT, and CANNED_RESP_LIST_INVALID_MSG_ID.
afx_msg LRESULT CFmiPcAppDlg::OnEventCannedResponseDlgClosed (WPARAM , LPARAM) protected
Handler for Canned Response Dialog Closed event.
Re-enable the button, and delete the dialog object.
Returns
0, always
Since
Protocol A604
Definition at line 1810 of file CFmiPcAppDlg.cpp.
References TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventCommErrorDlgClosed (WPARAM , LPARAM) protected
Handle the Comm Error Dlg Closed event.
Delete the dialog.
Definition at line 770 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventCommTimeout (WPARAM , LPARAM) protected
Display the Com Time Out error dialog.
Display the CommError dialog. If OK/Retry was clicked, send an enable (if not in legacy mode) and continue communication. If Cancel/Exit was clicked, do nothing more; the CommErrorDlg may have sent a close message to the app dialog.
Definition at line 748 of file CFmiPcAppDlg.cpp.
References IDD_ERROR, and TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventDeleteTextMessageStatus (WPARAM aEventData, LPARAM) protected
Handler for the Delete Text Message Status event from Com.
Show a pop up containing the CCommErrorDlg.
Parameters
aEventData Boolean indicating whether the delete succeeded
Returns
0, always
Since
Protocol A607
Definition at line 1997 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventDriverIdAndStatusDlgClosed (WPARAM , LPARAM) protected
Handler for Driver ID and Status Dialog Closed event.
Re-enable the button, and delete the dialog object.
Returns
0, always
Since
Protocol A604
Definition at line 1825 of file CFmiPcAppDlg.cpp.
References TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventDriverStatusListDeleteFailed (WPARAM , LPARAM) protected
Handler for the Delete Driver Status Failed event from Com.
Show a pop up containing the error.
Returns
0, always
Since
Protocol A604
Definition at line 1840 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventEsnReceived (WPARAM , LPARAM) protected
Handler for the Unit ID (ESN) Received event from Com.
Update the Unit ID (ESN) text box.
Returns
0, always
Definition at line 783 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventEtaReceived (WPARAM , LPARAM) protected
Handler for the ETA Received event from Com.
Update the ETA group of text boxes.
Returns
0, always
Since
Protocol A603
Definition at line 1539 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventFmiDisabled (WPARAM , LPARAM) protected
Set FMI as disabled.
Once FMI is disabled, the app should not try to do anything else with the client. This flag is checked once the Delete Data dialog is closed, and is used to cause the app to exit.
Since
Protocol A604
Definition at line 1858 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventFmiSafeModeError (WPARAM , LPARAM) protected
Handler for the FMI Safe Mode event from Com.
Display an error message pop up.
Returns
0, always
Since
Protocol A606
Definition at line 1966 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventLogViewerClosed (WPARAM , LPARAM) protected
Handler for Log Viewer Closed event.
Re-enable the log viewer button, and delete the log viewer object.
Returns
0, always
Definition at line 802 of file CFmiPcAppDlg.cpp.
References TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventLongTextMsgError (WPARAM aResultCode, LPARAM aEventDataPtr) protected
Handler for the Server to Client Long Text Message Error event from Com.
Display an error message pop up.
Parameters
aEventDataPtr The message ID.
Returns
0, always
Since
Protocol A611
Definition at line 2056 of file CFmiPcAppDlg.cpp.
References LONG_TEXT_APPEND_NULL_PTR, LONG_TEXT_EXCEEDED_MAX_BYTES, LONG_TEXT_ID_IN_USE_ERROR, LONG_TEXT_ID_IN_USE_SQL_ERROR, LONG_TEXT_INVALID_ID_SIZE, LONG_TEXT_MALLOC_BUFFER_FAIL, LONG_TEXT_MALLOC_INBOX_FAIL, LONG_TEXT_NON_INC_SEQ_NUM_ERROR, LONG_TEXT_NON_ZERO_SEQ_NUM_ERROR, LONG_TEXT_SAVE_SQL_NULL_PTR, LONG_TEXT_SQL_INSERT_FAIL, LONG_TEXT_WRONG_ID_ERROR, LONG_TEXT_WRONG_ID_SIZE, LONG_TEXT_WRONG_MESSAGE_TYPE, LONG_TEXT_WRONG_ORIG_TIME, and MessageId::toCString().
afx_msg LRESULT CFmiPcAppDlg::OnEventMainDlgInit (WPARAM , LPARAM) protected
Handler for Main Dialog Init question.
Flow in main dialog is doOpenLogFileQuestion -> doComPortQuestion -> Run.
Returns
0, always
Definition at line 822 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventMsgThrottleFailed (WPARAM , LPARAM) protected
Handler for the Message Throttle Failed event from Com.
Show a pop up containing the error.
Returns
0, always
Since
Protocol A604
Definition at line 1871 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventOpenTextMsgError (WPARAM , LPARAM aEventDataPtr) protected
Handler for the Server to Client Text Message Error event from Com.
Display an error message pop up.
Parameters
aEventDataPtr The message ID.
Returns
0, always
Since
Protocol A604
Definition at line 1890 of file CFmiPcAppDlg.cpp.
References MessageId::toCString().
afx_msg LRESULT CFmiPcAppDlg::OnEventProductIdReceived (WPARAM , LPARAM) protected
Handler for the Product ID Received event from Com.
Update the product name and software version text boxes.
Returns
0, always
Definition at line 834 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventProtocolsReceived (WPARAM , LPARAM) protected
Handler for the Protocols Received event from Com.
Update the Supported Protocols text box.
Returns
0, always
Definition at line 848 of file CFmiPcAppDlg.cpp.
References FALSE, IDC_MAIN_TXT_PROTOCOLS, and PROTOCOL_SIZE.
afx_msg LRESULT CFmiPcAppDlg::OnEventPvtReceived (WPARAM , LPARAM) protected
Handler for the PVT Data Received event from Com.
Update the text boxes in the PVT group.
Returns
0, always
Definition at line 869 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventStopDone (WPARAM , LPARAM) protected
Handler for the Stop Done event from Com.
If there is no active route, clear the ETA text boxes.
Returns
0, always
Definition at line 1567 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventStopListDlgClosed (WPARAM , LPARAM) protected
Handler for Stop List Dialog Closed event.
Re-enable the button, and delete the dialog object.
Returns
0, always
Since
Protocol A604
Definition at line 906 of file CFmiPcAppDlg.cpp.
References TRUE.
afx_msg LRESULT CFmiPcAppDlg::OnEventTextMsgAck (WPARAM , LPARAM aEventDataPtr) protected
Handler for the Text Message Ack Received event from Com.
Show a pop up containing the ack.
Parameters
aEventDataPtr The ack text.
Returns
0, always
Since
Protocol A602
Definition at line 1448 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventTxtMsgFromClient (WPARAM , LPARAM aEventDataPtr) protected
Handler for the Text Message Received event from Com.
Show a pop up containing the message from the client.
Parameters
aEventDataPtr The text message from the client.
Returns
0, always
Since
Protocol A603
Definition at line 1589 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventTxtMsgStatus (WPARAM , LPARAM aEventDataPtr) protected
Handler for the Text Message Status Received event from Com.
Show a pop up containing the message status.
Parameters
aEventDataPtr The text message status details
Returns
0, always
Since
Protocol A604
Definition at line 1913 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventUserInterfaceTextChangeFailed (WPARAM , LPARAM) protected
Handler for the UI Text Change Failed event from Com.
Show a pop up containing the CCommErrorDlg.
Returns
0, always
Since
Protocol A604
Definition at line 1940 of file CFmiPcAppDlg.cpp.
afx_msg LRESULT CFmiPcAppDlg::OnEventWaypointDlgClosed (WPARAM , LPARAM) protected
Handler for Stop List Dialog Closed event.
Re-enable the button, and delete the dialog object.
Returns
0, always
Since
Protocol A604
Definition at line 922 of file CFmiPcAppDlg.cpp.
References TRUE.
void CFmiPcAppDlg::OnFileAOBRDDrivers () protected
Handler for the File > AOBRD Drivers.
Show dialog for provisioning AOBRD driver profiles.
Definition at line 1008 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnFileClearPacketLog () protected
Handler for the File > Clear Packet Log action.
Clear the packet log. If the Log Viewer is open, close it beforehand, and open it again afterward.
Definition at line 945 of file CFmiPcAppDlg.cpp.
References Logger::clearLog().
void CFmiPcAppDlg::OnFileClose () protected
Handler for the File > Close action. Close the app.
Definition at line 935 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnFileRebootDevice () protected
Handler for the File > Reboot Device.
Send a command to the attached device to reboot it.
Definition at line 983 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnHelpAbout () protected
Opens the About Dialog box.
Definition at line 1041 of file CFmiPcAppDlg.cpp.
BOOL CFmiPcAppDlg::OnInitDialog () protected virtual
Initialize the dialog.
This function is called when the window is created. It sets up the parent, so it can get info from and send a message to Com. It also registers to receive events from Com, and initializes the data structures for canned messages, canned responses, and driver ID and status. The data structures for stops are only partially initialized at this point (stop names and IDs), since the client can update and delete stops when it is disconnected from the server. The status of each stop, and removal of deleted stops, will be initialized on the first timer cycle which enables FMI and sends update requests for all stops.
Returns
TRUE, since this function does not set focus to a control
Definition at line 370 of file CFmiPcAppDlg.cpp.
References FALSE, FMI_PROTOCOL_LEVEL, IDC_MAIN_BTN_CHANGE_BAUD_RATE, IDC_MAIN_BTN_MSG_DELETE, IDC_MAIN_BTN_SEND_ALERT, IDC_MAIN_BTN_SPEED_LIMIT_ALERTS, IDC_MAIN_EDIT_FMI_DATA, IDC_MAIN_EDIT_FMI_ID, IDC_MAIN_GRP_ETA_DATA, IDC_MAIN_GRP_FMI_PACKET, IDC_MAIN_LBL_ETA_DISTANCE, IDC_MAIN_LBL_ETA_LAT, IDC_MAIN_LBL_ETA_LON, IDC_MAIN_LBL_ETA_TIME, IDC_MAIN_LBL_FMI_DATA, IDC_MAIN_LBL_FMI_ID, IDM_ABOUTBOX, IDS_ABOUTBOX, MAIN_RX_TIMER_INTERVAL, MAIN_TIMER_ID, Event::post(), and TRUE.
void CFmiPcAppDlg::OnPaint () protected
Handler for WM_PAINT message. If the dialog is minimized, draw the icon centered in the client rectangle, else call the base class implementation of OnPaint.
Definition at line 1052 of file CFmiPcAppDlg.cpp.
HCURSOR CFmiPcAppDlg::OnQueryDragIcon () protected
The system calls this function to obtain the cursor to display while the user drags the minimized window.
Returns
A handle to the cursor
Definition at line 1082 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnSysCommand (UINT aSystemCommandId, LPARAM aParam) protected
Called when the user selects a command from the Control menu, or when the user selects the Maximize or Minimize button.
Display the about box, or delegate the message to the base class.
Parameters
aSystemCommandId Specifies the type of system command requested.
aParam Unused, but passed to base class OnSysCommand.
Definition at line 1097 of file CFmiPcAppDlg.cpp.
References IDM_ABOUTBOX.
void CFmiPcAppDlg::OnTimer (UINT aTimerId) protected
WM_TIMER event handler.
The main dialog has two timers: a comm timer which polls Com frequently to drive receiving of packets, and an ETA timer, which, if enabled, requests ETA data each mPvtTime it fires.
The comm timer is required because this is a single-threaded application; if rx were to block, the UI would be unresponsive.
Parameters
aTimerId The ID of the timer that was fired.
Definition at line 1124 of file CFmiPcAppDlg.cpp.
References MAIN_ETA_TIMER_ID, MAIN_TIMER_ID, and TimerManager::tick().
void CFmiPcAppDlg::OnToolsCustomForms () protected
Handler for the Tools > Custom Forms action.
Show the Custom Forms library dialog.
Definition at line 2126 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnToolsMapViewer () protected
Handler for the Tools > Map Viewer action.
Show the Map Viewer dialog.
Definition at line 2138 of file CFmiPcAppDlg.cpp.
References CMapViewerDlg::IDD.
void CFmiPcAppDlg::OnUpdateFileAOBRDDrivers (CCmdUI * aCmdUI) protected
ON_UPDATE_COMMAND_UI handler for File > AOBRD Drivers menu item.
Called by MFC just before the File menu is displayed to determine whether AOBRD Drivers should be enabled or disabled.
Parameters
aCmdUI Pointer to the CCmdUI object representing the File > View AOBRD Drivers item.
Definition at line 997 of file CFmiPcAppDlg.cpp.
void CFmiPcAppDlg::OnUpdateFileRebootDevice (CCmdUI * aCmdUI) protected
ON_UPDATE_COMMAND_UI handler for File > Reboot Device menu item.
Called by MFC just before the File menu is displayed to determine whether Reboot Device should be enabled or disabled.
Parameters
aCmdUI Pointer to the CCmdUI object representing the File > Reboot Device menu item.
Definition at line 972 of file CFmiPcAppDlg.cpp.
References TRUE.
void CFmiPcAppDlg::OnUpdateFileViewlog (CCmdUI * aCmdUI) protected
ON_UPDATE_COMMAND_UI handler for File > View Log menu item.
Called by MFC just before the File menu is displayed to determine whether View Log should be enabled or disabled. File > View Log is given the same state as the View Log button: enabled when there is no log viewer visible, and disabled when the log viewer is shown.
Parameters
aCmdUI Pointer to the CCmdUI object representing the File > View Log menu item.
Definition at line 1160 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
void CFmiPcAppDlg::OnViewlog (BOOL aOpenOther = FALSE) protected
Display the log viewer.
Display the log viewer; this is implemented as a modeless dialog (i.e., does not stop input to the main window).
Parameters
aOpenOther If TRUE, the log viewer will start by prompting the user to open an existing packet log.
Definition at line 1182 of file CFmiPcAppDlg.cpp.
References FALSE, and IDD_LOG.
BOOL CFmiPcAppDlg::selectComPort () protected
Show the Select Comm Port dialog.
Returns
TRUE if OK was selected, FALSE otherwise.
Definition at line 1323 of file CFmiPcAppDlg.cpp.
References FALSE, and TRUE.
Member Data Documentation
CString CFmiPcAppDlg::m2DVelocity protected
Contents of PVT text box: 2-D velocity.
Definition at line 291 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mAltitude protected
Contents of PVT text box: Altitude.
Definition at line 279 of file CFmiPcAppDlg.h.
BOOL CFmiPcAppDlg::mAutoEtaChecked protected
If TRUE, the Auto ETA Request text box is checked.
Since
Protocol A603
Definition at line 327 of file CFmiPcAppDlg.h.
CManageCannedResponseDlg* CFmiPcAppDlg::mCannedResponseDlg protected
Pointer to the Canned Response dialog, or NULL if no such dialog is displayed.
Since
Protocol A604
Definition at line 364 of file CFmiPcAppDlg.h.
CCannedTxtMsgDlg* CFmiPcAppDlg::mCannedTxtMsgDlg protected
Pointer to the Canned Text Message dialog, or NULL if no such dialog is displayed.
Since
Protocol A604
Definition at line 369 of file CFmiPcAppDlg.h.
FmiApplicationLayer CFmiPcAppDlg::mCom protected
The FmiApplicationLayer object used to communicate with the client.
Definition at line 244 of file CFmiPcAppDlg.h.
CCommErrorDlg* CFmiPcAppDlg::mCommErrorDlg protected
Pointer to the comm error dialog, or NULL if the dialog is not open.
Definition at line 306 of file CFmiPcAppDlg.h.
BOOL CFmiPcAppDlg::mComPortSelected protected
If TRUE, the user has selected a FmiApplicationLayer port.
Definition at line 256 of file CFmiPcAppDlg.h.
CCustomFormsDlg* CFmiPcAppDlg::mCustomFormsDlg protected
Pointer to the Custom Forms dailog, or NULL if no such dialog is displayed.
Since
Protocol A612
Definition at line 386 of file CFmiPcAppDlg.h.
CDriverIdAndStatusDlg* CFmiPcAppDlg::mDriverIdAndStatusDlg protected
Pointer to the Driver ID and Status dialog, or NULL if no such dialog is displayed.
Since
Protocol A604
Definition at line 374 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mEastWestVelocity protected
Contents of PVT text box: East-West velocity.
Definition at line 282 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mEtaDistance protected
Contents of the ETA Distance text box (distance to destination)
Since
Protocol A603
Definition at line 344 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mEtaLatitude protected
Contents of the ETA Latitude text box (latitude of destination)
Since
Protocol A603
Definition at line 348 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mEtaLongitude protected
Contents of the ETA Longitude text box (longitude of destination)
Since
Protocol A603
Definition at line 352 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mEtaTime protected
Contents of the ETA Time text box (arrival time at destination)
Since
Protocol A603
Definition at line 340 of file CFmiPcAppDlg.h.
UINT_PTR CFmiPcAppDlg::mEtaTimer protected
Pointer to the timer ID for the ETA timer (used to disable the timer when needed)
Since
Protocol A603
Definition at line 336 of file CFmiPcAppDlg.h.
bool CFmiPcAppDlg::mEtaTimerEnabled protected
If true, mEtaTimer is a valid timer ID.
Since
Protocol A603
Definition at line 331 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mGpsFix protected
Contents of PVT text box: GPS fix.
Definition at line 264 of file CFmiPcAppDlg.h.
HICON CFmiPcAppDlg::mIconHandle protected
Handle to the dialog's icon.
Definition at line 250 of file CFmiPcAppDlg.h.
BOOL CFmiPcAppDlg::mIgnoreTimer protected
If TRUE, all timers should be ignored.
Definition at line 258 of file CFmiPcAppDlg.h.
LogParser* CFmiPcAppDlg::mLogParser protected
The log parser to use.
Definition at line 247 of file CFmiPcAppDlg.h.
CLogViewerDlg* CFmiPcAppDlg::mLogViewerDlg protected
Pointer to the log viewer dialog, or NULL if the dialog is not open.
Definition at line 309 of file CFmiPcAppDlg.h.
CMapViewerDlg* CFmiPcAppDlg::mMapViewerDlg protected
Pointer to the Map Viewer dailog, or NULL if no such dialog is displayed.
Since
Protocol A613
Definition at line 391 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mNorthSouthVelocity protected
Contents of PVT text box: North-South velocity.
Definition at line 285 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mPacketData protected
Contents of the FMI Packet (payload) edit box.
Since
Protocol A602
Definition at line 321 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mPacketId protected
Contents of the FMI Packet ID edit box.
Since
Protocol A602
Definition at line 317 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mProductId protected
Contents of Product ID text box.
Definition at line 297 of file CFmiPcAppDlg.h.
std::map<uint16, CString> CFmiPcAppDlg::mProductNames protected
Map of numeric product IDs to displayable names.
Definition at line 294 of file CFmiPcAppDlg.h.
BOOL CFmiPcAppDlg::mPvtChecked protected
If true, the Enable PVT check box is selected.
Definition at line 253 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mPvtDate protected
Contents of PVT text box: Date.
Definition at line 267 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mPvtLatitude protected
Contents of PVT text box: Latitude.
Definition at line 273 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mPvtLongitude protected
Contents of PVT text box: Longitude.
Definition at line 276 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mPvtTime protected
Contents of PVT text box: Time.
Definition at line 270 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mSoftwareVersion protected
Contents of Software Version text box.
Definition at line 300 of file CFmiPcAppDlg.h.
CStopListDlg* CFmiPcAppDlg::mStopListDlg protected
Pointer to the stop list dialog, or NULL if the dialog is not open.
Definition at line 312 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mSupportedProtocols protected
Contents of Protocols text box.
Definition at line 303 of file CFmiPcAppDlg.h.
CTxtMsgStatusDlg* CFmiPcAppDlg::mTxtMsgStatusDlg protected
Pointer to the message status dialog, or NULL if no text message status dialog is displayed.
Since
Protocol A604
Definition at line 359 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mUnitId protected
Contents of the Unit ID (ESN) text box.
Definition at line 261 of file CFmiPcAppDlg.h.
CString CFmiPcAppDlg::mUpDownVelocity protected
Contents of PVT text box: Up-Down velocity.
Definition at line 288 of file CFmiPcAppDlg.h.
CWaypointDlg* CFmiPcAppDlg::mWaypointDlg protected
Pointer to the Waypoints dialog, or NULL if no such dialog is displayed.
Since
Protocol A607
Definition at line 380 of file CFmiPcAppDlg.h.
The documentation for this class was generated from the following files:
CFmiPcAppDlg.h
CFmiPcAppDlg.cpp