Garmin Fleet Management Controller: GarminLinkLayer Class Reference
GarminLinkLayer Class Reference
Link Layer in the OSI model.
#include <GarminLinkLayer.h>
Classes
struct fifo_type
A circular FIFO buffer for processing received bytes into packets.
Public Member Functions
virtual void rx (uint8 const *const aData, uint32 const aSize)
Copy Data to FIFO.
void setPhysicalLayer (PhysicalLayer *aPort)
Set the physical layer.
void setTransportLayer (TransportLayer *aTransport)
Set the transport layer.
virtual bool tx (Packet *aPacket)
Transmit a packet.
Static Public Member Functions
static void destroyInstance ()
Delete the one and only link layer object.
static GarminLinkLayer * getInstance ()
Get the one and only link layer object.
Protected Attributes
PhysicalLayer * mPhysicalLayer
The serial port that this link layer communicates with.
TransportLayer * mTransportLayer
The transport layer that this link layer communicates with.
Private Member Functions
GarminLinkLayer ()
Construct a new GarminLinkLayer.
void getDataFromFifo (uint8 *aData, uint32 aSize)
Get Data From FIFO.
bool getPacketFromFifo ()
Frame Packet.
void incrementHead (uint32 aIncrement)
Increment FIFO head.
int numBytesInFifo ()
Calculate the number of bytes in the FIFO buffer.
Private Attributes
fifo_type mFifo
FIFO (First-In, First-Out) buffer used to store bytes received from the client until they are parsed into packets.
Static Private Attributes
static GarminLinkLayer * sInstance = NULL
The one and only instance of this class.
Detailed Description
Link Layer in the OSI model.
In the OSI model, the Data Link layer provides encapsulation of data packets into frames, frame synchronization, and error control. For Fleet Management, encapsulation means adding the frame header, frame footer, and sequencing and DLE-stuffing the elements of the packet before transmitting a packet as a frame, and removing the DLE stuffing and verifying the checksum on incoming frames. Frame synchronization is performed by receiving bytes from the serial port into a FIFO buffer, then searching the data received to find valid frames (starting with DLE and ending with DLE-ETX), and sending any valid frames received up to the TransportLayer. Error control means responding to each received frame with either ACK or NAK, depending on whether the frame was received correctly.
Definition at line 39 of file GarminLinkLayer.h.
Constructor & Destructor Documentation
GarminLinkLayer::GarminLinkLayer () private
Construct a new GarminLinkLayer.
Construct and initialize the link layer.
Definition at line 49 of file GarminLinkLayer.cpp.
References FIFO_SIZE, SerialPort::getInstance(), GarminLinkLayer::fifo_type::head, mFifo, LinkLayer::mPhysicalLayer, PhysicalLayer::setLinkLayer(), LinkLayer::setPhysicalLayer(), GarminLinkLayer::fifo_type::size, and GarminLinkLayer::fifo_type::tail.
Referenced by getInstance().
Member Function Documentation
void GarminLinkLayer::destroyInstance () static
Delete the one and only link layer object.
Definition at line 40 of file GarminLinkLayer.cpp.
References sInstance.
Referenced by getInstance().
void GarminLinkLayer::getDataFromFifo (uint8 * aData, uint32 aSize) private
Get Data From FIFO.
This procedure copies data from the FIFO and places it into a persistent buffer. It does not advance the pointers (i.e., the data remains in the buffer).
Parameters
aData The data buffer to write to
aSize The number of bytes to retrieve.
Warning
Behavior is undefined if packet_size is greater than the number of bytes in the FIFO.
Definition at line 291 of file GarminLinkLayer.cpp.
Referenced by getPacketFromFifo().
GarminLinkLayer * GarminLinkLayer::getInstance () static
Get the one and only link layer object.
Returns
The link layer
Note
GarminLinkLayer is a singleton because this application is designed to communicate with a single client device. In a server-based application, there must be one link layer per connected client.
Definition at line 27 of file GarminLinkLayer.cpp.
References destroyInstance(), GarminLinkLayer(), and sInstance.
bool GarminLinkLayer::getPacketFromFifo () private
Frame Packet.
This procedure processes raw data in the FIFO into Garmin packets, and adds the packets to the rx_queue for processing. While doing so, it also sends ACK/NAK link-level responses as appropriate, and logs the packets that are received.
Each invocation of getPacketFromFifo will add at most one packet to the rx_queue.
Returns
TRUE if it found a valid Garmin packet in the FIFO, FALSE otherwise.
Warning
This implementation is not thread-safe - this routine manipulates the fifo head pointer during the search for a complete packet, then resets it to retrieve the packet; therefore appending data to the fifo or even obtaining the size of the buffer during a get operation is unsafe. A multi-threaded implementation would need to either copy to a temporary buffer, or protect all fifo use with a mutex.
Definition at line 128 of file GarminLinkLayer.cpp.
References GarminLinkLayer::fifo_type::buffer, header_type::dle, footer_type::dle, footer_type::etx, FALSE, FIFO_SIZE, getDataFromFifo(), GarminLinkLayer::fifo_type::head, header_type::id, ID_ACK_BYTE, ID_DLE_BYTE, ID_ETX_BYTE, ID_NAK_BYTE, incrementHead(), Logger::logRawData(), GarminPacket::mChecksum, mFifo, GarminPacket::mFrame, GarminPacket::mFrameSize, MIN_PACKET_SIZE, GarminPacket::mPacketId, GarminPacket::mPayload, GarminPacket::mPayloadSize, LinkLayer::mTransportLayer, numBytesInFifo(), TransportLayer::rx(), GarminLinkLayer::fifo_type::size, header_type::size, SIZE_OF_FOOTER, SIZE_OF_HEADER, GarminLinkLayer::fifo_type::tail, TRUE, and TransportLayer::tx().
void GarminLinkLayer::incrementHead (uint32 aIncrement) private
Increment FIFO head.
This procedure increments the receive FIFO's head by the amount requested, effectively removing the data from the FIFO. It will not increment the head beyond the tail, and it also accounts for wrapping.
Parameters
aIncrement The number of bytes to remove from the FIFO.
Definition at line 322 of file GarminLinkLayer.cpp.
Referenced by getPacketFromFifo().
int GarminLinkLayer::numBytesInFifo () private
Calculate the number of bytes in the FIFO buffer.
This procedure calculates the number of bytes between the head and tail of the receive FIFO.
Returns
The number of bytes held in the FIFO buffer.
Definition at line 97 of file GarminLinkLayer.cpp.
References GarminLinkLayer::fifo_type::head, mFifo, GarminLinkLayer::fifo_type::size, and GarminLinkLayer::fifo_type::tail.
Referenced by getPacketFromFifo().
void GarminLinkLayer::rx (uint8 const *const aData, uint32 const aSize) virtual
Copy Data to FIFO.
This procedure appends data (from the PC's com port) to a local rx FIFO, then calls getPacketFromFifo.
Parameters
aData Buffer containing the bytes to add to the FIFO
aSize Number of bytes to add
Implements LinkLayer.
Definition at line 67 of file GarminLinkLayer.cpp.
void LinkLayer::setPhysicalLayer (PhysicalLayer * aPort) inherited
Set the physical layer.
Set the physical layer that this LinkLayer sends bytes to and receives bytes from.
Parameters
aPort The physical layer, or NULL if none.
Definition at line 41 of file LinkLayer.cpp.
Referenced by GarminLinkLayer(), and SerialPort::~SerialPort().
void LinkLayer::setTransportLayer (TransportLayer * aTransport) inherited
Set the transport layer.
Set the transport layer that this LinkLayer sends packets to and receives packets from.
Parameters
aTransport The physical layer, or NULL if none.
Definition at line 55 of file LinkLayer.cpp.
Referenced by GarminTransportLayer::GarminTransportLayer(), and GarminTransportLayer::~GarminTransportLayer().
bool GarminLinkLayer::tx (Packet * aPacket) virtual
Transmit a packet.
Build a packet into a raw frame and call the physical layer to transmit it.
Parameters
aPacket The packet to build into a frame
Returns
True if the packet was sent successfully, false otherwise
Implements LinkLayer.
Definition at line 373 of file GarminLinkLayer.cpp.
References ID_DLE_BYTE, ID_ETX_BYTE, Logger::logRawData(), GarminPacket::mChecksum, GarminPacket::mFrame, GarminPacket::mFrameSize, GarminPacket::mPacketId, GarminPacket::mPayload, and GarminPacket::mPayloadSize.
Referenced by GarminTransportLayer::sendPacket().
Member Data Documentation
fifo_type GarminLinkLayer::mFifo private
FIFO (First-In, First-Out) buffer used to store bytes received from the client until they are parsed into packets.
Definition at line 88 of file GarminLinkLayer.h.
Referenced by GarminLinkLayer(), getPacketFromFifo(), and numBytesInFifo().
PhysicalLayer* LinkLayer::mPhysicalLayer protected inherited
The serial port that this link layer communicates with.
Definition at line 74 of file LinkLayer.h.
Referenced by GarminLinkLayer(), and LinkLayer::~LinkLayer().
TransportLayer* LinkLayer::mTransportLayer protected inherited
The transport layer that this link layer communicates with.
Definition at line 77 of file LinkLayer.h.
Referenced by getPacketFromFifo().
GarminLinkLayer * GarminLinkLayer::sInstance = NULL static private
The one and only instance of this class.
Definition at line 84 of file GarminLinkLayer.h.
Referenced by destroyInstance(), and getInstance().
The documentation for this class was generated from the following files:
GarminLinkLayer.h
GarminLinkLayer.cpp