Garmin Fleet Management Controller: TransportLayer Class Reference
TransportLayer Class Reference
Abstract base class for transport layer in the OSI model.
#include <TransportLayer.h>
Public Member Functions
TransportLayer ()
Constructor.
virtual ~TransportLayer ()
Destructor.
virtual void addAppLayer (ApplicationLayer *aAppLayer)
Add an app layer object to the callback list.
virtual void removeAppLayer (ApplicationLayer *aAppLayer)
Remove an app layer object from the callback list.
virtual void retry ()=0
Retry the last transmit.
virtual void rx (Packet *aPacket)=0
Callback when a complete packet is assembled by the LinkLayer.
virtual void tx (Packet *aPacket, bool aSendNow)=0
Transmit a packet.
Protected Types
typedef std::list
< ApplicationLayer * > AppLayerList
A list of app layers that are connected to this link layer.
Protected Attributes
AppLayerList mAppLayers
The application layer objects that send/receive using this GarminTransportLayer.
Detailed Description
Abstract base class for transport layer in the OSI model.
In the OSI model, the transport layer is responsible for the reliable delivery of packets to the partner device. It handles flow control (sending packets to the link layer at the appropriate rate) and error control (handling errors and retransmitting or timing out as appropriate).
Definition at line 28 of file TransportLayer.h.
Member Typedef Documentation
typedef std::list<ApplicationLayer *> TransportLayer::AppLayerList protected
A list of app layers that are connected to this link layer.
Definition at line 71 of file TransportLayer.h.
Constructor & Destructor Documentation
TransportLayer::TransportLayer ()
Constructor.
Definition at line 16 of file TransportLayer.cpp.
TransportLayer::~TransportLayer () virtual
Destructor.
Definition at line 23 of file TransportLayer.cpp.
Member Function Documentation
void TransportLayer::addAppLayer (ApplicationLayer * app) virtual
Add an app layer object to the callback list.
Parameters
app The ApplicationLayer to get packet notifications
Definition at line 32 of file TransportLayer.cpp.
Referenced by ApplicationLayer::ApplicationLayer().
void TransportLayer::removeAppLayer (ApplicationLayer * app) virtual
Remove an app layer object from the callback list.
Parameters
app The ApplicationLayer that should no longer get packet notifications
Definition at line 45 of file TransportLayer.cpp.
Referenced by ApplicationLayer::~ApplicationLayer().
virtual void TransportLayer::retry () pure virtual
Retry the last transmit.
Implemented in GarminTransportLayer.
Referenced by FmiApplicationLayer::clearError().
virtual void TransportLayer::rx (Packet * aPacket) pure virtual
Callback when a complete packet is assembled by the LinkLayer.
Parameters
aPacket The packet that was received
Implemented in GarminTransportLayer.
Referenced by GarminLinkLayer::getPacketFromFifo().
virtual void TransportLayer::tx (Packet * aPacket, bool aSendNow) pure virtual
Transmit a packet.
Parameters
aPacket The packet to transmit
aSendNow If true, the packet should be sent immediately (not FIFO)
Implemented in GarminTransportLayer.
Referenced by GarminLinkLayer::getPacketFromFifo().
Member Data Documentation
AppLayerList TransportLayer::mAppLayers protected
The application layer objects that send/receive using this GarminTransportLayer.
Definition at line 75 of file TransportLayer.h.
Referenced by GarminTransportLayer::~GarminTransportLayer().
The documentation for this class was generated from the following files:
TransportLayer.h
TransportLayer.cpp