Garmin Fleet Management Controller: StopListItem Class Reference
StopListItem Class Reference
Data structure to hold details of an A603 stop that the server needs to keep.
#include <StopListItem.h>
Public Types
typedef uint32 key_type
Public Member Functions
StopListItem ()
Constructor.
void commitName ()
Commit the item name.
CString getCurrentName () const
Get the current name of this item.
const key_type & getId () const
Get item's ID.
stop_status_status_type getStopStatus () const
Get the stop status.
BOOL isValid () const
Check whether this item is valid.
virtual void readFromStream (std::istream &aStream)
Read a ClientListItem from an input stream.
void setCurrentName (CString aName)
Set the current name of the stop.
void setId (const key_type &aId)
Set item's ID.
void setParent (FileBackedMap< StopListItem > *aParent)
Set the parent.
void setParent (FileBackedMap< ClientListItem > *aParent)
Set the parent.
void setStopStatus (stop_status_status_type aStatus)
Set the stop status.
void setUpdateName (CString aName)
Set pending name.
void setValid (BOOL aValid=TRUE)
Set this item as valid.
virtual void writeToStream (std::ofstream &aStream) const
Write a ClientListItem to an output stream.
Protected Member Functions
virtual void save ()
Save this item.
Protected Attributes
CString mCurrentName
The last name acknowledged by the client.
key_type mId
The unique ID of this item.
BOOL mIsValid
True if this list item is mIsValid.
CString mUpdateName
The last name entered by the user.
Private Attributes
FileBackedMap< StopListItem > * mParent
The map that this item belongs to, or NULL if none.
stop_status_status_type mStopStatus
The last known stop status for this stop.
Detailed Description
Data structure to hold details of an A603 stop that the server needs to keep.
Since
Protocol A603
Definition at line 21 of file StopListItem.h.
Member Typedef Documentation
typedef uint32 StopListItem::key_type
Definition at line 24 of file StopListItem.h.
Constructor & Destructor Documentation
StopListItem::StopListItem ()
Constructor.
Definition at line 16 of file StopListItem.cpp.
References INVALID_STOP_STATUS, and mStopStatus.
Member Function Documentation
void ClientListItem::commitName () inherited
Commit the item name.
Commit the item name and set the ClientListItem as valid
Definition at line 29 of file ClientListItem.cpp.
References ClientListItem::mCurrentName, ClientListItem::mUpdateName, and ClientListItem::setValid().
Referenced by FmiApplicationLayer::rx().
CString ClientListItem::getCurrentName () const inherited
Get the current name of this item.
Returns
The current (committed) name
Definition at line 39 of file ClientListItem.cpp.
References ClientListItem::mCurrentName.
Referenced by CDriverIdAndStatusDlg::OnLbnSelchangeStatuslist(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
const ClientListItem::key_type & ClientListItem::getId () const inherited
Get item's ID.
Get the unique ID of this item
Returns
The item's ID
Reimplemented in AobrdDriverItem, DriverLoginItem, and InboxListItem.
Definition at line 49 of file ClientListItem.cpp.
References ClientListItem::mId.
Referenced by FmiApplicationLayer::rx().
stop_status_status_type StopListItem::getStopStatus () const
Get the stop status.
Returns
the status of the stop
Definition at line 31 of file StopListItem.cpp.
References mStopStatus.
Referenced by CStopListDlg::OnEventStopListChanged().
BOOL ClientListItem::isValid () const inherited
Check whether this item is valid.
Returns
TRUE if the item is valid, FALSE otherwise
Definition at line 58 of file ClientListItem.cpp.
References ClientListItem::mIsValid.
Referenced by CAobrdDriversDlg::OnBnClickedSet(), FmiApplicationLayer::procDriverStatusUpdate(), and FmiApplicationLayer::rx().
void StopListItem::readFromStream (std::istream & aStream) virtual
Read a ClientListItem from an input stream.
Read id and current name from the input stream, and updates the member variables appropriately.
Parameters
aStream The stream to read from
Reimplemented from ClientListItem.
Definition at line 21 of file StopListItem.cpp.
References INVALID_STOP_STATUS, and mStopStatus.
void ClientListItem::save () protected virtual inherited
Save this item.
Invokes parent to save all items
Reimplemented in AobrdDriverItem, WaypointListItem, and DriverLoginItem.
Definition at line 172 of file ClientListItem.cpp.
References ClientListItem::mParent, and FileBackedMap< T >::save().
void StopListItem::setCurrentName (CString aName)
Set the current name of the stop.
Parameters
aName The new name of the stop
Definition at line 65 of file StopListItem.cpp.
Referenced by CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::sendA603Stop(), and CMapViewerDlg::sendRouteToDevice().
void ClientListItem::setId (const key_type & aId) inherited
Set item's ID.
Parameters
aId The item's ID
Reimplemented in DriverLoginItem.
Definition at line 101 of file ClientListItem.cpp.
Referenced by CStopNewDlg::OnBnClickedOk(), and FmiApplicationLayer::sendCannedMessage().
void StopListItem::setParent (FileBackedMap< StopListItem > * aParent)
Set the parent.
Parameters
aParent The FileBackedMap that contains this item
Definition at line 53 of file StopListItem.cpp.
void ClientListItem::setParent (FileBackedMap< ClientListItem > * aParent) inherited
Set the parent.
Parameters
aParent The FileBackedMap that contains this item
Definition at line 113 of file ClientListItem.cpp.
void StopListItem::setStopStatus (stop_status_status_type aStatus)
Set the stop status.
Parameters
aStatus The new stop status
Definition at line 41 of file StopListItem.cpp.
Referenced by CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::sendA603Stop(), and CMapViewerDlg::sendRouteToDevice().
void ClientListItem::setUpdateName (CString aName) inherited
Set pending name.
Set the pending name of this ClientListItem. This does not become the item's name until commitName is called.
Parameters
aName The pending name to set
Definition at line 127 of file ClientListItem.cpp.
Referenced by FmiApplicationLayer::sendCannedMessage(), FmiApplicationLayer::sendCannedResponse(), FmiApplicationLayer::sendCreateWaypointCat(), FmiApplicationLayer::sendDriverStatusListItem(), and FmiApplicationLayer::sendWaypoint().
void ClientListItem::setValid (BOOL aValid = TRUE) inherited
Set this item as valid.
Set the valid flag. If this item is part of a FileBackedMap, save the map.
Parameters
aValid If TRUE, the item is valid.
Definition at line 141 of file ClientListItem.cpp.
Referenced by ClientListItem::commitName(), CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendA603Stop(), FmiApplicationLayer::sendDeleteWaypointCat(), and CMapViewerDlg::sendRouteToDevice().
void ClientListItem::writeToStream (std::ofstream & aStream) const virtual inherited
Write a ClientListItem to an output stream.
Append id and current name to the output stream.
Parameters
aStream The stream to write to
Reimplemented in AobrdDriverItem, DriverLoginItem, and WaypointListItem.
Definition at line 155 of file ClientListItem.cpp.
Referenced by WaypointListItem::writeToStream().
Member Data Documentation
CString ClientListItem::mCurrentName protected inherited
The last name acknowledged by the client.
Definition at line 75 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), ClientListItem::commitName(), and ClientListItem::getCurrentName().
key_type ClientListItem::mId protected inherited
The unique ID of this item.
Definition at line 84 of file ClientListItem.h.
Referenced by ClientListItem::getId().
BOOL ClientListItem::mIsValid protected inherited
True if this list item is mIsValid.
Definition at line 81 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::isValid().
FileBackedMap<StopListItem>* StopListItem::mParent private
The map that this item belongs to, or NULL if none.
Definition at line 59 of file StopListItem.h.
stop_status_status_type StopListItem::mStopStatus private
The last known stop status for this stop.
Note
This may be out of date if the stop status protocol is throttled or if the update process that occurs when the server begins communicating with the client has not completed.
Definition at line 56 of file StopListItem.h.
Referenced by getStopStatus(), readFromStream(), and StopListItem().
CString ClientListItem::mUpdateName protected inherited
The last name entered by the user.
Definition at line 78 of file ClientListItem.h.
Referenced by ClientListItem::ClientListItem(), and ClientListItem::commitName().
The documentation for this class was generated from the following files:
StopListItem.h
StopListItem.cpp