Garmin Fleet Management Controller: CWebBrowser2 Class Reference
CWebBrowser2 Class Reference
Web Browser ActiveX wrapper, generated by Visual Studio.
#include <CWebBrowser2.h>
Public Member Functions
void ClientToWindow (long *pcx, long *pcy)
virtual BOOL Create (LPCTSTR, LPCTSTR lpszWindowName, DWORD dwStyle, const RECT &rect, CWnd *pParentWnd, UINT nID, CCreateContext *)
BOOL Create (LPCTSTR lpszWindowName, DWORD dwStyle, const RECT &rect, CWnd *pParentWnd, UINT nID, CFile *pPersist=NULL, BOOL bStorage=FALSE, BSTR bstrLicKey=NULL)
void ExecWB (long cmdID, long cmdexecopt, VARIANT *pvaIn, VARIANT *pvaOut)
BOOL get_AddressBar ()
LPDISPATCH get_Application ()
BOOL get_Busy ()
LPDISPATCH get_Container ()
LPDISPATCH get_Document ()
CString get_FullName ()
BOOL get_FullScreen ()
long get_Height ()
long get_HWND ()
long get_Left ()
CString get_LocationName ()
CString get_LocationURL ()
BOOL get_MenuBar ()
CString get_Name ()
BOOL get_Offline ()
LPDISPATCH get_Parent ()
CString get_Path ()
long get_ReadyState ()
BOOL get_RegisterAsBrowser ()
BOOL get_RegisterAsDropTarget ()
BOOL get_Resizable ()
BOOL get_Silent ()
BOOL get_StatusBar ()
CString get_StatusText ()
BOOL get_TheaterMode ()
long get_ToolBar ()
long get_Top ()
BOOL get_TopLevelContainer ()
CString get_Type ()
BOOL get_Visible ()
long get_Width ()
CLSID const & GetClsid ()
IHTMLDocument2 * GetDocument ()
Shortcut method for accessing the ITHMLDocument2 instance.
VARIANT GetProperty (LPCTSTR Property)
void GoBack ()
void GoForward ()
void GoHome ()
void GoSearch ()
CComVariant InvokeScript (LPCTSTR funcName, const CStringArray *paramArray=NULL)
void Navigate (LPCTSTR URL, VARIANT *Flags, VARIANT *TargetFrameName, VARIANT *PostData, VARIANT *Headers)
void Navigate2 (VARIANT *URL, VARIANT *Flags, VARIANT *TargetFrameName, VARIANT *PostData, VARIANT *Headers)
void put_AddressBar (BOOL newValue)
void put_FullScreen (BOOL newValue)
void put_Height (long newValue)
void put_Left (long newValue)
void put_MenuBar (BOOL newValue)
void put_Offline (BOOL newValue)
void put_RegisterAsBrowser (BOOL newValue)
void put_RegisterAsDropTarget (BOOL newValue)
void put_Resizable (BOOL newValue)
void put_Silent (BOOL newValue)
void put_StatusBar (BOOL newValue)
void put_StatusText (LPCTSTR newValue)
void put_TheaterMode (BOOL newValue)
void put_ToolBar (long newValue)
void put_Top (long newValue)
void put_Visible (BOOL newValue)
void put_Width (long newValue)
void PutProperty (LPCTSTR Property, VARIANT vtValue)
long QueryStatusWB (long cmdID)
void Quit ()
void Refresh ()
void Refresh2 (VARIANT *Level)
void ShowBrowserBar (VARIANT *pvaClsid, VARIANT *pvarShow, VARIANT *pvarSize)
void Stop ()
void WriteContent (CString content)
Dynamically set the HTML content on the control.
Static Public Member Functions
static CString URLDecode (CString sIn)
translate escape sequences into their original characters
static CString URLEncode (CString sIn)
escape any special characters for use in URLs
Detailed Description
Web Browser ActiveX wrapper, generated by Visual Studio.
This class exposes methods from IWebBrowser2 from the Microsoft ActiveX component library and can be used to embed a browser into a dialog for rendering HTML and basic navigation
Definition at line 24 of file CWebBrowser2.h.
Member Function Documentation
void CWebBrowser2::ClientToWindow (long * pcx, long * pcy) inline
Definition at line 194 of file CWebBrowser2.h.
virtual BOOL CWebBrowser2::Create (LPCTSTR , LPCTSTR lpszWindowName, DWORD dwStyle, const RECT & rect, CWnd * pParentWnd, UINT nID, CCreateContext *) inline virtual
Definition at line 35 of file CWebBrowser2.h.
References GetClsid().
BOOL CWebBrowser2::Create (LPCTSTR lpszWindowName, DWORD dwStyle, const RECT & rect, CWnd * pParentWnd, UINT nID, CFile * pPersist = NULL, BOOL bStorage = FALSE, BSTR bstrLicKey = NULL) inline
Definition at line 42 of file CWebBrowser2.h.
References GetClsid().
void CWebBrowser2::ExecWB (long cmdID, long cmdexecopt, VARIANT * pvaIn, VARIANT * pvaOut) inline
Definition at line 313 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_AddressBar () inline
Definition at line 384 of file CWebBrowser2.h.
LPDISPATCH CWebBrowser2::get_Application () inline
Definition at line 92 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_Busy () inline
Definition at line 184 of file CWebBrowser2.h.
LPDISPATCH CWebBrowser2::get_Container () inline
Definition at line 104 of file CWebBrowser2.h.
LPDISPATCH CWebBrowser2::get_Document () inline
Definition at line 110 of file CWebBrowser2.h.
CString CWebBrowser2::get_FullName () inline
Definition at line 223 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_FullScreen () inline
Definition at line 290 of file CWebBrowser2.h.
long CWebBrowser2::get_Height () inline
Definition at line 161 of file CWebBrowser2.h.
long CWebBrowser2::get_HWND () inline
Definition at line 217 of file CWebBrowser2.h.
long CWebBrowser2::get_Left () inline
Definition at line 128 of file CWebBrowser2.h.
CString CWebBrowser2::get_LocationName () inline
Definition at line 172 of file CWebBrowser2.h.
CString CWebBrowser2::get_LocationURL () inline
Definition at line 178 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_MenuBar () inline
Definition at line 279 of file CWebBrowser2.h.
CString CWebBrowser2::get_Name () inline
Definition at line 211 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_Offline () inline
Definition at line 329 of file CWebBrowser2.h.
LPDISPATCH CWebBrowser2::get_Parent () inline
Definition at line 98 of file CWebBrowser2.h.
CString CWebBrowser2::get_Path () inline
Definition at line 229 of file CWebBrowser2.h.
long CWebBrowser2::get_ReadyState () inline
Definition at line 323 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_RegisterAsBrowser () inline
Definition at line 351 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_RegisterAsDropTarget () inline
Definition at line 362 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_Resizable () inline
Definition at line 395 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_Silent () inline
Definition at line 340 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_StatusBar () inline
Definition at line 246 of file CWebBrowser2.h.
CString CWebBrowser2::get_StatusText () inline
Definition at line 257 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_TheaterMode () inline
Definition at line 373 of file CWebBrowser2.h.
long CWebBrowser2::get_ToolBar () inline
Definition at line 268 of file CWebBrowser2.h.
long CWebBrowser2::get_Top () inline
Definition at line 139 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_TopLevelContainer () inline
Definition at line 116 of file CWebBrowser2.h.
CString CWebBrowser2::get_Type () inline
Definition at line 122 of file CWebBrowser2.h.
BOOL CWebBrowser2::get_Visible () inline
Definition at line 235 of file CWebBrowser2.h.
long CWebBrowser2::get_Width () inline
Definition at line 150 of file CWebBrowser2.h.
CLSID const& CWebBrowser2::GetClsid () inline
Definition at line 29 of file CWebBrowser2.h.
Referenced by Create().
IHTMLDocument2 * CWebBrowser2::GetDocument ()
Shortcut method for accessing the ITHMLDocument2 instance.
Returns
The IHTMLDocument2, if available, or NULL
Definition at line 20 of file CWebBrowser2.cpp.
Referenced by InvokeScript(), and WriteContent().
VARIANT CWebBrowser2::GetProperty (LPCTSTR Property) inline
Definition at line 204 of file CWebBrowser2.h.
void CWebBrowser2::GoBack () inline
Definition at line 58 of file CWebBrowser2.h.
void CWebBrowser2::GoForward () inline
Definition at line 62 of file CWebBrowser2.h.
void CWebBrowser2::GoHome () inline
Definition at line 66 of file CWebBrowser2.h.
void CWebBrowser2::GoSearch () inline
Definition at line 70 of file CWebBrowser2.h.
CComVariant CWebBrowser2::InvokeScript (LPCTSTR funcName, const CStringArray * paramArray = NULL)
Definition at line 85 of file CWebBrowser2.cpp.
References FALSE, and GetDocument().
void CWebBrowser2::Navigate (LPCTSTR URL, VARIANT * Flags, VARIANT * TargetFrameName, VARIANT * PostData, VARIANT * Headers) inline
Definition at line 74 of file CWebBrowser2.h.
void CWebBrowser2::Navigate2 (VARIANT * URL, VARIANT * Flags, VARIANT * TargetFrameName, VARIANT * PostData, VARIANT * Headers) inline
Definition at line 301 of file CWebBrowser2.h.
void CWebBrowser2::put_AddressBar (BOOL newValue) inline
Definition at line 390 of file CWebBrowser2.h.
void CWebBrowser2::put_FullScreen (BOOL newValue) inline
Definition at line 296 of file CWebBrowser2.h.
void CWebBrowser2::put_Height (long newValue) inline
Definition at line 167 of file CWebBrowser2.h.
void CWebBrowser2::put_Left (long newValue) inline
Definition at line 134 of file CWebBrowser2.h.
void CWebBrowser2::put_MenuBar (BOOL newValue) inline
Definition at line 285 of file CWebBrowser2.h.
void CWebBrowser2::put_Offline (BOOL newValue) inline
Definition at line 335 of file CWebBrowser2.h.
void CWebBrowser2::put_RegisterAsBrowser (BOOL newValue) inline
Definition at line 357 of file CWebBrowser2.h.
void CWebBrowser2::put_RegisterAsDropTarget (BOOL newValue) inline
Definition at line 368 of file CWebBrowser2.h.
void CWebBrowser2::put_Resizable (BOOL newValue) inline
Definition at line 401 of file CWebBrowser2.h.
void CWebBrowser2::put_Silent (BOOL newValue) inline
Definition at line 346 of file CWebBrowser2.h.
void CWebBrowser2::put_StatusBar (BOOL newValue) inline
Definition at line 252 of file CWebBrowser2.h.
void CWebBrowser2::put_StatusText (LPCTSTR newValue) inline
Definition at line 263 of file CWebBrowser2.h.
void CWebBrowser2::put_TheaterMode (BOOL newValue) inline
Definition at line 379 of file CWebBrowser2.h.
void CWebBrowser2::put_ToolBar (long newValue) inline
Definition at line 274 of file CWebBrowser2.h.
void CWebBrowser2::put_Top (long newValue) inline
Definition at line 145 of file CWebBrowser2.h.
void CWebBrowser2::put_Visible (BOOL newValue) inline
Definition at line 241 of file CWebBrowser2.h.
void CWebBrowser2::put_Width (long newValue) inline
Definition at line 156 of file CWebBrowser2.h.
void CWebBrowser2::PutProperty (LPCTSTR Property, VARIANT vtValue) inline
Definition at line 199 of file CWebBrowser2.h.
long CWebBrowser2::QueryStatusWB (long cmdID) inline
Definition at line 306 of file CWebBrowser2.h.
void CWebBrowser2::Quit () inline
Definition at line 190 of file CWebBrowser2.h.
void CWebBrowser2::Refresh () inline
Definition at line 79 of file CWebBrowser2.h.
void CWebBrowser2::Refresh2 (VARIANT * Level) inline
Definition at line 83 of file CWebBrowser2.h.
void CWebBrowser2::ShowBrowserBar (VARIANT * pvaClsid, VARIANT * pvarShow, VARIANT * pvarSize) inline
Definition at line 318 of file CWebBrowser2.h.
void CWebBrowser2::Stop () inline
Definition at line 88 of file CWebBrowser2.h.
CString CWebBrowser2::URLDecode (CString sIn) static
translate escape sequences into their original characters
This takes an encoded URL and produces a plain-text version which is useful for parsing the location URL of a browser control
Definition at line 141 of file CWebBrowser2.cpp.
Referenced by CCustomFormsDlg::OnBeforeNavigate2(), CMapViewerDlg::OnBeforeNavigate2(), and CCustomFormsDlg::refreshCatalog().
CString CWebBrowser2::URLEncode (CString sIn) static
escape any special characters for use in URLs
This takes an plain-text string and replaces several special characters with escape sequences that can be interpreted by a URL handler
Definition at line 151 of file CWebBrowser2.cpp.
void CWebBrowser2::WriteContent (CString content)
Dynamically set the HTML content on the control.
Returns
This is a convenience method for setting the browser content from memory instead of navigating to a URL
Definition at line 48 of file CWebBrowser2.cpp.
References GetDocument().
The documentation for this class was generated from the following files:
CWebBrowser2.h
CWebBrowser2.cpp