Garmin Fleet Management Controller: Event Class Reference
Event Class Reference
Event dispatcher.
#include <Event.h>
Static Public Member Functions
static void addListener (EventListener *aListener)
Adds a window that is interested in receiving events.
static void post (EventId aEventId, uint32 aEventData=0, void *aEventDataPtr=NULL)
Posts a message to all windows that have registered to get events.
static void removeListener (EventListener *aListener)
Remove a target window from the interested object list.
Static Private Attributes
static std::list< EventListener * > mListeners
List of listeners that should receive event notifications.
Detailed Description
Event dispatcher.
The Event class manages event posting between objects. To post an event, call Event::post(). The event will then be dispatched to all EventListener objects that have registered themselves via the addListener interface.
An event dispatcher is not always strictly required (direct callbacks can usually be used instead) but use of an event system improves maintainability, as it decouples event senders from receivers, and allows code to be written more expressively, in terms of real-world things that have happened.
Definition at line 35 of file Event.h.
Member Function Documentation
void Event::addListener (EventListener * aTarget) static
Adds a window that is interested in receiving events.
Parameters
aTarget The object that is interested in events
Definition at line 24 of file Event.cpp.
Referenced by EventListener::EventListener().
void Event::post (EventId aEventId, uint32 aEventData = 0, void * aEventDataPtr = NULL) static
Posts a message to all windows that have registered to get events.
Calls the onEvent function for all registered listeners.
Parameters
aEventId The event ID that is posted.
aEventData A small bit of event data, may be 0
aEventDataPtr A pointer to a longer bit of event data, may be NULL if not used
Definition at line 65 of file Event.cpp.
Referenced by Logger::clearLog(), FmiApplicationLayer::endFileReceive(), Logger::logRawData(), FmiApplicationLayer::onAck(), CFmiPcAppDlg::OnInitDialog(), GarminTransportLayer::onTimer(), CCannedTxtMsgDlg::PostNcDestroy(), CStopListDlg::PostNcDestroy(), CDriverIdAndStatusDlg::PostNcDestroy(), CManageCannedResponseDlg::PostNcDestroy(), CCommErrorDlg::PostNcDestroy(), CWaypointDlg::PostNcDestroy(), CLogViewerDlg::PostNcDestroy(), FmiApplicationLayer::procDriverStatusUpdate(), FmiApplicationLayer::resetCannedMessages(), FmiApplicationLayer::resetCannedResponses(), FmiApplicationLayer::resetDriverStatusList(), FmiApplicationLayer::resetWaypoints(), FmiApplicationLayer::rx(), FmiApplicationLayer::sendDeleteWaypoint(), FmiApplicationLayer::sendDeleteWaypointCat(), FmiApplicationLayer::sendFile(), and FmiApplicationLayer::stopFileTransfer().
void Event::removeListener (EventListener * aTarget) static
Remove a target window from the interested object list.
Parameters
aTarget The object that is no longer interested
Definition at line 40 of file Event.cpp.
Referenced by EventListener::~EventListener().
Member Data Documentation
std::list< EventListener * > Event::mListeners static private
List of listeners that should receive event notifications.
Definition at line 57 of file Event.h.
The documentation for this class was generated from the following files:
Event.h
Event.cpp