Garmin Fleet Management Controller: SerialPort Class Reference
SerialPort Class Reference
Physical layer implementation for a serial port.
#include <SerialPort.h>
Public Member Functions
uint32 getBaudRate () const
Return the last successfully applied baud rate
const CString & getLastError () const
Return a description of the last error that occurred.
const CString & getPortName () const
Get the name of the serial port that is open.
bool init (const CString &aPortName)
Initializes the port passed in.
bool isOpen () const
Indicate whether the port is open.
void onTimer ()
Timer callback.
bool setBaudRate (uint32 aBaudRate)
Set the baud rate.
virtual void setLinkLayer (LinkLayer *aLinkLayer)
Change the link layer that receives bytes from this SerialPort.
virtual bool tx (uint8 *aData, uint16 aSize)
Transmit bytes on the serial port.
Static Public Member Functions
static void destroyInstance ()
Destroy the one and only serial port object.
static SerialPort * getInstance ()
Get the one and only serial port object.
static void getPortList (std::list< CString > &aList)
Get the list of serial ports.
Protected Member Functions
SerialPort ()
Construct the SerialPort.
virtual ~SerialPort ()
Destructor. Close the serial port.
void recordErrorText (const CString &aOperation)
Store a textual description of the last error that occurred.
Static Protected Member Functions
static void getPortListEnum (std::list< CString > &aList)
Find the COM ports on the system by opening each in turn.
static bool getPortListFromRegistry (std::list< CString > &aList)
Get the list of com ports on the system by enumerating the device map in the Windows registry.
Protected Attributes
LinkLayer * mLinkLayer
The link layer that is one level up from this serial port.
Private Member Functions
void close ()
Close the COM port if one is in use.
void pumpRx ()
Receive and process any data.
Private Attributes
uint32 mBaudRate
The last successfully applied baud rate.
HANDLE mComPortHandle
File handle for the com port that is open, or INVALID_HANDLE_VALUE if the port is not open.
BOOL mHandleInitialized
If TRUE, mComPortHandle is initialized.
CString mLastErrorText
String containing the last communication error.
CString mPortName
Display name of the serial port being used for communication.
Static Private Attributes
static SerialPort * sInstance = NULL
The one and only instance of this object.
Detailed Description
Physical layer implementation for a serial port.
Definition at line 27 of file SerialPort.h.
Constructor & Destructor Documentation
SerialPort::SerialPort () protected
Construct the SerialPort.
Note
The SerialPort is constructed as a closed port; init() must be called to open the port and begin communicating.
Definition at line 77 of file SerialPort.cpp.
References mComPortHandle, and PhysicalLayer::mLinkLayer.
Referenced by getInstance().
SerialPort::~SerialPort () protected virtual
Destructor. Close the serial port.
Definition at line 412 of file SerialPort.cpp.
References close(), PhysicalLayer::mLinkLayer, and LinkLayer::setPhysicalLayer().
Member Function Documentation
void SerialPort::close () private
Close the COM port if one is in use.
Close the handle for the com port. After this is called, init() must be called to resume communication.
Definition at line 165 of file SerialPort.cpp.
References isOpen(), mComPortHandle, and mPortName.
Referenced by ~SerialPort().
void SerialPort::destroyInstance () static
Destroy the one and only serial port object.
Definition at line 49 of file SerialPort.cpp.
References sInstance.
Referenced by getInstance().
uint32 SerialPort::getBaudRate () const
Return the last successfully applied baud rate
Definition at line 522 of file SerialPort.cpp.
References mBaudRate.
SerialPort * SerialPort::getInstance () static
Get the one and only serial port object.
Returns
The serial port
Note
SerialPort is a singleton because this application is designed to communicate with a single client device. In a server-based application, there must be one serial port per connected client.
Definition at line 35 of file SerialPort.cpp.
References destroyInstance(), SerialPort(), and sInstance.
Referenced by GarminLinkLayer::GarminLinkLayer(), CSelectCommPortDlg::OnBnClickedOk(), CLogViewerDlg::OnLbnSelchangeLog(), and FmiApplicationLayer::rx().
const CString & SerialPort::getLastError () const
Return a description of the last error that occurred.
Definition at line 393 of file SerialPort.cpp.
References mLastErrorText.
void SerialPort::getPortList (std::list< CString > & aList) static
Get the list of serial ports.
Parameters
aList The list to store the port names.
Definition at line 59 of file SerialPort.cpp.
References getPortListEnum(), and getPortListFromRegistry().
Referenced by CSelectCommPortDlg::OnInitDialog().
void SerialPort::getPortListEnum (std::list< CString > & aList) static protected
Find the COM ports on the system by opening each in turn.
Parameters
aList The list to append port names to.
Definition at line 352 of file SerialPort.cpp.
Referenced by getPortList().
bool SerialPort::getPortListFromRegistry (std::list< CString > & aList) static protected
Get the list of com ports on the system by enumerating the device map in the Windows registry.
Parameters
aList The list of port names to append to
Returns
TRUE if successful, FALSE otherwise. Note that a return value of FALSE does not mean aList is untouched; aList will have all of the port names that were found.
Note
May require administrative privileges to open the registry
Definition at line 263 of file SerialPort.cpp.
Referenced by getPortList().
const CString & SerialPort::getPortName () const
Get the name of the serial port that is open.
Returns
The name of the serial port that is open, or an empty string if the port is closed.
Definition at line 454 of file SerialPort.cpp.
References mPortName.
bool SerialPort::init (const CString & port)
Initializes the port passed in.
Parameters
port Null-terminated string containing the friendly name of the port (e.g., "COM1")
Returns
TRUE if the port was successfully opened and initialized, FALSE otherwise
Definition at line 91 of file SerialPort.cpp.
References Logger::clearLog(), DEFAULT_BAUD_RATE, Logger::isLogOpen(), RX_QUEUE_SIZE, and TX_QUEUE_SIZE.
bool SerialPort::isOpen () const
Indicate whether the port is open.
Returns
true if the serial port is open, false otherwise.
Definition at line 463 of file SerialPort.cpp.
References mComPortHandle.
Referenced by close().
void SerialPort::onTimer () virtual
Timer callback.
If the serial port is open, receive (and process) anything that is ready to receive.
Implements TimerListener.
Definition at line 403 of file SerialPort.cpp.
References mComPortHandle, and pumpRx().
void SerialPort::pumpRx () private
Receive and process any data.
Definition at line 178 of file SerialPort.cpp.
References mComPortHandle, minval, PhysicalLayer::mLinkLayer, and LinkLayer::rx().
Referenced by onTimer().
void SerialPort::recordErrorText (const CString & aOperation) protected
Store a textual description of the last error that occurred.
Parameters
aOperation The name of the operation that caused the error
Definition at line 426 of file SerialPort.cpp.
bool SerialPort::setBaudRate (uint32 aBaudRate)
Set the baud rate.
Parameters
aBaudRate The new baud rate for the port, in bps. \
Definition at line 474 of file SerialPort.cpp.
References FALSE, and TRUE.
Referenced by FmiApplicationLayer::rx().
void PhysicalLayer::setLinkLayer (LinkLayer * aLinkLayer) virtual inherited
Change the link layer that receives bytes from this SerialPort.
Parameters
aLinkLayer The LinkLayer object that receives bytes, or NULL if no LinkLayer should receive data from this port.
Definition at line 19 of file PhysicalLayer.cpp.
References PhysicalLayer::mLinkLayer.
Referenced by GarminLinkLayer::GarminLinkLayer(), and LinkLayer::~LinkLayer().
bool SerialPort::tx (uint8 * aData, uint16 aSize) virtual
Transmit bytes on the serial port.
Parameters
aData The bytes to transmit
aSize The number of bytes to transmit
Returns
true if the bytes were transmitted, false otherwise
Implements PhysicalLayer.
Definition at line 228 of file SerialPort.cpp.
Member Data Documentation
uint32 SerialPort::mBaudRate private
The last successfully applied baud rate.
Definition at line 104 of file SerialPort.h.
Referenced by getBaudRate().
HANDLE SerialPort::mComPortHandle private
File handle for the com port that is open, or INVALID_HANDLE_VALUE if the port is not open.
Definition at line 90 of file SerialPort.h.
Referenced by close(), isOpen(), onTimer(), pumpRx(), and SerialPort().
BOOL SerialPort::mHandleInitialized private
If TRUE, mComPortHandle is initialized.
Definition at line 93 of file SerialPort.h.
CString SerialPort::mLastErrorText private
String containing the last communication error.
Note
This is currently only used for errors reported by SerialPort::init()
Definition at line 101 of file SerialPort.h.
Referenced by getLastError().
LinkLayer* PhysicalLayer::mLinkLayer protected inherited
The link layer that is one level up from this serial port.
Definition at line 47 of file PhysicalLayer.h.
Referenced by pumpRx(), SerialPort(), PhysicalLayer::setLinkLayer(), and ~SerialPort().
CString SerialPort::mPortName private
Display name of the serial port being used for communication.
Definition at line 96 of file SerialPort.h.
Referenced by close(), and getPortName().
SerialPort * SerialPort::sInstance = NULL static private
The one and only instance of this object.
Definition at line 86 of file SerialPort.h.
Referenced by destroyInstance(), and getInstance().
The documentation for this class was generated from the following files:
SerialPort.h
SerialPort.cpp