Garmin Fleet Management Controller: CStopNewDlg Class Reference
CStopNewDlg Class Reference
Modal dialog allowing the user to send a new stop to the client.
#include <CStopNewDlg.h>
Public Member Functions
CStopNewDlg (CWnd *aParent, FmiApplicationLayer &aCom)
Constructor.
virtual ~CStopNewDlg ()
Destructor.
Protected Types
enum StopProtocolType {
STOP_PROTOCOL_A618,
STOP_PROTOCOL_A603,
STOP_PROTOCOL_A602,
STOP_PROTOCOL_LEGACY
}
Index of the selected item in the mStopProtocol radio button group.
Protected Member Functions
virtual void DoDataExchange (CDataExchange *aDataExchange)
Perform dialog data exchange and validation.
afx_msg void OnBnClickedOk ()
Click handler for the OK button.
afx_msg void OnFormChanged ()
Change handler for all radio buttons and edit boxes on this dialog.
BOOL OnInitDialog ()
Initialize the dialog.
Protected Attributes
FmiApplicationLayer & mCom
Reference to the FMI communication controller.
BOOL mCompressLongStop
Flag to determine if A618 stop "file" should be compressed.
CString mLatitudeStr
Text in the Latitude edit box.
CString mLongitudeStr
Text in the Longitude edit box.
CString mMessageStr
Text in the Destination Name/Message edit box.
CString mStopId
Text in the Stop ID edit box.
int mStopProtocol
Index of the selected mStopProtocol.
Detailed Description
Modal dialog allowing the user to send a new stop to the client.
Definition at line 19 of file CStopNewDlg.h.
Member Enumeration Documentation
enum CStopNewDlg::StopProtocolType protected
Index of the selected item in the mStopProtocol radio button group.
Enumerator:
STOP_PROTOCOL_A618
STOP_PROTOCOL_A603
STOP_PROTOCOL_A602
STOP_PROTOCOL_LEGACY
Definition at line 35 of file CStopNewDlg.h.
Constructor & Destructor Documentation
CStopNewDlg::CStopNewDlg (CWnd * aParent, FmiApplicationLayer & aCom)
Constructor.
Parameters
aParent The parent of this dialog
aCom Reference to the FMI communication controller
Definition at line 46 of file CStopNewDlg.cpp.
CStopNewDlg::~CStopNewDlg () virtual
Destructor.
Definition at line 71 of file CStopNewDlg.cpp.
Member Function Documentation
void CStopNewDlg::DoDataExchange (CDataExchange * aDataExchange) protected virtual
Perform dialog data exchange and validation.
Parameters
aDataExchange The DDX context
Definition at line 80 of file CStopNewDlg.cpp.
References IDC_COMPRESS_LONG_STOP, and IDC_STOPNEW_EDIT_STOPID.
void CStopNewDlg::OnBnClickedOk () protected
Click handler for the OK button.
Gets the detail from the form and sends a new stop to the client using the mStopProtocol specified by the user.
Definition at line 223 of file CStopNewDlg.cpp.
References FmiApplicationLayer::getNextStopId(), sc_position_type::lat, sc_position_type::lon, FmiApplicationLayer::mA603Stops, FmiApplicationLayer::mClientCodepage, mCom, mCompressLongStop, minval, mLatitudeStr, mLongitudeStr, mMessageStr, mStopId, mStopProtocol, FileBackedMap< T >::put(), FmiApplicationLayer::sendA602Stop(), FmiApplicationLayer::sendA603Stop(), FmiApplicationLayer::sendFile(), StopListItem::setCurrentName(), ClientListItem::setId(), StopListItem::setStopStatus(), ClientListItem::setValid(), STOP_PROTOCOL_A602, STOP_PROTOCOL_A603, STOP_PROTOCOL_A618, STOP_PROTOCOL_LEGACY, STOP_STATUS_UNREAD, TRUE, UTIL_convert_degrees_to_semicircles(), and UTIL_get_current_garmin_time().
void CStopNewDlg::OnFormChanged () protected
Change handler for all radio buttons and edit boxes on this dialog.
Validate all required fields, and enable the OK button if all fields are present.
Definition at line 142 of file CStopNewDlg.cpp.
References FALSE, IDC_COMPRESS_LONG_STOP, IDC_STOPNEW_EDIT_STOPID, IDC_STOPNEW_LBL_STOPID, mLatitudeStr, mLongitudeStr, mMessageStr, mStopId, mStopProtocol, STOP_PROTOCOL_A602, STOP_PROTOCOL_A603, STOP_PROTOCOL_A618, TRUE, and UTIL_data_is_uint32().
BOOL CStopNewDlg::OnInitDialog () protected
Initialize the dialog.
This function is called when the window is created. It sets up the parent, so it can get info from and send a message to FmiApplicationLayer.
Returns
TRUE, since this function does not set focus to a control
Definition at line 103 of file CStopNewDlg.cpp.
References FALSE, FmiApplicationLayer::getNextStopId(), IDC_COMPRESS_LONG_STOP, IDC_STOPNEW_EDIT_STOPID, IDC_STOPNEW_RDO_A602, mCom, mStopId, and TRUE.
Member Data Documentation
FmiApplicationLayer& CStopNewDlg::mCom protected
Reference to the FMI communication controller.
Definition at line 52 of file CStopNewDlg.h.
Referenced by OnBnClickedOk(), and OnInitDialog().
BOOL CStopNewDlg::mCompressLongStop protected
Flag to determine if A618 stop "file" should be compressed.
Definition at line 71 of file CStopNewDlg.h.
Referenced by OnBnClickedOk().
CString CStopNewDlg::mLatitudeStr protected
Text in the Latitude edit box.
Definition at line 55 of file CStopNewDlg.h.
Referenced by OnBnClickedOk(), and OnFormChanged().
CString CStopNewDlg::mLongitudeStr protected
Text in the Longitude edit box.
Definition at line 58 of file CStopNewDlg.h.
Referenced by OnBnClickedOk(), and OnFormChanged().
CString CStopNewDlg::mMessageStr protected
Text in the Destination Name/Message edit box.
Definition at line 61 of file CStopNewDlg.h.
Referenced by OnBnClickedOk(), and OnFormChanged().
CString CStopNewDlg::mStopId protected
Text in the Stop ID edit box.
Definition at line 64 of file CStopNewDlg.h.
Referenced by OnBnClickedOk(), OnFormChanged(), and OnInitDialog().
int CStopNewDlg::mStopProtocol protected
Index of the selected mStopProtocol.
See Also
StopProtocolType
Definition at line 68 of file CStopNewDlg.h.
Referenced by OnBnClickedOk(), and OnFormChanged().
The documentation for this class was generated from the following files:
CStopNewDlg.h
CStopNewDlg.cpp