Garmin Fleet Management Controller: CAobrdDriversDlg Class Reference
CAobrdDriversDlg Class Reference
Dialog allowing the user to manage AOBRD drivers.
#include <CAobrdDriversDlg.h>
Public Member Functions
CAobrdDriversDlg (CWnd *aParent, FmiApplicationLayer &aCom)
Constructor.
virtual ~CAobrdDriversDlg ()
Destructor.
Protected Member Functions
void clearData ()
Clear values from the editable fields.
virtual void DoDataExchange (CDataExchange *pDX)
Perform dialog data exchange and validation.
afx_msg void OnBnClickedDelete ()
Button handler for the Delete button.
afx_msg void OnBnClickedOk ()
Button handler for the OK button.
afx_msg void OnBnClickedSendUpdate ()
Button handler for the Send Update button.
afx_msg void OnBnClickedSet ()
Button handler for the Set button.
afx_msg void OnBnClickedShipments ()
afx_msg void OnCancel ()
Handler for the Cancel action.
afx_msg void OnChangeDriverData ()
Edit/Change handler for the driver-specific data controls.
afx_msg void OnEnKillfocusLoginEdit ()
Handles the kill focus event for the driver ID and password edit boxes.
afx_msg void OnEnSetfocusLoginEdit ()
Handles the set focus event for the driver ID and password edit boxes.
BOOL OnInitDialog ()
This function is called when the window is created.
afx_msg void OnLbnKillfocusDriverList ()
Handles the kill focus event for the driver list.
afx_msg void OnLbnSelchangeDriverList ()
Selection Changed handler for the Driver List box.
afx_msg void OnLbnSetfocusDriverList ()
Handles the set focus event for the driver list.
void PostNcDestroy ()
Called by MFC after the window has been destroyed; performs final termination activities.
void updateListBox ()
Update the drivers list box from the drivers map owned by FmiApplicationLayer.
Protected Attributes
FmiApplicationLayer & mCom
Reference to the FMI communication controller.
CString mDriverCarrierID
DDX member: the contents of the Carrier ID edit box.
CString mDriverCarrierName
DDX member: the contents of the Carrier Name edit box.
CString mDriverFirstName
DDX member: the contents of the First Name edit box.
CString mDriverId
DDX member: the contents of the Driver ID edit box.
CString mDriverLastName
DDX member: the contents of the Last Name edit box.
int mDriverLongTermRuleset
DDX member: the selection of the Long Term Ruleset chooser.
CString mDriverPassword
DDX member: the contents of the Driver Password edit box.
int mDriverTimeZone
DDX member: the selection of the Time Zone chooser.
CListBox mListBox
List box control containing the drivers.
int mSelectedIndex
Index of the list box item currently selected.
Detailed Description
Dialog allowing the user to manage AOBRD drivers.
This dialog allows the user to set up a database of drivers that are used to authenticate and provision a device.
Since
Protocol A610
Definition at line 26 of file CAobrdDriversDlg.h.
Constructor & Destructor Documentation
CAobrdDriversDlg::CAobrdDriversDlg (CWnd * aParent, FmiApplicationLayer & aCom)
Constructor.
Parameters
aParent The parent window.
aCom Reference to the FMI communication controller
Definition at line 68 of file CAobrdDriversDlg.cpp.
CAobrdDriversDlg::~CAobrdDriversDlg () virtual
Destructor.
Definition at line 92 of file CAobrdDriversDlg.cpp.
Member Function Documentation
void CAobrdDriversDlg::clearData () protected
Clear values from the editable fields.
Definition at line 179 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::DoDataExchange (CDataExchange * aDataExchange) protected virtual
Perform dialog data exchange and validation.
Parameters
aDataExchange The DDX context
Definition at line 101 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::OnBnClickedDelete () protected
Button handler for the Delete button.
Remove the selected driver from the allowed logins.
Definition at line 268 of file CAobrdDriversDlg.cpp.
References FALSE, IDC_DRIVERS_BTN_DELETE, IDC_DRIVERS_SEND_LOGOFF, and TRUE.
void CAobrdDriversDlg::OnBnClickedOk () protected
Button handler for the OK button.
Closes the window.
Definition at line 426 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::OnBnClickedSendUpdate () protected
Button handler for the Send Update button.
Send the driver info to the device.
Definition at line 232 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::OnBnClickedSet () protected
Button handler for the Set button.
Saves the new driver info.
Definition at line 293 of file CAobrdDriversDlg.cpp.
References FALSE, AobrdDriverItem::getFirstName(), AobrdDriverItem::getLastName(), ClientListItem::isValid(), AobrdDriverItem::setCarrierID(), AobrdDriverItem::setCarrierName(), AobrdDriverItem::setFirstName(), AobrdDriverItem::setLastName(), AobrdDriverItem::setLongTermRuleset(), AobrdDriverItem::setPassword(), AobrdDriverItem::setTimeZone(), and TRUE.
void CAobrdDriversDlg::OnBnClickedShipments () protected
Definition at line 339 of file CAobrdDriversDlg.cpp.
References CAobrdDriverShipmentsDlg::ShowShipments().
void CAobrdDriversDlg::OnCancel () protected
Handler for the Cancel action.
Closes the window.
Definition at line 435 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::OnChangeDriverData () protected
Edit/Change handler for the driver-specific data controls.
If any of controls are unset, disables the Set button; if all are specified, enables the Set button.
Definition at line 353 of file CAobrdDriversDlg.cpp.
References FALSE, FMI_SUPPORT_A615, and TRUE.
void CAobrdDriversDlg::OnEnKillfocusLoginEdit () protected
Handles the kill focus event for the driver ID and password edit boxes.
Sets the default control to the OK button so that it is activated if the user presses the Enter key.
Definition at line 466 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::OnEnSetfocusLoginEdit () protected
Handles the set focus event for the driver ID and password edit boxes.
Sets the default control to the Set button so that it is activated if the user presses the Enter key.
Definition at line 455 of file CAobrdDriversDlg.cpp.
BOOL CAobrdDriversDlg::OnInitDialog () protected
This function is called when the window is created.
This function is called when the window is created. It initializes the drivers list, and sets the initial position of the window.
Returns
TRUE, since this function does not set focus to a control
Definition at line 127 of file CAobrdDriversDlg.cpp.
References FALSE, IDC_DRIVERS_BTN_DELETE, IDC_DRIVERS_LBL_LOAD_TYPE_RULESET, IDC_DRIVERS_SEND_LOGOFF, and TRUE.
void CAobrdDriversDlg::OnLbnKillfocusDriverList () protected
Handles the kill focus event for the driver list.
Sets the default control to the OK button so that it is activated if the user presses the Enter key.
Definition at line 486 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::OnLbnSelchangeDriverList () protected
Selection Changed handler for the Driver List box.
Fills in the driver ID and password fields of the dialog with the information from the selected list item, for easy editing.
Definition at line 380 of file CAobrdDriversDlg.cpp.
References FALSE, AobrdDriverItem::getCarrierID(), AobrdDriverItem::getCarrierName(), AobrdDriverItem::getDriverId(), AobrdDriverItem::getFirstName(), AobrdDriverItem::getLastName(), AobrdDriverItem::getLongTermRuleset(), AobrdDriverItem::getPassword(), AobrdDriverItem::getTimeZone(), IDC_DRIVERS_BTN_DELETE, IDC_DRIVERS_SEND_LOGOFF, and TRUE.
void CAobrdDriversDlg::OnLbnSetfocusDriverList () protected
Handles the set focus event for the driver list.
Sets the default control to the Delete button so that it is activated if the user presses the Enter key.
Definition at line 476 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::PostNcDestroy () protected
Called by MFC after the window has been destroyed; performs final termination activities.
Definition at line 444 of file CAobrdDriversDlg.cpp.
void CAobrdDriversDlg::updateListBox () protected
Update the drivers list box from the drivers map owned by FmiApplicationLayer.
Definition at line 198 of file CAobrdDriversDlg.cpp.
References FileBackedMap< T >::begin(), and FileBackedMap< T >::end().
Member Data Documentation
FmiApplicationLayer& CAobrdDriversDlg::mCom protected
Reference to the FMI communication controller.
Definition at line 67 of file CAobrdDriversDlg.h.
CString CAobrdDriversDlg::mDriverCarrierID protected
DDX member: the contents of the Carrier ID edit box.
Definition at line 91 of file CAobrdDriversDlg.h.
CString CAobrdDriversDlg::mDriverCarrierName protected
DDX member: the contents of the Carrier Name edit box.
Definition at line 88 of file CAobrdDriversDlg.h.
CString CAobrdDriversDlg::mDriverFirstName protected
DDX member: the contents of the First Name edit box.
Definition at line 82 of file CAobrdDriversDlg.h.
CString CAobrdDriversDlg::mDriverId protected
DDX member: the contents of the Driver ID edit box.
Definition at line 76 of file CAobrdDriversDlg.h.
CString CAobrdDriversDlg::mDriverLastName protected
DDX member: the contents of the Last Name edit box.
Definition at line 85 of file CAobrdDriversDlg.h.
int CAobrdDriversDlg::mDriverLongTermRuleset protected
DDX member: the selection of the Long Term Ruleset chooser.
Definition at line 94 of file CAobrdDriversDlg.h.
CString CAobrdDriversDlg::mDriverPassword protected
DDX member: the contents of the Driver Password edit box.
Definition at line 79 of file CAobrdDriversDlg.h.
int CAobrdDriversDlg::mDriverTimeZone protected
DDX member: the selection of the Time Zone chooser.
Definition at line 102 of file CAobrdDriversDlg.h.
CListBox CAobrdDriversDlg::mListBox protected
List box control containing the drivers.
Definition at line 70 of file CAobrdDriversDlg.h.
int CAobrdDriversDlg::mSelectedIndex protected
Index of the list box item currently selected.
Definition at line 73 of file CAobrdDriversDlg.h.
The documentation for this class was generated from the following files:
CAobrdDriversDlg.h
CAobrdDriversDlg.cpp