Garmin Fleet Management Controller: util.cpp File Reference
util.cpp File Reference
#include "stdafx.h"
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <time.h>
#include <math.h>
#include <zlib.h>
#include "util.h"
Functions
CString unzip (char *original)
This function will uncompress a file into a new file.
BOOL unzip (char *original, LPCTSTR destination)
This function will uncompress a file into a specified file.
void UTIL_calc_2d_direction (float32 aNorthVelocity, float32 aEastVelocity, char *aCardinalDirection, int aCardinalDirectionSize)
Determine the nearest cardinal aCardinalDirection.
double UTIL_calc_2d_speed (float32 aNorthVelocity, float32 aEastVelocity)
Determine the two-dimensional velocity.
boolean UTIL_convert_date_time_to_seconds (const date_time_data_type *aDateTime, time_type *aSeconds)
Converts a date from from a structure to a Garmin date.
double UTIL_convert_degrees_to_radians (double aDegrees)
Converts a latitude/longitude from degrees to radians.
sint32 UTIL_convert_degrees_to_semicircles (double aDegrees)
Converts a latitude/longitude from degrees to semicircles.
void UTIL_convert_gps_time_to_seconds (const gps_time_type *aGpsTime, time_type *aSeconds)
Converts from gps_time to Garmin time.
void UTIL_convert_local_to_UTC (const time_type *aLocalTime, time_type *aUtcTime)
Converts a time_type from local to UTC time.
double UTIL_convert_radians_to_degrees (double aRadians)
Converts a latitude/longitude from radians to degrees.
void UTIL_convert_seconds_to_date_type (const time_type *aSeconds, date_time_data_type *aDateTime)
Converts a Garmin date to a structure containing year, month, and day.
void UTIL_convert_seconds_to_gps_time (const time_type *aSeconds, gps_time_type *aGpsTime)
Converts Garmin time to a structure containing GPS time.
void UTIL_convert_seconds_to_time_type (const time_type *aSeconds, date_time_data_type *aDateTime)
Converts from a Garmin time to a structure containing separate members for hour, minute, and second (time_type).
double UTIL_convert_semicircles_to_degrees (sint32 aSemicircles)
Converts a latitude/longitude from semicircles to degrees.
void UTIL_convert_time_type_to_seconds (const date_time_data_type *aDateTime, time_type *aSeconds)
Converts a time_type to seconds since midnight.
void UTIL_convert_UTC_to_local (const time_type *aUtcTime, time_type *aLocalTime)
Converts a time_type from UTC to local time.
bool UTIL_data_is_printable (const char *aData, int aLength)
Determine whether an array of characters consists only of printable ASCII.
bool UTIL_data_is_uint32 (const char *aData)
Determine whether an array of characters consists only of numeric, and that the value when converted from a string is in the valid range for a uint32.
void UTIL_format_date_string (const date_time_data_type *aDateTime, char *aResultString, int aResultStringSize)
Format a date as a string.
void UTIL_format_time_string (const date_time_data_type *aDateTime, char *aResultString, int aResultStringSize)
Converts a time structure (date_time_data_type) to a time string representation.
time_type UTIL_get_current_garmin_time ()
Get the current server time in Garmin format.
time_type UTIL_get_garmin_time (tm aTimeTm)
Get the current server time in Garmin format.
uint8 UTIL_hex_to_uint16 (const char *aHexString, uint16 *aBinaryData, uint8 aMaxWords)
Converts a null-terminated string in hexadecimal format to an array of uint16 numbers, assuming natural byte ordering in the hex. No prefix should be present in the hex string.
uint16 UTIL_hex_to_uint8 (const char *aHexString, uint8 *aBinaryData, uint16 aMaxBytes)
Convert a hexadecimal ASCII string to an array of uint8.
void UTIL_uint8_to_hex (const uint8 *aData, char *aOutput, uint8 aNumBytes)
Convert from binary to a hexadecimal string.
Variables
static uint8 const sMonthDays [12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
Number of days in each month in a non-leap year.
static uint32 const sYearDays [12] = { 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334 }
Cumulative number of days in prior months in a non-leap year.
Function Documentation
CString unzip (char * original)
This function will uncompress a file into a new file.
If the original file was not gz compressed then the result file will be an exact copy of the original
Definition at line 741 of file util.cpp.
Referenced by CCustomFormsDlg::OnFormSubmitReceived().
BOOL unzip (char * original, LPCTSTR destination)
This function will uncompress a file into a specified file.
If the original file was not gz compressed then the result file will be an exact copy of the original
Definition at line 771 of file util.cpp.
References FALSE, and TRUE.
void UTIL_calc_2d_direction (float32 aNorthVelocity, float32 aEastVelocity, char * aCardinalDirection, int aCardinalDirectionSize)
Determine the nearest cardinal aCardinalDirection.
Parameters
aNorthVelocity The north velocity (negative is south)
aEastVelocity The aEastVelocity velocity (negative is west)
aCardinalDirection A buffer of at least 3 bytes to contain the cardinal direction, which is one of "N", "E", "S", "W", "NE", "NW", "SE", "SW", or ""
Definition at line 692 of file util.cpp.
References PI.
Referenced by FmiApplicationLayer::calculate2DVelocity().
double UTIL_calc_2d_speed (float32 aNorthVelocity, float32 aEastVelocity)
Determine the two-dimensional velocity.
Parameters
aNorthVelocity The north velocity (negative is south)
aEastVelocity The east velocity (negative is west)
Returns
The 2d velocity, which is sqrt(aNorthVelocity^2 + aEastVelocity^2).
Definition at line 674 of file util.cpp.
Referenced by FmiApplicationLayer::calculate2DVelocity().
boolean UTIL_convert_date_time_to_seconds (const date_time_data_type * aDateTime, time_type * aSeconds)
Converts a date from from a structure to a Garmin date.
Parameters
aDateTime Structure containing year, month, and day
aSeconds Number of seconds since Dec 31, 1989
Returns
TRUE if the conversion was successful, FALSE if the date_type does not represent a valid date between Dec 31, 1989 and Feb 5, 2126.
Definition at line 114 of file util.cpp.
References BASE_YEAR, date_time_data_type::date, date_time_data_type::_date::day, DAYS_IN_1_YEAR, DAYS_IN_4_YEARS, FALSE, FEBRUARY, date_time_data_type::_date::month, returnif_v, SECONDS_PER_DAY, sYearDays, TRUE, and date_time_data_type::_date::year.
Referenced by convertToTimeType(), and parseDateTime().
double UTIL_convert_degrees_to_radians (double aDegrees)
Converts a latitude/longitude from degrees to radians.
Parameters
aDegrees The latitude/longitude in degrees
Returns
The latitude/longitude in radians.
Definition at line 187 of file util.cpp.
References PI.
sint32 UTIL_convert_degrees_to_semicircles (double aDegrees)
Converts a latitude/longitude from degrees to semicircles.
2^31 semicircles equal 180 degrees. The conversion uses the equivalent 2^30 semicircles per 90 degrees to avoid overflow.
Parameters
aDegrees The latitude/longitude in degrees
Returns
The latitude/longitude in semicircles.
Definition at line 204 of file util.cpp.
Referenced by decodeDegreeFields(), CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::sendA602Stop(), FmiApplicationLayer::sendA603Stop(), and FmiApplicationLayer::sendWaypoint().
void UTIL_convert_gps_time_to_seconds (const gps_time_type * aGpsTime, time_type * aSeconds)
Converts from gps_time to Garmin time.
Parameters
aGpsTime Structure containing week number and time of week
aSeconds The Garmin time (seconds since Dec. 31, 1989 UTC)
Definition at line 233 of file util.cpp.
References SECONDS_PER_DAY, gps_time_type::time_of_week, and gps_time_type::week_number_days.
Referenced by FmiApplicationLayer::rx().
void UTIL_convert_local_to_UTC (const time_type * aLocalTime, time_type * aUtcTime)
Converts a time_type from local to UTC time.
Parameters
[in] aUtcTime The UTC time as a time_type.
[out] aLocalTime The local time as a time_type.
Definition at line 549 of file util.cpp.
References SECONDS_PER_MINUTE.
Referenced by convertToTimeType(), and parseDateTime().
double UTIL_convert_radians_to_degrees (double aRadians)
Converts a latitude/longitude from radians to degrees.
Parameters
aRadians The latitude/longitude in radians
Returns
The latitude/longitude in degrees
Definition at line 247 of file util.cpp.
References PI.
Referenced by FmiLogParser::getPacketDetail(), and FmiApplicationLayer::rx().
void UTIL_convert_seconds_to_date_type (const time_type * aSeconds, date_time_data_type * aDateTime)
Converts a Garmin date to a structure containing year, month, and day.
Parameters
aSeconds Number of seconds since Dec 31, 1989
aDateTime Structure containing year, month, and day
Definition at line 39 of file util.cpp.
References BASE_YEAR, date_time_data_type::date, date_time_data_type::_date::day, DAYS_IN_1_YEAR, DAYS_IN_4_YEARS, DECEMBER, FALSE, FEBRUARY, MARCH, date_time_data_type::_date::month, SECONDS_PER_DAY, sMonthDays, sYearDays, TRUE, and date_time_data_type::_date::year.
Referenced by convertFromTimeType(), convertTimeTypeToString(), FmiLogParser::formatTime(), and FmiApplicationLayer::rx().
void UTIL_convert_seconds_to_gps_time (const time_type * aSeconds, gps_time_type * aGpsTime)
Converts Garmin time to a structure containing GPS time.
Parameters
aSeconds The Garmin time (seconds since Dec. 31, 1989 UTC)
aGpsTime Structure containing week number and time of week
Returns
TRUE, always.
Definition at line 218 of file util.cpp.
References SECONDS_PER_DAY, gps_time_type::time_of_week, and gps_time_type::week_number_days.
void UTIL_convert_seconds_to_time_type (const time_type * aSeconds, date_time_data_type * aDateTime)
Converts from a Garmin time to a structure containing separate members for hour, minute, and second (time_type).
Parameters
aSeconds The Garmin time to convert
aDateTime The output structure
Definition at line 274 of file util.cpp.
References date_time_data_type::_time::hour, date_time_data_type::_time::minute, date_time_data_type::_time::second, SECONDS_PER_DAY, SECONDS_PER_HOUR, SECONDS_PER_MINUTE, and date_time_data_type::time.
Referenced by convertFromTimeType(), convertTimeTypeToString(), FmiLogParser::formatTime(), CTxtMsgFromClient::OnInitDialog(), and FmiApplicationLayer::rx().
double UTIL_convert_semicircles_to_degrees (sint32 aSemicircles)
Converts a latitude/longitude from semicircles to degrees.
Parameters
aSemicircles The latitude/longitude in semicircles
Returns
The latitude/longitude in degrees
Definition at line 260 of file util.cpp.
Referenced by encodeDegreeFields(), FmiLogParser::formatFmiPacket(), FmiLogParser::formatLatitude(), FmiLogParser::formatLongitude(), FmiLogParser::getPacketDetail(), CTxtMsgFromClient::OnInitDialog(), and FmiApplicationLayer::rx().
void UTIL_convert_time_type_to_seconds (const date_time_data_type * aDateTime, time_type * aSeconds)
Converts a time_type to seconds since midnight.
Parameters
aDateTime The structure containing hours, minutes, seconds
aSeconds The number of seconds since midnight.
Definition at line 295 of file util.cpp.
References date_time_data_type::_time::hour, date_time_data_type::_time::minute, date_time_data_type::_time::second, SECONDS_PER_HOUR, SECONDS_PER_MINUTE, and date_time_data_type::time.
Referenced by convertToTimeType(), and parseDateTime().
void UTIL_convert_UTC_to_local (const time_type * aUtcTime, time_type * aLocalTime)
Converts a time_type from UTC to local time.
Parameters
[in] aUtcTime The UTC time as a time_type.
[out] aLocalTime The local time as a time_type.
Definition at line 526 of file util.cpp.
References SECONDS_PER_MINUTE.
Referenced by convertFromTimeType(), convertTimeTypeToString(), FmiLogParser::formatTime(), CTxtMsgFromClient::OnInitDialog(), and FmiApplicationLayer::rx().
bool UTIL_data_is_printable (const char * aData, int aLength)
Determine whether an array of characters consists only of printable ASCII.
Uses isprint().
Parameters
[in] aData The character array to test.
[in] aLength The number of characters to test.
Returns
TRUE if all characters are printable, FALSE otherwise.
Definition at line 471 of file util.cpp.
Referenced by CGpiQueryDlg::OnGpiInfoReceived(), and MessageId::toCString().
bool UTIL_data_is_uint32 (const char * aData)
Determine whether an array of characters consists only of numeric, and that the value when converted from a string is in the valid range for a uint32.
Parameters
[in] aData The character array to test.
Returns
true if the resulting string is a valid uint32, false otherwise.
Definition at line 495 of file util.cpp.
References max_uint_val.
Referenced by CDriverIdAndStatusDlg::OnEnChangeEditSet(), and CStopNewDlg::OnFormChanged().
void UTIL_format_date_string (const date_time_data_type * aDateTime, char * aResultString, int aResultStringSize)
Format a date as a string.
Formats the date portion of aDateTime as a string, in MM/DD/YYYY format
Parameters
aDateTime The date to format.
aResultString Pointer to a char[11] or longer to contain the formatted date.
Definition at line 657 of file util.cpp.
References date_time_data_type::date, date_time_data_type::_date::day, date_time_data_type::_date::month, and date_time_data_type::_date::year.
Referenced by FmiLogParser::formatTime(), and FmiApplicationLayer::rx().
void UTIL_format_time_string (const date_time_data_type * aDateTime, char * aResultString, int aResultStringSize)
Converts a time structure (date_time_data_type) to a time string representation.
Parameters
[in] aDateTime The structure containing the time.
[out] aResultString A null-terminated ASCII string of the form "HH:MM:SS AA" (hours, minutes, seconds, AM/PM, respectively).
Definition at line 575 of file util.cpp.
References FALSE, date_time_data_type::_time::hour, date_time_data_type::_time::minute, date_time_data_type::_time::second, date_time_data_type::time, and TRUE.
Referenced by FmiLogParser::formatTime(), CTxtMsgFromClient::OnInitDialog(), and FmiApplicationLayer::rx().
time_type UTIL_get_current_garmin_time (void)
Get the current server time in Garmin format.
Returns
The current time as a time_type
Definition at line 603 of file util.cpp.
References UTIL_get_garmin_time().
Referenced by FmiApplicationLayer::beginA611LongTextMessage(), CFeatureDlg::OnBnClickedOk(), CStopNewDlg::OnBnClickedOk(), FmiApplicationLayer::sendA602Stop(), FmiApplicationLayer::sendA602TextMessage(), FmiApplicationLayer::sendA603Stop(), FmiApplicationLayer::sendA604TextMessage(), FmiApplicationLayer::sendA607DriverIdUpdate(), FmiApplicationLayer::sendA607DriverStatusUpdate(), FmiApplicationLayer::sendDriverIdUpdate(), FmiApplicationLayer::sendDriverStatusUpdate(), and CMapViewerDlg::sendRouteToDevice().
time_type UTIL_get_garmin_time (tm aTimeTm)
Get the current server time in Garmin format.
Returns
The current time as a time_type
Definition at line 619 of file util.cpp.
References DAYS_IN_1_YEAR, SECONDS_PER_DAY, SECONDS_PER_HOUR, SECONDS_PER_MINUTE, and sYearDays.
Referenced by UTIL_get_current_garmin_time().
uint8 UTIL_hex_to_uint16 (const char * aHexString, uint16 * aBinaryData, uint8 aMaxWords)
Converts a null-terminated string in hexadecimal format to an array of uint16 numbers, assuming natural byte ordering in the hex. No prefix should be present in the hex string.
For example, given a hex string "01020304" and aMaxWords 2, the output will be the equivalent of { 258, 772 } decimal.
Note
Conversion will stop when an invalid hexadecimal digit is encountered in the input or when the null terminator is found, whichever comes first.
Parameters
[in] aHexString The ASCII null-terminated string containing the hex to convert.
[out] aBinaryData Pointer to an array of uint16 to contain the output.
[in] aMaxWords The maximum number of words to convert.
Returns
The number of complete words converted, or 0 if either aHexString contains a character that is not a hex digit or the length of aHexString is not a multiple of 4.
Definition at line 411 of file util.cpp.
Referenced by CFmiPcAppDlg::OnBnClickedSend().
uint16 UTIL_hex_to_uint8 (const char * aHexString, uint8 * aBinaryData, uint16 aMaxBytes)
Convert a hexadecimal ASCII string to an array of uint8.
Parameters
[in] aHexString The hexadecimal string to convert. May be null-terminated. aHexString should not contain any prefix; only the digits 0-9 and a-f may be present.
[out] aBinaryData An array of uint8 to receive the output. This array's size must be at least max_bytes.
[in] aMaxBytes The maximum number of bytes to convert. If aHexString is not null-terminated its length must be at least 2 * max_bytes.
Returns
The number of bytes actually converted. This may be less than max_bytes if a null terminator was found, and will be 0 if a character that is not a hexadecimal digit was encountered or if the length of aHexString is not even.
Note
aBinaryData may be modified even if 0 is returned.
Definition at line 323 of file util.cpp.
Referenced by FmiLogParser::getPacketDetail(), FmiLogParser::getPacketTitle(), MessageId::MessageId(), CFileTransferDlg::OnBnClickedOk(), CFmiPcAppDlg::OnBnClickedSend(), FmiLogParser::resendPacket(), and FmiApplicationLayer::rx().
void UTIL_uint8_to_hex (const uint8 * aData, char * aOutput, uint8 aNumBytes)
Convert from binary to a hexadecimal string.
Converts an array of uint8 values to a displayable string, one octet (uint8) at a time. No prefix is included in the output. For example, given a null-terminated ASCII string "ABC" and aNumBytes = 4, the output would be the string "41424300".
Parameters
[in] aData The binary data.
[out] aOutput The null-terminated output string. This must be a buffer of at least (2 * aNumBytes + 1) characters.
[in] aNumBytes The number of bytes to convert.
Definition at line 376 of file util.cpp.
Referenced by CGpiQueryDlg::OnGpiInfoReceived(), and MessageId::toCString().
Variable Documentation
uint8 const sMonthDays[12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static
Number of days in each month in a non-leap year.
Definition at line 25 of file util.cpp.
Referenced by UTIL_convert_seconds_to_date_type().
uint32 const sYearDays[12] = { 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334 } static
Cumulative number of days in prior months in a non-leap year.
Definition at line 30 of file util.cpp.
Referenced by UTIL_convert_date_time_to_seconds(), UTIL_convert_seconds_to_date_type(), and UTIL_get_garmin_time().